#!/usr/bin/env python3
"""Phase 3: 4x sub-pal pixel-bias expander for RoomRom BG CHR.

Reads source 4bpp Genesis-format CHR arrays where every nibble is in {0..3}
(i.e. NES BG pixel values: 0=transparent, 1..3=indexed into a 4-color sub-pal).
For each source byte, applies the per-nibble pixel-bias rule:

    out_pixel = (in_pixel == 0) ? 0 : (sub_pal * 4 + in_pixel)

For sub_pal in {0,1,2,3}, producing 4 concatenated copies (pal0||pal1||pal2||pal3).

INPUT ASSERTION: every source nibble must already be in {0..3}. If any pixel
> 3 is encountered, abort -- means the array is already biased and re-biasing
would corrupt it.

Reads:
  data/chr/common.c                              -> common_chr[7616]
  data/chr/overworld_bg.c                        -> overworld_bg_chr[4160]
  data/chr/underworld_bg.c                       -> underworld_bg_chr[4160]
  RoomRom/src/redux_overworld_bg.c               -> redux_overworld_bg_chr[4160]
                                                  + redux_overworld_secret_chr[384]
  RoomRom/src/redux_uw_bg.c                      -> redux_uw_bg_chr[8192]
  RoomRom/src/redux_hud_chr.c                    -> redux_automap_chr[1024]

Writes:
  RoomRom/src/expanded_bg_chr.h                  -> extern declarations
  RoomRom/src/expanded_bg_chr.c                  -> all <name>_x4 arrays

Usage: python RoomRom/tools/expand_bg_chr.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ROOMROM = ROOT / "RoomRom"

# (source_path_relative_to_repo_root, array_name) tuples.
SOURCES = [
    ("data/chr/common.c",                "common_chr"),
    ("data/chr/overworld_bg.c",          "overworld_bg_chr"),
    ("data/chr/underworld_bg.c",         "underworld_bg_chr"),
    ("RoomRom/src/redux_overworld_bg.c", "redux_overworld_bg_chr"),
    ("RoomRom/src/redux_overworld_bg.c", "redux_overworld_secret_chr"),
    ("RoomRom/src/redux_uw_bg.c",        "redux_uw_bg_chr"),
    ("RoomRom/src/redux_hud_chr.c",      "redux_automap_chr"),
]

OUT_C = ROOMROM / "src" / "expanded_bg_chr.c"
OUT_H = ROOMROM / "src" / "expanded_bg_chr.h"


def fail(msg):
    print(f"expand_bg_chr: FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def parse_array(text, name):
    """Find `const unsigned char NAME[SIZE] = { ... };` and return (size, bytes)."""
    pat = re.compile(
        r"const\s+unsigned\s+char\s+" + re.escape(name) + r"\s*\[\s*(\d+)\s*\]\s*=\s*\{([^}]*)\}",
        re.MULTILINE | re.DOTALL,
    )
    m = pat.search(text)
    if not m:
        return None
    size = int(m.group(1))
    body = m.group(2)
    bytes_out = []
    for tok in re.finditer(r"0x([0-9A-Fa-f]{1,2})", body):
        bytes_out.append(int(tok.group(1), 16))
    if len(bytes_out) != size:
        fail(f"{name}: declared size {size} != parsed {len(bytes_out)} bytes")
    return size, bytes_out


def assert_pixel_range(name, data):
    for i, b in enumerate(data):
        hi = (b >> 4) & 0x0F
        lo = b & 0x0F
        if hi > 3 or lo > 3:
            fail(f"{name}: byte[{i}] = 0x{b:02X} has pixel > 3 "
                 "(array already biased? refusing to re-bias)")


def bias_byte(b, sub_pal):
    hi = (b >> 4) & 0x0F
    lo = b & 0x0F
    hi_out = 0 if hi == 0 else (sub_pal * 4 + hi)
    lo_out = 0 if lo == 0 else (sub_pal * 4 + lo)
    return ((hi_out & 0x0F) << 4) | (lo_out & 0x0F)


def expand_to_x4(data):
    out = bytearray()
    for s in (0, 1, 2, 3):
        for b in data:
            out.append(bias_byte(b, s))
    return bytes(out)


def emit_array(f, name, data):
    f.write(f"const unsigned char {name}_x4[{len(data)}] __attribute__((aligned(4))) = {{\n")
    cols = 16
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk))
        if i + cols < len(data):
            f.write(",")
        f.write("\n")
    f.write("};\n\n")


def main():
    arrays = []  # list of (name, size_per_pal, expanded_bytes)
    for rel_path, name in SOURCES:
        path = ROOT / rel_path
        if not path.exists():
            fail(f"{rel_path}: not found")
        text = path.read_text(encoding="utf-8")
        parsed = parse_array(text, name)
        if parsed is None:
            fail(f"{rel_path}: array `{name}` not found")
        size, data = parsed
        assert_pixel_range(name, data)
        x4 = expand_to_x4(data)
        arrays.append((name, size, x4))
        print(f"  {name}: {size} bytes -> {len(x4)} bytes (x4)")

    # Emit header.
    with OUT_H.open("w", encoding="utf-8") as f:
        f.write("/* Generated by RoomRom/tools/expand_bg_chr.py. Do not edit. */\n")
        f.write("#ifndef ROOMROM_EXPANDED_BG_CHR_H\n")
        f.write("#define ROOMROM_EXPANDED_BG_CHR_H\n\n")
        f.write("/* 4x pixel-biased sub-pal copies of source NES BG CHR arrays.\n"
                " * Each array is layout: pal0_bytes || pal1_bytes || pal2_bytes || pal3_bytes.\n"
                " * Per-pal stride = original array size in bytes.\n"
                " * Pixel bias applied per-nibble: out = (in == 0) ? 0 : (s*4 + in). */\n\n")
        for name, size, _ in arrays:
            f.write(f"#define {name.upper()}_PER_PAL_BYTES {size}u\n")
        f.write("\n")
        for name, _, x4 in arrays:
            f.write(f"extern const unsigned char {name}_x4[{len(x4)}];\n")
        f.write("\n#endif\n")

    # Emit source.
    with OUT_C.open("w", encoding="utf-8") as f:
        f.write("/* Generated by RoomRom/tools/expand_bg_chr.py. Do not edit. */\n")
        f.write('#include "expanded_bg_chr.h"\n\n')
        for name, _, x4 in arrays:
            emit_array(f, name, x4)

    print(f"wrote {OUT_H}")
    print(f"wrote {OUT_C}")


if __name__ == "__main__":
    main()
