#!/usr/bin/env python3
"""Phase 3 sprite-side: 4x sub-pal pixel-bias expander for RoomRom item atlas.

Mirrors RoomRom/tools/expand_bg_chr.py but operates on the live item atlas
(RoomRom/src/roomrom_item_chr.c -> roomrom_item_chr[VARIANT_COUNT][BYTES]).
Other sprite CHR (Link, sword body, common_chr sprite half) is NOT expanded
- those stay 1x in the main SPR bank because they only ever use NES sprite
sub-pal 0. Items are the only sprite category with non-trivial sub-pal
variation (bomb sub-pal 1, explosion sub-pal 1, future sword level upgrades).

Per-nibble bias rule:
    out_pixel = (in_pixel == 0) ? 0 : (sub_pal * 4 + in_pixel)

Source nibble assertion: every source pixel must already be in {0..3}
(unbiased 4-color NES sprite pixel). Aborts on out-of-range so we can't
double-bias an already-expanded array.

Reads:
  RoomRom/src/roomrom_item_chr.c -> roomrom_item_chr[VARIANT_COUNT][BYTES]

Writes:
  RoomRom/src/expanded_sprite_chr.h
  RoomRom/src/expanded_sprite_chr.c
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ROOMROM = ROOT / "RoomRom"

# (path_relative_to_repo_root, array_name)
# Item atlas only - per-category VRAM model. Link / sword body /
# common_chr sprite half stay 1x in the main SPR bank.
SOURCES = [
    ("RoomRom/src/roomrom_item_chr.c", "roomrom_item_chr"),
]

OUT_C = ROOMROM / "src" / "expanded_sprite_chr.c"
OUT_H = ROOMROM / "src" / "expanded_sprite_chr.h"


def fail(msg):
    print(f"expand_sprite_chr: FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def bias_byte(byte_val, sub_pal):
    """Apply pixel-bias rule to one source byte (high+low nibble).

    NES pixel 0 stays 0; nonzero pixels become sub_pal*4 + pixel.
    Source nibbles must be in {0..3} — aborts if not (already-biased guard).
    """
    if not (0 <= sub_pal <= 3):
        fail(f"sub_pal out of range: {sub_pal}")
    hi = (byte_val >> 4) & 0x0F
    lo = byte_val & 0x0F
    if hi > 3 or lo > 3:
        fail(f"source pixel > 3 in byte 0x{byte_val:02X} (already biased?)")
    new_hi = 0 if hi == 0 else (sub_pal * 4 + hi) & 0x0F
    new_lo = 0 if lo == 0 else (sub_pal * 4 + lo) & 0x0F
    return ((new_hi << 4) | new_lo) & 0xFF


def parse_2d_array(text, name):
    """Parse `const unsigned char NAME[DIM0][DIM1] = { {row0}, {row1}, ... };`.

    Returns list of bytearrays (one per row). Dimension tokens may be integer
    literals or macro names — we count parsed bytes rather than trusting them.
    """
    # Match the outer array header; dimensions can be macros (\w+) or literals.
    # re.DOTALL lets \s* span newlines between name and '['.
    pat = re.compile(
        r"const\s+unsigned\s+char\s+" + re.escape(name) +
        r"\s*\[\s*\w+\s*\]\s*\[\s*\w+\s*\]\s*=\s*\{",
        re.DOTALL,
    )
    m = pat.search(text)
    if not m:
        return None

    # Find the matching closing '};' by counting braces from the opening '{'.
    body_start = m.end() - 1  # points at the opening '{'
    depth = 0
    i = body_start
    while i < len(text):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                body_end = i
                break
        i += 1
    else:
        fail(f"{name}: unmatched brace — truncated file?")

    outer_body = text[body_start + 1:body_end]  # content between outer { }

    # Extract each inner { ... } block (one per variant/row).
    rows = []
    for inner in re.finditer(r"\{([^{}]*)\}", outer_body):
        row_bytes = [
            int(tok.group(1), 16)
            for tok in re.finditer(r"0x([0-9A-Fa-f]{1,2})", inner.group(1))
        ]
        if row_bytes:
            rows.append(bytearray(row_bytes))

    if not rows:
        fail(f"{name}: no rows parsed from 2D array body")
    return rows


def assert_pixel_range(name, row_idx, data):
    for i, b in enumerate(data):
        hi = (b >> 4) & 0x0F
        lo = b & 0x0F
        if hi > 3 or lo > 3:
            fail(
                f"{name}[{row_idx}][{i}] = 0x{b:02X} has pixel > 3 "
                "(array already biased? refusing to re-bias)"
            )


def expand_row_to_x4(row):
    """Concatenate 4 sub-pal copies of row bytes: pal0||pal1||pal2||pal3."""
    out = bytearray()
    for s in range(4):
        out.extend(bias_byte(b, s) for b in row)
    return out


def emit_header(arrays_meta):
    """arrays_meta: list of (name, per_pal_bytes, n_rows)."""
    lines = [
        "/* Auto-generated by RoomRom/tools/expand_sprite_chr.py - do not edit. */",
        "#ifndef ROOMROM_EXPANDED_SPRITE_CHR_H",
        "#define ROOMROM_EXPANDED_SPRITE_CHR_H",
        "",
        "/* 4x pixel-biased sub-pal copies of source NES sprite item CHR arrays.",
        " * Each array row is layout: pal0_bytes || pal1_bytes || pal2_bytes || pal3_bytes.",
        " * Per-pal stride = original per-variant byte count.",
        " * Pixel bias applied per-nibble: out = (in == 0) ? 0 : (s*4 + in). */",
        "",
    ]
    for name, per_pal_bytes, n_rows in arrays_meta:
        ident = name.upper() + "_X4_BYTES"
        lines.append(f"#define {ident} {per_pal_bytes * 4}u")
        lines.append(
            f"extern const unsigned char {name}_x4[{n_rows}][{ident}];"
        )
        lines.append("")
    lines += ["#endif", ""]
    OUT_H.write_text("\n".join(lines), encoding="ascii", newline="\n")


def emit_source(expansions):
    """expansions: list of (name, n_rows, list_of_x4_bytearrays)."""
    lines = [
        "/* Auto-generated by RoomRom/tools/expand_sprite_chr.py - do not edit. */",
        '#include "expanded_sprite_chr.h"',
        "",
    ]
    for name, n_rows, rows_x4 in expansions:
        ident = name.upper() + "_X4_BYTES"
        lines.append(f"const unsigned char {name}_x4[{n_rows}][{ident}] = {{")
        for r, row in enumerate(rows_x4):
            lines.append(f"    {{ /* row {r} */")
            for i in range(0, len(row), 16):
                chunk = row[i:i + 16]
                lines.append("        " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
            lines.append("    },")
        lines.append("};")
        lines.append("")
    OUT_C.write_text("\n".join(lines), encoding="ascii", newline="\n")


def main():
    arrays_meta = []
    expansions = []

    for src_rel, name in SOURCES:
        path = ROOT / src_rel
        if not path.exists():
            fail(f"{src_rel}: not found")
        text = path.read_text(encoding="utf-8")
        rows = parse_2d_array(text, name)
        if rows is None:
            fail(f"{src_rel}: array '{name}' not found")

        # Validate pixel range before biasing.
        for idx, row in enumerate(rows):
            assert_pixel_range(name, idx, row)

        rows_x4 = [expand_row_to_x4(row) for row in rows]
        n_rows = len(rows)
        per_pal_bytes = len(rows[0])

        arrays_meta.append((name, per_pal_bytes, n_rows))
        expansions.append((name, n_rows, rows_x4))
        print(
            f"  {name}: {n_rows} variants x {per_pal_bytes} bytes "
            f"-> x4 = {per_pal_bytes * 4} bytes/variant"
        )

    emit_header(arrays_meta)
    emit_source(expansions)
    print(f"wrote {OUT_H}")
    print(f"wrote {OUT_C}")


if __name__ == "__main__":
    main()
