#!/usr/bin/env python3
"""Generate RoomRom item CHR C/H files from item_chr_manifest.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = ROOT / "RoomRom" / "data" / "item_chr_manifest.json"
DEFAULT_C = ROOT / "RoomRom" / "src" / "roomrom_item_chr.c"
DEFAULT_H = ROOT / "RoomRom" / "src" / "roomrom_item_chr.h"


def nes_tile_to_genesis(nes_tile: bytes) -> bytes:
    if len(nes_tile) != 16:
        raise ValueError("NES tile must be exactly 16 bytes")
    out = bytearray(32)
    for row in range(8):
        p0 = nes_tile[row]
        p1 = nes_tile[row + 8]
        for col in range(8):
            bit = 7 - col
            color = ((p0 >> bit) & 1) | (((p1 >> bit) & 1) << 1)
            byte_idx = row * 4 + col // 2
            if col & 1:
                out[byte_idx] |= color
            else:
                out[byte_idx] |= color << 4
    return bytes(out)


def hflip_genesis_tile(gen_tile: bytes) -> bytes:
    """Mirror a Genesis 4bpp tile horizontally. Layout: 8 rows x 4 bytes,
    each byte holds 2 pixels (high nibble = even col, low nibble = odd col).
    Mirrored row reverses pixel order — swap nibbles within each byte AND
    reverse byte order across the row."""
    if len(gen_tile) != 32:
        raise ValueError("Genesis tile must be exactly 32 bytes")
    out = bytearray(32)
    for row in range(8):
        for byte_idx in range(4):
            src = gen_tile[row * 4 + byte_idx]
            swapped = ((src & 0x0F) << 4) | ((src >> 4) & 0x0F)
            out[row * 4 + (3 - byte_idx)] = swapped
    return bytes(out)


def c_ident(name: str) -> str:
    return name.upper().replace("-", "_")


def parse_manifest(path: Path) -> Dict[str, object]:
    manifest = json.loads(path.read_text(encoding="ascii"))
    if manifest.get("schema_version") != 1:
        raise SystemExit(f"unsupported manifest schema: {path}")
    if manifest.get("source_policy") != "live_nes_chr_only":
        raise SystemExit("manifest must declare source_policy=live_nes_chr_only")
    if not manifest.get("item_defs"):
        raise SystemExit("manifest has no item_defs")
    if not manifest.get("variants"):
        raise SystemExit("manifest has no variants")
    return manifest


def tiles_per_input(item_def: Dict[str, object]) -> int:
    """Number of Genesis tiles produced per declared NES tile_id.
    `mirrored_*` draw_rules emit (raw, hflipped) per NES tile so SGDK
    SPRITE_SIZE(2,1) can render both halves of an @Mirrored cluster
    (NES Z1 right column = left column hflipped) without per-sprite
    flip attribute juggling."""
    rule = str(item_def.get("draw_rule", ""))
    if rule.startswith("mirrored_"):
        return 2
    return 1


def build_variant_bytes(item_defs: List[Dict[str, object]],
                        variant: Dict[str, object]) -> bytes:
    tiles = variant.get("tiles", {})
    if not isinstance(tiles, dict):
        raise SystemExit(f"variant {variant.get('rom_id')} has invalid tiles map")
    out = bytearray()
    for item_def in item_defs:
        rule = str(item_def.get("draw_rule", ""))
        bake_mirror = rule.startswith("mirrored_")
        for tile_id in item_def["tile_ids"]:
            tile_meta = tiles.get(tile_id)
            if tile_meta is None:
                raise SystemExit(f"variant {variant.get('rom_id')} missing tile {tile_id}")
            source = tile_meta.get("source")
            if source == "guessed_common_chr":
                raise SystemExit(f"tile {tile_id} still uses forbidden guessed_common_chr source")
            raw = bytes.fromhex(tile_meta["bytes"])
            if len(raw) != 16:
                raise SystemExit(f"tile {tile_id} in variant {variant.get('rom_id')} is not 16 bytes")
            gen = nes_tile_to_genesis(raw)
            out.extend(gen)
            if bake_mirror:
                out.extend(hflip_genesis_tile(gen))
    return bytes(out)


def write_header(path: Path, item_defs: List[Dict[str, object]],
                 variant_count: int, tile_count: int, byte_count: int) -> None:
    lines = [
        "/* Auto-generated by RoomRom/tools/gen_item_chr_blob.py - do not edit. */",
        "#ifndef ROOMROM_ITEM_CHR_H",
        "#define ROOMROM_ITEM_CHR_H",
        "",
        f"#define ROOMROM_ITEM_CHR_VARIANT_COUNT {variant_count}u",
        f"#define ROOMROM_ITEM_CHR_TILE_COUNT {tile_count}u",
        f"#define ROOMROM_ITEM_CHR_BYTES {byte_count}u",
        "",
    ]
    offset = 0
    for item_def in item_defs:
        name = c_ident(str(item_def["name"]))
        lines.append(f"#define ROOMROM_ITEM_TILE_{name} {offset}u")
        offset += len(item_def["tile_ids"]) * tiles_per_input(item_def)
    lines += [
        "",
        "extern const unsigned long roomrom_item_chr_size;",
        "extern const unsigned short roomrom_item_chr_byte_count;",
        "extern const unsigned char roomrom_item_chr",
        "    [ROOMROM_ITEM_CHR_VARIANT_COUNT][ROOMROM_ITEM_CHR_BYTES];",
        "",
        "#endif",
        "",
    ]
    path.write_text("\n".join(lines), encoding="ascii", newline="\n")


def write_source(path: Path, manifest_path: Path, variant_blobs: List[bytes],
                 variant_names: List[str]) -> None:
    lines = [
        "/* Auto-generated by RoomRom/tools/gen_item_chr_blob.py - do not edit. */",
        f"/* Source manifest: {manifest_path.as_posix()} */",
        '#include "roomrom_item_chr.h"',
        "",
        "const unsigned long roomrom_item_chr_size = ROOMROM_ITEM_CHR_BYTES;",
        "const unsigned short roomrom_item_chr_byte_count = ROOMROM_ITEM_CHR_BYTES;",
        "",
        "const unsigned char roomrom_item_chr",
        "    [ROOMROM_ITEM_CHR_VARIANT_COUNT][ROOMROM_ITEM_CHR_BYTES] = {",
    ]
    for variant_name, blob in zip(variant_names, variant_blobs):
        lines.append(f"    {{ /* {variant_name} */")
        for i in range(0, len(blob), 16):
            chunk = blob[i:i + 16]
            row = ", ".join(f"0x{b:02X}" for b in chunk)
            comma = "," if i + 16 < len(blob) else ""
            lines.append(f"        {row}{comma}")
        lines.append("    },")
    lines += [
        "};",
        "",
    ]
    path.write_text("\n".join(lines), encoding="ascii", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--out-c", default=str(DEFAULT_C))
    parser.add_argument("--out-h", default=str(DEFAULT_H))
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    manifest = parse_manifest(manifest_path)
    item_defs = manifest["item_defs"]
    variants = manifest["variants"]

    variant_blobs = [build_variant_bytes(item_defs, variant) for variant in variants]
    byte_count = len(variant_blobs[0])
    if byte_count == 0 or byte_count % 32 != 0:
        raise SystemExit("generated item CHR byte count is invalid")
    for variant, blob in zip(variants, variant_blobs):
        if len(blob) != byte_count:
            raise SystemExit(f"variant {variant.get('rom_id')} has inconsistent byte count")

    tile_count = byte_count // 32
    write_header(Path(args.out_h), item_defs, len(variants), tile_count, byte_count)
    write_source(
        Path(args.out_c),
        manifest_path,
        variant_blobs,
        [str(v.get("rom_id", "?")) for v in variants],
    )
    print(
        f"wrote {args.out_h} and {args.out_c} "
        f"({len(variants)} variant(s), {tile_count} tiles, {byte_count} bytes each)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
