#!/usr/bin/env python3
"""Generate RoomRom UW NT blob from one or more NES dungeon dump JSONs.

By default reads the original-ROM dump (RoomRom/out/nes_uw_warp_v2.json)
and the redux-ROM dump (RoomRom/out/nes_uw_warp_redux.json). Each
dungeon snapshot becomes one blob entry tagged with map_id (0 = original,
1 = redux). RoomRom looks up entries by (map_id, level, room_id).

Emits RoomRom/src/uw_room_blob.c containing:
  - g_uw_room_count
  - g_uw_room_index[][3]  : (map_id, level, room_id)
  - g_uw_room_nt[][22*32] : play-area nametable (NT rows 8..29)
  - g_uw_room_attr[][64]  : full attribute table $23C0..$23FF
  - g_uw_room_palette[][32] : NES PALRAM
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ORIG = ROOT / "RoomRom" / "out" / "nes_uw_warp_v2.json"
DEFAULT_REDUX = ROOT / "RoomRom" / "out" / "nes_uw_warp_redux.json"
OUT_C = ROOT / "RoomRom" / "src" / "uw_room_blob.c"

PLAY_NT_TOP = 8
PLAY_ROWS = 22
PLAY_COLS = 32


def load_dump(path: Path, map_id: int) -> list[dict]:
    """Return list of dungeon entries from one dump JSON, tagged with map_id."""
    if not path.exists():
        return []
    data = json.loads(path.read_text())
    rows = []
    for r in data.get("results", []):
        if r.get("cur_level", 0) == 0:
            continue
        if r.get("game_mode", 0) != 5:
            continue
        r["map_id"] = map_id
        rows.append(r)
    return rows


def emit_c(entries: list[dict], out_path: Path) -> None:
    lines: list[str] = []
    lines.append("/* Auto-generated by RoomRom/tools/gen_uw_blob.py - do not edit. */")
    lines.append("")
    lines.append("#include \"uw_room_blob.h\"")
    lines.append("")
    n = len(entries)
    lines.append(f"const unsigned short g_uw_room_count = {n}u;")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_index[{max(n,1)}][3] = {{")
    for e in entries:
        mid = e.get("map_id", 0)
        lvl = e["cur_level"]
        rid = e["room_id"]
        lines.append(f"    {{ {mid:#04x}, {lvl:#04x}, {rid:#04x} }},")
    if n == 0:
        lines.append("    { 0, 0, 0 }, /* placeholder */")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_nt[{max(n,1)}][{PLAY_ROWS * PLAY_COLS}] = {{")
    for e in entries:
        nt = e["nt"]
        lines.append("    {")
        for r in range(PLAY_ROWS):
            row = nt[PLAY_NT_TOP + r]
            byte_strs = ", ".join(f"{b:#04x}" for b in row)
            lines.append(f"        {byte_strs},")
        lines.append("    },")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_attr[{max(n,1)}][64] = {{")
    for e in entries:
        attr = e.get("attr") or ([0] * 64)
        if len(attr) < 64:
            attr = attr + [0] * (64 - len(attr))
        byte_strs = ", ".join(f"{b:#04x}" for b in attr[:64])
        lines.append(f"    {{ {byte_strs} }},")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_palette[{max(n,1)}][32] = {{")
    for e in entries:
        pal = e["palram"]
        byte_strs = ", ".join(f"{b:#04x}" for b in pal)
        lines.append(f"    {{ {byte_strs} }},")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines) + "\n")


def main(argv: list[str]) -> int:
    orig_path = Path(argv[1]) if len(argv) > 1 else DEFAULT_ORIG
    redux_path = Path(argv[2]) if len(argv) > 2 else DEFAULT_REDUX
    entries: list[dict] = []
    entries += load_dump(orig_path,  map_id=0)
    entries += load_dump(redux_path, map_id=1)
    print(f"Original entries from {orig_path}: "
          f"{sum(1 for e in entries if e['map_id'] == 0)}")
    print(f"Redux entries from {redux_path}: "
          f"{sum(1 for e in entries if e['map_id'] == 1)}")
    emit_c(entries, OUT_C)
    print(f"Wrote {OUT_C}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
