#!/usr/bin/env python3
"""Generate RoomRom UW NT blob from a NES dungeon dump JSON.

Reads RoomRom/out/nes_uw_warp_v2.json (or path passed as arg).
Emits RoomRom/src/uw_room_blob.c containing:
  - g_uw_room_count : number of captured (level, room) entries
  - g_uw_room_index[] : (level, room_id) pairs
  - g_uw_room_nt[][22*32] : play-area nametable (NT rows 8..29) per entry
  - g_uw_room_attr[][16] : attribute table bytes for play-area rows
  - g_uw_room_palette[][32] : NES palette ram per entry

Each NT byte is the NES tile index. RoomRom blits raw_tile + UW_VDP_TILE_BASE
to plane A row (HUD_ROWS + r), col c.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_JSON = ROOT / "RoomRom" / "out" / "nes_uw_warp_v2.json"
OUT_C = ROOT / "RoomRom" / "src" / "uw_room_blob.c"

PLAY_NT_TOP = 8
PLAY_ROWS = 22
PLAY_COLS = 32


def load_dump(path: Path) -> list[dict]:
    """Return list of {level, room_id, nt[30][32], palram[32]} entries that
    are dungeon (cur_level != 0) and in gameplay mode."""
    data = json.loads(path.read_text())
    rows = []
    for r in data.get("results", []):
        if r.get("cur_level", 0) == 0:
            continue
        if r.get("game_mode", 0) != 5:
            continue
        rows.append(r)
    return rows


def emit_c(entries: list[dict], out_path: Path) -> None:
    lines: list[str] = []
    lines.append("/* Auto-generated by RoomRom/tools/gen_uw_blob.py - do not edit. */")
    lines.append("")
    lines.append("#include \"uw_room_blob.h\"")
    lines.append("")
    n = len(entries)
    lines.append(f"const unsigned short g_uw_room_count = {n}u;")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_index[{max(n,1)}][2] = {{")
    for e in entries:
        lvl = e["cur_level"]
        rid = e["room_id"]
        lines.append(f"    {{ {lvl:#04x}, {rid:#04x} }},")
    if n == 0:
        lines.append("    { 0, 0 }, /* placeholder */")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_nt[{max(n,1)}][{PLAY_ROWS * PLAY_COLS}] = {{")
    for e in entries:
        nt = e["nt"]
        lines.append("    {")
        for r in range(PLAY_ROWS):
            row = nt[PLAY_NT_TOP + r]
            byte_strs = ", ".join(f"{b:#04x}" for b in row)
            lines.append(f"        {byte_strs},")
        lines.append("    },")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_attr[{max(n,1)}][64] = {{")
    for e in entries:
        attr = e.get("attr") or ([0] * 64)
        if len(attr) < 64:
            attr = attr + [0] * (64 - len(attr))
        byte_strs = ", ".join(f"{b:#04x}" for b in attr[:64])
        lines.append(f"    {{ {byte_strs} }},")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_palette[{max(n,1)}][32] = {{")
    for e in entries:
        pal = e["palram"]
        byte_strs = ", ".join(f"{b:#04x}" for b in pal)
        lines.append(f"    {{ {byte_strs} }},")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines) + "\n")


def main(argv: list[str]) -> int:
    json_path = DEFAULT_JSON
    if len(argv) > 1:
        json_path = Path(argv[1])
    if not json_path.exists():
        print(f"input not found: {json_path}", file=sys.stderr)
        return 1
    entries = load_dump(json_path)
    print(f"Loaded {len(entries)} dungeon room entries from {json_path}")
    emit_c(entries, OUT_C)
    print(f"Wrote {OUT_C}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
