#!/usr/bin/env python3
"""Run the Phase 5.3 UW west-exit movement probe in BizHawk.

The probe resolves RoomRom static symbols from the built ELF, generates a
one-shot Lua probe, launches BizHawk against Debug.md, and fails unless
Link can leave L1 room $73 through the open west doorway into room $72.
"""
from __future__ import annotations

import argparse
import ctypes
import json
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "build" / "probes" / "ph5" / "t53"
LUA_PATH = OUT_DIR / "uw_west_exit.generated.lua"
JSON_PATH = OUT_DIR / "uw_west_exit.json"
ROM_PATH = ROOT / "RoomRom" / "out" / "Debug.md"
ELF_PATH = ROOT / "RoomRom" / "out" / "rom.out"


SYMBOLS = (
    "s_link_y",
    "s_link_x",
    "s_room_id",
    "s_scene",
    "s_mode",
    "s_link_dir",
    "s_link_grid_offset",
    "s_link_pos_frac",
    "s_link_subx",
    "s_link_suby",
    "s_scroll_state",
    "s_uw_walkable",
    "s_uw_tile_walkable",
)


def short_path(path: Path) -> str:
    """Return an 8.3 path when Windows provides one; otherwise the long path."""
    raw = str(path.resolve())
    if os.name != "nt":
        return raw
    buf = ctypes.create_unicode_buffer(32768)
    n = ctypes.windll.kernel32.GetShortPathNameW(raw, buf, len(buf))
    return buf.value if n else raw


def find_bizhawk() -> Path:
    env = os.environ.get("CODEX_BIZHAWK_ROOT")
    candidates = []
    if env:
        candidates.append(Path(env) / "EmuHawk.exe")
    candidates.extend(
        [
            Path(r"C:\Users\Jake Diggity\Documents\GitHub\VDP rebirth tools and asms\BizHawk-2.11-win-x64\EmuHawk.exe"),
            Path(r"C:\BizHawk\EmuHawk.exe"),
            Path.home() / "BizHawk" / "EmuHawk.exe",
        ]
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError("EmuHawk.exe not found; set CODEX_BIZHAWK_ROOT")


def nm_path() -> Path:
    candidates = [
        ROOT / "build" / "toolchain" / "sgdk_bin" / "bin" / "nm.exe",
        ROOT / "sgdk" / "bin" / "nm.exe",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError("SGDK nm.exe not found; run RoomRom/build.bat once")


def resolve_symbols() -> dict[str, int]:
    if not ELF_PATH.is_file():
        raise FileNotFoundError(f"missing {ELF_PATH}")
    result = subprocess.run(
        [str(nm_path()), "-n", str(ELF_PATH)],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    found: dict[str, int] = {}
    wanted = set(SYMBOLS)
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2] in wanted:
            vma = int(parts[0], 16)
            found[parts[2]] = vma - 0xE0FF0000
    missing = sorted(wanted - found.keys())
    if missing:
        raise RuntimeError(f"missing symbols in {ELF_PATH}: {', '.join(missing)}")
    return found


def lua_bool(value: bool) -> str:
    return "true" if value else "false"


def write_lua(symbols: dict[str, int], case_name: str, case_x: int | None) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    json_path = str(JSON_PATH.resolve()).replace("\\", "\\\\")
    case_x_lua = "nil" if case_x is None else str(case_x)
    lua = f"""-- Generated by RoomRom/tools/probe_uw_west_exit.py. Do not edit.
local OUT_JSON = "{json_path}"
local CASE_NAME = "{case_name}"
local CASE_X = {case_x_lua}
local RAM = "68K RAM"

local A = {{
  link_y = 0x{symbols["s_link_y"]:04X},
  link_x = 0x{symbols["s_link_x"]:04X},
  room_id = 0x{symbols["s_room_id"]:04X},
  scene = 0x{symbols["s_scene"]:04X},
  mode = 0x{symbols["s_mode"]:04X},
  link_dir = 0x{symbols["s_link_dir"]:04X},
  grid_offset = 0x{symbols["s_link_grid_offset"]:04X},
  pos_frac = 0x{symbols["s_link_pos_frac"]:04X},
  subx = 0x{symbols["s_link_subx"]:04X},
  suby = 0x{symbols["s_link_suby"]:04X},
  scroll_state = 0x{symbols["s_scroll_state"]:04X},
  walkable = 0x{symbols["s_uw_walkable"]:04X},
  tile_walkable = 0x{symbols["s_uw_tile_walkable"]:04X},
}}

local function r8(a) return memory.read_u8(a, RAM) or 0 end
local function r16s(a) return memory.read_s16_be(a, RAM) or 0 end
local function r32(a) return memory.read_u32_be(a, RAM) or 0 end
local function w8(a, v) memory.write_u8(a, v, RAM) end
local function w16(a, v) memory.write_s16_be(a, v, RAM) end
local function w32(a, v) memory.write_u32_be(a, v, RAM) end

local function adv(n, pad)
  for _ = 1, n do
    joypad.set(pad or {{}}, 1)
    emu.frameadvance()
  end
end

local function hold_left(n)
  local pad = {{ Left = true, ["P1 Left"] = true }}
  adv(n, pad)
  adv(8, {{}})
end

local function walkable_at(col, row)
  return r8(A.walkable + col * 11 + row)
end

local function tile_walkable_at(col, row)
  return r8(A.tile_walkable + col * 22 + row)
end

local function tile_mask()
  local out = {{}}
  for col = 0, 31 do
    for row = 0, 21 do
      out[#out + 1] = tile_walkable_at(col, row)
    end
  end
  return out
end

local function state(label)
  return {{
    label = label,
    frame = emu.framecount(),
    room = r8(A.room_id),
    scene = r32(A.scene),
    mode = r32(A.mode),
    x = r16s(A.link_x),
    y = r16s(A.link_y),
    scroll_state = r32(A.scroll_state),
    west_inner = walkable_at(1, 5),
    west_outer = walkable_at(0, 5),
    west_tile_0_10 = tile_walkable_at(0, 10),
    west_tile_1_10 = tile_walkable_at(1, 10),
    west_tile_2_10 = tile_walkable_at(2, 10),
    west_tile_3_10 = tile_walkable_at(3, 10),
  }}
end

local function encode(v)
  local t = type(v)
  if t == "number" then return tostring(v) end
  if t == "boolean" then return v and "true" or "false" end
  if t == "string" then return string.format("%q", v) end
  if t == "table" then
    local n = 0
    local array = true
    for k, _ in pairs(v) do
      n = n + 1
      if type(k) ~= "number" then array = false end
    end
    local parts = {{}}
    if array then
      for i = 1, n do parts[#parts + 1] = encode(v[i]) end
      return "[" .. table.concat(parts, ",") .. "]"
    end
    for k, value in pairs(v) do
      parts[#parts + 1] = string.format("%q:%s", tostring(k), encode(value))
    end
    return "{{" .. table.concat(parts, ",") .. "}}"
  end
  return "null"
end

local function force_room73(x, y)
  w8(A.room_id, 0x73)
  w32(A.scene, 1)
  w32(A.mode, 0)
  w16(A.link_x, x)
  w16(A.link_y, y)
  w32(A.link_dir, 0)
  w8(A.grid_offset, 0)
  w8(A.pos_frac, 0)
  w8(A.subx, 0)
  w8(A.suby, 0)
  adv(16, {{}})
end

local function run_case(name, x, y)
  force_room73(x, y)
  local before = state(name .. "_before")
  hold_left(230)
  local after = state(name .. "_after")
  return {{
    name = name,
    start_x = x,
    start_y = y,
    pass = after.room == 0x72 and after.scroll_state == 0,
    before = before,
    after = after,
  }}
end

adv(140, {{}})
local boot_default = state("boot_default")

local start_x = CASE_X or boot_default.x
local c = run_case(CASE_NAME, start_x, boot_default.y)

local payload = {{
  schema = "ph5_t53_uw_west_exit_v1",
  pass = c.pass,
  expected_room = 0x72,
  boot_default = boot_default,
  tile_mask = tile_mask(),
  cases = {{ c }},
  symbols = {{
    link_x = A.link_x,
    link_y = A.link_y,
    room_id = A.room_id,
    scroll_state = A.scroll_state,
    walkable = A.walkable,
    tile_walkable = A.tile_walkable,
  }},
}}

local f = assert(io.open(OUT_JSON, "w"))
f:write(encode(payload))
f:write("\\n")
f:close()
client.exit()
"""
    LUA_PATH.write_text(lua, encoding="utf-8")


def run_one_case(emu: Path, symbols: dict[str, int],
                 case_name: str, case_x: int | None, timeout: int) -> dict:
    write_lua(symbols, case_name, case_x)
    if JSON_PATH.exists():
        JSON_PATH.unlink()
    args = [f"--lua={short_path(LUA_PATH)}", short_path(ROM_PATH)]
    subprocess.run(args=[short_path(emu), *args], cwd=short_path(emu.parent), timeout=timeout, check=False)
    if not JSON_PATH.is_file():
        raise RuntimeError(f"probe did not write {JSON_PATH} for {case_name}")
    payload = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    return payload


def run_probe(timeout: int) -> int:
    if not ROM_PATH.is_file():
        raise FileNotFoundError(f"missing {ROM_PATH}; run RoomRom/build.bat")
    emu = find_bizhawk()
    symbols = resolve_symbols()
    case_specs: list[tuple[str, int | None]] = [
        ("default_boot_line", None),
        ("doorway_band", 32),
        ("left_approach_x40", 40),
        ("left_approach_x48", 48),
        ("left_approach_x56", 56),
    ]
    aggregate: dict | None = None
    cases: list[dict] = []
    for case_name, case_x in case_specs:
        payload = run_one_case(emu, symbols, case_name, case_x, timeout)
        if aggregate is None:
            aggregate = payload
        cases.extend(payload.get("cases", []))
    assert aggregate is not None
    aggregate["cases"] = cases
    aggregate["pass"] = all(c.get("pass") for c in cases
                            if c.get("name") != "default_boot_line")
    mask_ok, mask_diff = verify_room73_mask(aggregate.get("tile_mask", []))
    aggregate["room73_mask_pass"] = mask_ok
    aggregate["room73_mask_diff"] = mask_diff[:16]
    aggregate["pass"] = bool(aggregate["pass"] and mask_ok)
    JSON_PATH.write_text(json.dumps(aggregate, separators=(",", ":")) + "\n",
                         encoding="utf-8")
    print(json.dumps(aggregate, indent=2))
    return 0 if aggregate.get("pass") else 2


def expected_room73_mask() -> list[int]:
    sys.path.insert(0, str(ROOT / "tools" / "builder"))
    from extract_uw_collision import build_room_grid, load_manifest, parse_dungeons_c

    data = parse_dungeons_c(ROOT / "data" / "rooms" / "dungeons.c")
    tables, _sha = load_manifest(ROOT / "data" / "rooms" / "MANIFEST.json")
    block_off, _ = tables["LevelBlockUW1Q1"]
    uid = data[block_off + 0x180 + 0x73] & 0x3F
    grid = build_room_grid(data, tables, uid)
    attrs_a = data[block_off + 0x73]
    attrs_b = data[block_off + 128 + 0x73]
    door_types = {
        0: (attrs_b >> 2) & 7,  # east
        1: (attrs_b >> 5) & 7,  # west
        2: (attrs_a >> 2) & 7,  # south
        3: (attrs_a >> 5) & 7,  # north
    }
    open_patches = {
        0: ((28, 10), (29, 10), (28, 11), (29, 11)),
        1: ((2, 10), (3, 10), (2, 11), (3, 11)),
        2: ((15, 18), (16, 18), (15, 19), (16, 19)),
        3: ((15, 2), (16, 2), (15, 3), (16, 3)),
    }
    tile = [[0 for _row in range(22)] for _col in range(32)]
    for col in range(16):
        for row in range(11):
            walk = 1 if grid[col][row] == 0 else 0
            for dc in (0, 1):
                for dr in (0, 1):
                    tile[col * 2 + dc][row * 2 + dr] = walk
    for door_dir, points in open_patches.items():
        open_value = 1 if door_types[door_dir] == 0 else 0
        for col, row in points:
            tile[col][row] = open_value

    expected: list[int] = []
    for col in range(32):
        for row in range(22):
            expected.append(tile[col][row])
    return expected


def verify_room73_mask(actual: list[int]) -> tuple[bool, list[dict[str, int]]]:
    expected = expected_room73_mask()
    if len(actual) != len(expected):
        return False, [{"index": len(actual), "expected": len(expected), "actual": -1}]
    diffs = []
    for index, (a, e) in enumerate(zip(actual, expected)):
        if int(a) != int(e):
            col = index // 22
            row = index % 22
            diffs.append({"col": col, "row": row, "expected": e, "actual": int(a)})
    return not diffs, diffs


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--timeout", type=int, default=90)
    args = parser.parse_args(argv)
    return run_probe(args.timeout)


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
