;==============================================================================
; z_03.asm — auto-generated by transpile_6502.py
; Source: reference/aldonunez/Z_03.asm
; DO NOT EDIT — regenerate with: python tools/transpile_6502.py
;
; Register convention:
;   D0 = 6502 A  (accumulator)
;   D1 = scratch
;   D2 = 6502 X  (X index register)
;   D3 = 6502 Y  (Y index register)
;   D4,D5 = scratch (used by indirect addressing sequences)
;   D6 = scratch
;   D7 = 6502 SP shadow (NES stack pointer, $0100 area)
;   A4 = NES RAM base ($FF0000) — init by genesis_shell.asm
;   A5 = NES stack pointer ($FF0200 initially, grows downward)
;==============================================================================

; (fixed equates omitted — provided by z_07.asm in --all build)
;==============================================================================
; NES RAM variable offsets (used as (offset,A4) — A4=NES_RAM)
; Source: Variables.inc + CommonVars.inc
;==============================================================================
; (var equates omitted — provided by z_07.asm in --all build)
;==============================================================================
; Begin translated Z_03.asm code
;==============================================================================

; [skipped] .INCLUDE "Variables.inc"

; === .SEGMENT "BANK_03_00" ===


; Imports from program bank 07

; .IMPORT TurnOffAllVideo

; .EXPORT TransferLevelPatternBlocks

    even
LevelPatternBlockSrcAddrs:
    dc.b    (PatternBlockUWSP127)&$FF, (PatternBlockUWSP127>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP127)&$FF, (PatternBlockUWSP127>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP127)&$FF, (PatternBlockUWSP127>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP358)&$FF, (PatternBlockUWSP358>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP469)&$FF, (PatternBlockUWSP469>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP358)&$FF, (PatternBlockUWSP358>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP469)&$FF, (PatternBlockUWSP469>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP127)&$FF, (PatternBlockUWSP127>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP358)&$FF, (PatternBlockUWSP358>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP469)&$FF, (PatternBlockUWSP469>>8)&$FF   ; NES .ADDR (little-endian)

    even
BossPatternBlockSrcAddrs:
    dc.b    (PatternBlockUWSPBoss1257)&$FF, (PatternBlockUWSPBoss1257>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss1257)&$FF, (PatternBlockUWSPBoss1257>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss1257)&$FF, (PatternBlockUWSPBoss1257>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss3468)&$FF, (PatternBlockUWSPBoss3468>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss3468)&$FF, (PatternBlockUWSPBoss3468>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss1257)&$FF, (PatternBlockUWSPBoss1257>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss3468)&$FF, (PatternBlockUWSPBoss3468>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss1257)&$FF, (PatternBlockUWSPBoss1257>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss3468)&$FF, (PatternBlockUWSPBoss3468>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSPBoss9)&$FF, (PatternBlockUWSPBoss9>>8)&$FF   ; NES .ADDR (little-endian)

    even
PatternBlockSrcAddrsUW:
    dc.b    (PatternBlockUWBG)&$FF, (PatternBlockUWBG>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockUWSP)&$FF, (PatternBlockUWSP>>8)&$FF   ; NES .ADDR (little-endian)

    even
PatternBlockSrcAddrsOW:
    dc.b    (PatternBlockOWBG)&$FF, (PatternBlockOWBG>>8)&$FF   ; NES .ADDR (little-endian)
    dc.b    (PatternBlockOWSP)&$FF, (PatternBlockOWSP>>8)&$FF   ; NES .ADDR (little-endian)

    even
PatternBlockPpuAddrs:
    dc.w    $1700
    dc.w    $08E0

    even
PatternBlockPpuAddrsExtra:
    dc.w    $09E0
    dc.w    $0C00

    even
PatternBlockSizesOW:
    dc.w    $0820
    dc.w    $0720

    even
PatternBlockSizesUW:
    dc.w    $0820
    dc.w    $0100
    dc.w    $0220
    dc.w    $0400

    even
TransferLevelPatternBlocks:
    bsr     TurnOffAllVideo
    bsr     _ppu_read_2  ; PPU $2002 read → D0
    bsr     ResetPatternBlockIndex
    move.b  ($0010,A4),D0
    bne  TransferLevelPatternBlocksUW
    even
_L_z03_TransferLevelPatternBlocks_LoopBlockOW:
    bsr     FetchPatternBlockInfoOW
    bsr     TransferPatternBlock_Bank3
    move.b  ($051D,A4),D0
    cmpi.b  #$02,D0
    bne  _L_z03_TransferLevelPatternBlocks_LoopBlockOW
    even
ResetPatternBlockIndex:
    moveq   #0,D0
    move.b  D0,($051D,A4)
    rts

    even
TransferLevelPatternBlocksUW:
    bsr     FetchPatternBlockAddrUW
    bsr     FetchPatternBlockSizeUW
    move.b  ($051D,A4),D0
    cmpi.b  #$02,D0
    bne  TransferLevelPatternBlocksUW
    ; At this point, we've transferred two common blocks
    ; (BG and sprites). Now UW, transfer bosses and other
    ; specialized sprite patterns.
    ;
    bsr     FetchPatternBlockAddrUWSpecial
    bsr     FetchPatternBlockSizeUW
    bsr     FetchPatternBlockUWBoss
    bsr     FetchPatternBlockSizeUW
    jmp     ResetPatternBlockIndex

    even
FetchPatternBlockAddrUW:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockSrcAddrsUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (PatternBlockSrcAddrsUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    rts

; Returns:
; [$00:01]: source address
; [$03:02]: size
;
    even
FetchPatternBlockInfoOW:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockSrcAddrsOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    lea     (PatternBlockSizesOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0002,A4)
    addq.b  #1,D2
    lea     (PatternBlockSrcAddrsOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    lea     (PatternBlockSizesOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0003,A4)
    rts

    even
FetchPatternBlockAddrUWSpecial:
    move.b  ($0010,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (LevelPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (LevelPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    rts

    even
FetchPatternBlockUWBoss:
    move.b  ($0010,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (BossPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (BossPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    rts

    even
FetchPatternBlockSizeUW:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockSizesUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0002,A4)
    addq.b  #1,D2
    lea     (PatternBlockSizesUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0003,A4)
; Params:
; [$00:01]: source address
; [$03:02]: size
;
; Look up and transfer destination PPU address by PatternBlockIndex.
;
    even
TransferPatternBlock_Bank3:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockPpuAddrs).l,A0
    move.b  (A0,D2.W),D0
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    addq.b  #1,D2
    lea     (PatternBlockPpuAddrs).l,A0
    move.b  (A0,D2.W),D0
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    moveq   #0,D3
    even
_L_z03_TransferPatternBlock_Bank3_LoopCopy:
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    andi.w  #$00FF,D1         ; zero-extend lo byte
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    bsr     _ppu_write_7  ; PPU $2007 write, D0=val
    ; Increment source address.
    ;
    move.b  ($0000,A4),D0
    andi    #$EE,CCR  ; CLC: clear C+X
    move.b  #$01,D1
    addx.b  D1,D0   ; ADC #$01 (X flag = 6502 C)
    move.b  D0,($0000,A4)
    move.b  ($0001,A4),D0
    move.b  #$00,D1
    addx.b  D1,D0   ; ADC #$00 (X flag = 6502 C)
    move.b  D0,($0001,A4)
    ; Decrement count.
    ;
    move.b  ($0003,A4),D0
    ori     #$11,CCR  ; SEC: set C+X
    move.b  #$01,D1
    subx.b  D1,D0   ; SBC #$01
    move.b  D0,($0003,A4)
    move.b  ($0002,A4),D0
    move.b  #$00,D1
    subx.b  D1,D0   ; SBC #$00
    move.b  D0,($0002,A4)
    ; If count is not zero, go copy more.
    ;
    move.b  ($0002,A4),D0
    bne  _L_z03_TransferPatternBlock_Bank3_LoopCopy
    move.b  ($0003,A4),D0
    bne  _L_z03_TransferPatternBlock_Bank3_LoopCopy
    addq.b  #1,($051D,A4)
    rts

    even
PatternBlockUWBG:
; .INCBIN "dat/PatternBlockUWBG.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockOWBG:
; .INCBIN "dat/PatternBlockOWBG.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockOWSP:
; .INCBIN "dat/PatternBlockOWSP.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP358:
; .INCBIN "dat/PatternBlockUWSP358.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP469:
; .INCBIN "dat/PatternBlockUWSP469.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP:
; .INCBIN "dat/PatternBlockUWSP.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP127:
; .INCBIN "dat/PatternBlockUWSP127.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSPBoss1257:
; .INCBIN "dat/PatternBlockUWSPBoss1257.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSPBoss3468:
; .INCBIN "dat/PatternBlockUWSPBoss3468.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSPBoss9:
; .INCBIN "dat/PatternBlockUWSPBoss9.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr


; === .SEGMENT "BANK_03_ISR" ===



; Unknown block
    dc.b    $78, $D8, $A9, $00, $8D, $00, $20, $A2
    dc.b    $FF, $9A, $AD, $02, $20, $29, $80, $F0
    dc.b    $F9, $AD, $02, $20, $29, $80, $F0, $F9
    dc.b    $09, $FF, $8D, $00, $80, $8D, $00, $A0
    dc.b    $8D, $00, $C0, $8D, $00, $E0, $A9, $0F
    dc.b    $20, $98, $BF, $A9, $00, $8D, $00, $A0
    dc.b    $4A, $8D, $00, $A0, $4A, $8D, $00, $A0
    dc.b    $4A, $8D, $00, $A0, $4A, $8D, $00, $A0
    dc.b    $A9, $07, $20, $AC, $BF, $4C, $40, $E4
    dc.b    $8D, $00, $80, $4A, $8D, $00, $80, $4A
    dc.b    $8D, $00, $80, $4A, $8D, $00, $80, $4A
    dc.b    $8D, $00, $80, $60, $8D, $00, $E0, $4A
    dc.b    $8D, $00, $E0, $4A, $8D, $00, $E0, $4A
    dc.b    $8D, $00, $E0, $4A, $8D, $00, $E0, $60


; === .SEGMENT "BANK_03_VEC" ===



; Unknown block
    dc.b    $84, $E4, $50, $BF, $F0, $BF

