;==============================================================================
; z_03.asm — auto-generated by transpile_6502.py
; Source: reference/aldonunez/Z_03.asm
; DO NOT EDIT — regenerate with: python tools/transpile_6502.py
;
; Register convention:
;   D0 = 6502 A  (accumulator)
;   D1 = scratch
;   D2 = 6502 X  (X index register)
;   D3 = 6502 Y  (Y index register)
;   D4,D5 = scratch (used by indirect addressing sequences)
;   D6 = scratch
;   D7 = 6502 SP shadow (NES stack pointer, $0100 area)
;   A4 = NES RAM base ($FF0000) — init by genesis_shell.asm
;   A5 = NES stack pointer ($FF0200 initially, grows downward)
;==============================================================================

NES_RAM         equ $FF0000
NES_SRAM        equ $FF6000
NES_STACK_BASE  equ $FF0100

;==============================================================================
; NES RAM variable offsets (used as (offset,A4) — A4=NES_RAM)
; Source: Variables.inc + CommonVars.inc
;==============================================================================
GLEEOK_DIRCOUNTERH                      equ $0000  ; NES RAM offset
GLEEOK_DIRCOUNTERV                      equ $0001  ; NES RAM offset
GLEEOK_SPEEDX                           equ $0002  ; NES RAM offset
GLEEOK_SPEEDY                           equ $0003  ; NES RAM offset
GLEEOK_DIRCHANGECOUNTER                 equ $0004  ; NES RAM offset
GLEEOK_DELAY                            equ $0005  ; NES RAM offset
CurLevel                                equ $0010  ; NES RAM offset
IsUpdatingMode                          equ $0011  ; NES RAM offset
GameMode                                equ $0012  ; NES RAM offset
GameSubmode                             equ $0013  ; NES RAM offset
TileBufSelector                         equ $0014  ; NES RAM offset
FrameCounter                            equ $0015  ; NES RAM offset
CurSaveSlot                             equ $0016  ; NES RAM offset
Random                                  equ $0018  ; NES RAM offset
StunCycle                               equ $0026  ; NES RAM offset
DoorTimer                               equ $0027  ; NES RAM offset
ObjTimer                                equ $0028  ; NES RAM offset
FluteTimer                              equ $003C  ; NES RAM offset
ObjStunTimer                            equ $003D  ; NES RAM offset
ChaseLongTimer                          equ $004A  ; NES RAM offset
MonstersFromEdgesLongTimer              equ $004B  ; NES RAM offset
SwordBlockedLongTimer                   equ $004C  ; NES RAM offset
RedLeeverLongTimer                      equ $004D  ; NES RAM offset
EndingFlashLongTimer                    equ $004D  ; NES RAM offset
HelpDropCount                           equ $0050  ; NES RAM offset
HelpDropValue                           equ $0051  ; NES RAM offset
ProcessedNarrowObj                      equ $0052  ; NES RAM offset
DoorwayDir                              equ $0053  ; NES RAM offset
TriggeredDoorCmd                        equ $0054  ; NES RAM offset
TriggeredDoorDir                        equ $0055  ; NES RAM offset
Link_GoStraightWhenDiagInput            equ $0056  ; NES RAM offset
Link_GoStraight                         equ $0057  ; NES RAM offset
VScrollAddrHi                           equ $0058  ; NES RAM offset
EmptyMonsterSlot                        equ $0059  ; NES RAM offset
UndergroundExitType                     equ $005A  ; NES RAM offset
TargetMode                              equ $005B  ; NES RAM offset
SwitchNameTablesReq                     equ $005C  ; NES RAM offset
CurScanRoomId                           equ $005D  ; NES RAM offset
SubmenuScrollProgress                   equ $005E  ; NES RAM offset
OddBaseNameTableOverride                equ $005F  ; NES RAM offset
ChaseOtherTarget                        equ $0060  ; NES RAM offset
ChaseTargetX                            equ $0061  ; NES RAM offset
ChaseTargetY                            equ $0062  ; NES RAM offset
World_IsFillingHearts                   equ $0063  ; NES RAM offset
LadderSlot                              equ $0064  ; NES RAM offset
UndergroundEntranceTile                 equ $0065  ; NES RAM offset
SongScriptPtrLo                         equ $0066  ; NES RAM offset
SongScriptPtrHi                         equ $0067  ; NES RAM offset
EffectCounter                           equ $0069  ; NES RAM offset
CurNoteLowPeriodSq0                     equ $006A  ; NES RAM offset
CurNoteLowPeriodSq1                     equ $006B  ; NES RAM offset
SongPhraseIndex                         equ $006C  ; NES RAM offset
CustomEnvelopeOffsetTune1               equ $006D  ; NES RAM offset
NoteLengthTune1                         equ $006E  ; NES RAM offset
NoteCounterTune1                        equ $006F  ; NES RAM offset
ObjX                                    equ $0070  ; NES RAM offset
ObjY                                    equ $0084  ; NES RAM offset
ObjDir                                  equ $0098  ; NES RAM offset
ObjRoomItemId                           equ $0098  ; NES RAM offset
RoomItemId                              equ $00AB  ; NES RAM offset
ObjState                                equ $00AC  ; NES RAM offset
Item_ObjItemId                          equ $00AC  ; NES RAM offset
ObjShoveDir                             equ $00C0  ; NES RAM offset
ObjShoveDistance                        equ $00D3  ; NES RAM offset
Paused                                  equ $00E0  ; NES RAM offset
MenuState                               equ $00E1  ; NES RAM offset
VScrollAddrLo                           equ $00E2  ; NES RAM offset
IsSprite0CheckActive                    equ $00E3  ; NES RAM offset
DeathTurns                              equ $00E5  ; NES RAM offset
VScrollStartFrame                       equ $00E6  ; NES RAM offset
CurColumn                               equ $00E8  ; NES RAM offset
CurRow                                  equ $00E9  ; NES RAM offset
WhirlwindPrevRoomId                     equ $00EA  ; NES RAM offset
RoomId                                  equ $00EB  ; NES RAM offset
NextRoomId                              equ $00EC  ; NES RAM offset
PrevRow                                 equ $00ED  ; NES RAM offset
CurOpenedDoors                          equ $00EE  ; NES RAM offset
_Unknown_F3                             equ $00F3  ; NES RAM offset
InitializedGame                         equ $00F4  ; NES RAM offset
TransferredCommonPatterns               equ $00F5  ; NES RAM offset
TransferredDemoPatterns                 equ $00F6  ; NES RAM offset
ReturnToBank4                           equ $00F7  ; NES RAM offset
ButtonsPressed                          equ $00F8  ; NES RAM offset
ButtonsDown                             equ $00FA  ; NES RAM offset
CurVScroll                              equ $00FC  ; NES RAM offset
CurHScroll                              equ $00FD  ; NES RAM offset
CurPpuMask_2001                         equ $00FE  ; NES RAM offset
CurPpuControl_2000                      equ $00FF  ; NES RAM offset
PositiveGridCellSize                    equ $010E  ; NES RAM offset
NegativeGridCellSize                    equ $010F  ; NES RAM offset
Sprites                                 equ $0200  ; NES RAM offset
DynTileBufLen                           equ $0301  ; NES RAM offset
DynTileBuf                              equ $0302  ; NES RAM offset
OpenDoorwayMask                         equ $033F  ; NES RAM offset
CurObjIndex                             equ $0340  ; NES RAM offset
RollingSpriteIndex                      equ $0341  ; NES RAM offset
FirstSpriteIndex                        equ $0342  ; NES RAM offset
LeftSpriteOffset                        equ $0343  ; NES RAM offset
RightSpriteOffset                       equ $0344  ; NES RAM offset
RoomBoundLeft                           equ $0346  ; NES RAM offset
RoomBoundRight                          equ $0347  ; NES RAM offset
RoomBoundUp                             equ $0348  ; NES RAM offset
RoomBoundDown                           equ $0349  ; NES RAM offset
ObjectFirstUnwalkableTile               equ $034A  ; NES RAM offset
ShotCollidesWithLink                    equ $034B  ; NES RAM offset
ActiveMonsterShots                      equ $034C  ; NES RAM offset
RoomAllDead                             equ $034D  ; NES RAM offset
RoomObjCount                            equ $034E  ; NES RAM offset
ObjType                                 equ $034F  ; NES RAM offset
RoomKillCount                           equ $034F  ; NES RAM offset
RoomObjTemplateType                     equ $035F  ; NES RAM offset
ObjMovingLimit                          equ $0380  ; NES RAM offset
ObjAngleFrac                            equ $0380  ; NES RAM offset
Shot_ObjBounceDir                       equ $0380  ; NES RAM offset
Moldorm_ObjOldDir                       equ $0380  ; NES RAM offset
Gohma_ObjShootTimer                     equ $0380  ; NES RAM offset
Gleook_HeadInfo2                        equ $0381  ; NES RAM offset
Manhandla_SegmentJustDied               equ $0383  ; NES RAM offset
Manhandla_BounceDir                     equ $0385  ; NES RAM offset
ObjGridOffset                           equ $0394  ; NES RAM offset
ObjRemDistance                          equ $0394  ; NES RAM offset
ObjAngleWhole                           equ $0394  ; NES RAM offset
Shot_ObjBounceDist                      equ $0394  ; NES RAM offset
RedWizzrobe_ObjFadeCounter              equ $0394  ; NES RAM offset
Gleeok_NeckXs3                          equ $0395  ; NES RAM offset
ObjPosFrac                              equ $03A8  ; NES RAM offset
Item_ObjItemLifetime                    equ $03A8  ; NES RAM offset
Gleook_HeadInfo3                        equ $03A9  ; NES RAM offset
ObjQSpeedFrac                           equ $03BC  ; NES RAM offset
Moldorm_ObjBounceDir                    equ $03BC  ; NES RAM offset
Gleeok_NeckYs3                          equ $03BD  ; NES RAM offset
ObjAnimCounter                          equ $03D0  ; NES RAM offset
ObjAnimFrame                            equ $03E4  ; NES RAM offset
ObjInputDir                             equ $03F8  ; NES RAM offset
ObjMetastate                            equ $0405  ; NES RAM offset
Item_ObjMonsterType                     equ $0412  ; NES RAM offset
StairsTargetY                           equ $0412  ; NES RAM offset
ObjWantsToShoot                         equ $0412  ; NES RAM offset
ObjPushTimer                            equ $0412  ; NES RAM offset
TileObjRoomId                           equ $0412  ; NES RAM offset
Fireball_ObjDirToTargetX                equ $0412  ; NES RAM offset
Flyer_ObjSpeedFrac                      equ $0412  ; NES RAM offset
Jumper_ObjSpeedWholeY                   equ $0412  ; NES RAM offset
Wallmaster_ObjStep                      equ $0412  ; NES RAM offset
PolsVoice_ObjSpeedWhole                 equ $0412  ; NES RAM offset
BlueWizzrobe_ObjTurnCounter             equ $0412  ; NES RAM offset
RedWizzrobe_ObjAnimCounter              equ $0412  ; NES RAM offset
Manhandla_ObjSpeedAccum                 equ $0412  ; NES RAM offset
Gohma_ObjDistTraveled                   equ $0412  ; NES RAM offset
TriforceGlowTimer                       equ $0412  ; NES RAM offset
PeaceCharDelayCounter                   equ $0412  ; NES RAM offset
TriforceGlowCycle                       equ $0413  ; NES RAM offset
Gleeok_ObjHeadInfo                      equ $0413  ; NES RAM offset
Gleeok_ObjHeadDirCounterH               equ $0413  ; NES RAM offset
PeaceCharIndex                          equ $0413  ; NES RAM offset
CaveFlags                               equ $0413  ; NES RAM offset
Gleeok_ObjHeadDirCounterV               equ $0414  ; NES RAM offset
ScrolledScreenCount                     equ $0415  ; NES RAM offset
Gleeok_ObjHeadSpeedX                    equ $0415  ; NES RAM offset
PersonTextSelector                      equ $0415  ; NES RAM offset
Gleeok_ObjHeadSpeedY                    equ $0416  ; NES RAM offset
TextboxCharIndex                        equ $0416  ; NES RAM offset
PersonTextIndex                         equ $0416  ; NES RAM offset
DemoLineAttrVramAddrLo                  equ $0417  ; NES RAM offset
Gleeok_ObjHeadDirChangeCounter          equ $0417  ; NES RAM offset
DemoLineAttrVramAddrHi                  equ $0418  ; NES RAM offset
Gleeok_ObjHeadDelay                     equ $0418  ; NES RAM offset
DemoLineIndex                           equ $0419  ; NES RAM offset
DemoTimer                               equ $041A  ; NES RAM offset
ScrolledLineCount                       equ $041B  ; NES RAM offset
DemoLineTileVramAddrLo                  equ $041C  ; NES RAM offset
DemoLineTileVramAddrHi                  equ $041D  ; NES RAM offset
ObjTurnRate                             equ $041F  ; NES RAM offset
Fireball_ObjQSpeedX                     equ $041F  ; NES RAM offset
Flyer_ObjSpeed                          equ $041F  ; NES RAM offset
Jumper_ObjSpeedFracY                    equ $041F  ; NES RAM offset
Wallmaster_ObjTilesCrossed              equ $041F  ; NES RAM offset
Digdogger_ObjSpeedFrac                  equ $041F  ; NES RAM offset
PolsVoice_ObjLastTile                   equ $041F  ; NES RAM offset
Wizzrobe_ObjLastTile                    equ $041F  ; NES RAM offset
Manhandla_ObjSpeedFrac                  equ $041F  ; NES RAM offset
Gohma_ObjMoveAccum                      equ $041F  ; NES RAM offset
InitializedWaterfallAnimation           equ $041F  ; NES RAM offset
CharBoardIndex                          equ $041F  ; NES RAM offset
Gleook_HeadInfo0                        equ $0420  ; NES RAM offset
TitleWaveYs                             equ $0420  ; NES RAM offset
InitializedNameField                    equ $0420  ; NES RAM offset
NameCharOffset                          equ $0421  ; NES RAM offset
NameInputCharBuf                        equ $0422  ; NES RAM offset
CaveItemIds                             equ $0422  ; NES RAM offset
StillHoldingButton                      equ $0426  ; NES RAM offset
HeldButton                              equ $0427  ; NES RAM offset
SubsequentButtonRepeat                  equ $0428  ; NES RAM offset
ButtonRepeatTimer                       equ $0429  ; NES RAM offset
ModeE_WrappedAroundBoardY               equ $042A  ; NES RAM offset
ObjRefId                                equ $042C  ; NES RAM offset
ObjCaptureTimer                         equ $042C  ; NES RAM offset
Flyer_ObjTurns                          equ $042C  ; NES RAM offset
Digdogger_ObjSpeedWhole                 equ $042C  ; NES RAM offset
Dodongo_ObjBloatedSubstate              equ $042C  ; NES RAM offset
PolsVoice_ObjTargetY                    equ $042C  ; NES RAM offset
Manhandla_ObjSpeedWhole                 equ $042C  ; NES RAM offset
Gohma_ObjNextOpenEyeCounter             equ $042C  ; NES RAM offset
Ganon_ObjPhase                          equ $042C  ; NES RAM offset
DemoPhase                               equ $042C  ; NES RAM offset
DemoSubphase                            equ $042D  ; NES RAM offset
Gleook_HeadInfo1                        equ $042D  ; NES RAM offset
DemoLineTextIndex                       equ $042E  ; NES RAM offset
CaveCurPriceIndex                       equ $042E  ; NES RAM offset
DemoItemRow                             equ $042F  ; NES RAM offset
CaveCurPriceOffset                      equ $042F  ; NES RAM offset
CavePrices                              equ $0430  ; NES RAM offset
Fireball_ObjDirToTargetY                equ $0437  ; NES RAM offset
Flyer_ObjDistTraveled                   equ $0437  ; NES RAM offset
Digdogger_ObjTargetSpeedFrac            equ $0437  ; NES RAM offset
Dodongo_ObjBombHits                     equ $0437  ; NES RAM offset
Manhandla_ObjPrevFrame                  equ $0437  ; NES RAM offset
DemoPhase0Subphase1Cycle                equ $0437  ; NES RAM offset
DemoPhase0Subphase1Timer                equ $0438  ; NES RAM offset
Gleeok_NeckXs0                          equ $0438  ; NES RAM offset
CaveChosenIndex                         equ $0438  ; NES RAM offset
Fireball_ObjQSpeedY                     equ $0444  ; NES RAM offset
Flyer_ObjFlyingState                    equ $0444  ; NES RAM offset
Jumper_ObjTargetY                       equ $0444  ; NES RAM offset
Digdogger_ObjTargetSpeedWhole           equ $0444  ; NES RAM offset
PolsVoice_ObjSpeedFrac                  equ $0444  ; NES RAM offset
Gohma_ObjEyeOpenTimer                   equ $0444  ; NES RAM offset
DemoItemIds                             equ $0444  ; NES RAM offset
Ganon_ScenePhase                        equ $0445  ; NES RAM offset
Gleeok_NeckYs0                          equ $0445  ; NES RAM offset
MoneyGameAmounts                        equ $0448  ; NES RAM offset
ObjShootTimer                           equ $0451  ; NES RAM offset
Fireball_ObjPosFracX                    equ $0451  ; NES RAM offset
Jumper_ObjReversalCount                 equ $0451  ; NES RAM offset
Manhandla_ObjFrameAccum                 equ $0451  ; NES RAM offset
Gohma_ObjGoStraight                     equ $0451  ; NES RAM offset
Gleeok_NeckXs1                          equ $0452  ; NES RAM offset
Fireball_ObjPosFracY                    equ $045E  ; NES RAM offset
Digdogger_ObjSpeedFlag                  equ $045E  ; NES RAM offset
Dodongo_ObjBloatedTimer                 equ $045E  ; NES RAM offset
Gohma_ObjSprints                        equ $045E  ; NES RAM offset
Patra_ObjManeuverIndex                  equ $045E  ; NES RAM offset
Gleeok_NeckYs1                          equ $045F  ; NES RAM offset
TextboxCharPtr                          equ $045F  ; NES RAM offset
PersonTextPtr                           equ $045F  ; NES RAM offset
Flyer_ObjOffsetX                        equ $046B  ; NES RAM offset
Digdogger_ObjIsChild                    equ $046B  ; NES RAM offset
Gohma_ObjEyeState                       equ $046B  ; NES RAM offset
Ganon_ObjAnimationFrame                 equ $046B  ; NES RAM offset
Gleeok_NeckXs2                          equ $046C  ; NES RAM offset
ObjTurnTimer                            equ $0478  ; NES RAM offset
Flyer_ObjOffsetY                        equ $0478  ; NES RAM offset
Digdogger_ObjCurPart                    equ $0478  ; NES RAM offset
Aquamentus_ObjFireballOffset            equ $0478  ; NES RAM offset
Manhandla_ObjFrame                      equ $0478  ; NES RAM offset
Gohma_ObjEyeAnimCounter                 equ $0478  ; NES RAM offset
Ganon_ObjCloudDist                      equ $0478  ; NES RAM offset
Gleeok_NeckYs2                          equ $0479  ; NES RAM offset
ObjHP                                   equ $0485  ; NES RAM offset
ObjUninitialized                        equ $0492  ; NES RAM offset
ObjCollidedTile                         equ $049E  ; NES RAM offset
ObjInvincibilityMask                    equ $04B2  ; NES RAM offset
ObjAttr                                 equ $04BF  ; NES RAM offset
PersonFireballsEnabled                  equ $04CC  ; NES RAM offset
LevelBlockAttrsByteF                    equ $04CD  ; NES RAM offset
ShutterTrigger                          equ $04CE  ; NES RAM offset
BlockPushComplete                       equ $04CF  ; NES RAM offset
FlyingMaxSpeedFrac                      equ $04D1  ; NES RAM offset
GleeokCurNeck                           equ $04D7  ; NES RAM offset
GleeokSignedRefSegmentDistance          equ $04D8  ; NES RAM offset
GleeokPrimarySegmentLimits              equ $04D9  ; NES RAM offset
GleeokSecondarySegmentLimits            equ $04DB  ; NES RAM offset
GleeokTertiarySegmentLimits             equ $04DD  ; NES RAM offset
StatusBarMapTrigger                     equ $04E5  ; NES RAM offset
GleeokAnimationTimer                    equ $04E6  ; NES RAM offset
Lamnola_Speed                           equ $04E6  ; NES RAM offset
GleeokBodyAnimationFrame                equ $04E7  ; NES RAM offset
Lamnola_Type                            equ $04E7  ; NES RAM offset
Statue_ObjFireballTimer                 equ $04E8  ; NES RAM offset
ObjInvincibilityTimer                   equ $04F0  ; NES RAM offset
LeftAlignHalfWidthObj                   equ $0504  ; NES RAM offset
ItemTypeToLift                          equ $0505  ; NES RAM offset
ItemLiftTimer                           equ $0506  ; NES RAM offset
ChildDigdoggerCount                     equ $0507  ; NES RAM offset
SummonedWhirlwind                       equ $0508  ; NES RAM offset
TriforceFanfareActive                   equ $0509  ; NES RAM offset
CreditsRow                              equ $050A  ; NES RAM offset
CreditsTileOffset                       equ $050B  ; NES RAM offset
CreditsVramPage                         equ $050C  ; NES RAM offset
CreditsVramLine                         equ $050D  ; NES RAM offset
CreditsLineIndex                        equ $050E  ; NES RAM offset
LamnolaViableDirMask                    equ $050F  ; NES RAM offset
ActiveRedLeeverCount                    equ $0510  ; NES RAM offset
Gleeok_WrithingCounter                  equ $0510  ; NES RAM offset
GleeokDeadNeckMask                      equ $0511  ; NES RAM offset
LinkParalyzed                           equ $0512  ; NES RAM offset
UsedCandle                              equ $0513  ; NES RAM offset
ZoraActive                              equ $0514  ; NES RAM offset
ActiveBoulders                          equ $0515  ; NES RAM offset
SecretColorCycle                        equ $051A  ; NES RAM offset
UsedFlute                               equ $051B  ; NES RAM offset
FadeCycle                               equ $051C  ; NES RAM offset
PatternBlockIndex                       equ $051D  ; NES RAM offset
BrighteningRoom                         equ $051E  ; NES RAM offset
CandleState                             equ $051F  ; NES RAM offset
PrevOpenedDoors                         equ $0521  ; NES RAM offset
WhirlwindTeleportingState               equ $0522  ; NES RAM offset
TeleportingLevelIndex                   equ $0523  ; NES RAM offset
SpawnCycle                              equ $0524  ; NES RAM offset
CurEdgeSpawnCell                        equ $0525  ; NES RAM offset
CaveSourceRoomId                        equ $0526  ; NES RAM offset
CellarSourceRoomId                      equ $0527  ; NES RAM offset
SkippedDemo                             equ $0528  ; NES RAM offset
WorldKillCycle                          equ $052A  ; NES RAM offset
RoomTileObjType                         equ $052B  ; NES RAM offset
RoomTileObjX                            equ $052C  ; NES RAM offset
RoomTileObjY                            equ $052D  ; NES RAM offset
SwordBlocked                            equ $052E  ; NES RAM offset
MazeStep                                equ $052F  ; NES RAM offset
PlayAreaAttrs                           equ $0530  ; NES RAM offset
LevelKillCounts                         equ $0560  ; NES RAM offset
CurNoteLowPeriodTrg                     equ $05F0  ; NES RAM offset
SampleCounter                           equ $05F2  ; NES RAM offset
SeaSfxCounter                           equ $05F3  ; NES RAM offset
NoteLengthTableBase                     equ $05F4  ; NES RAM offset
FirstNoteIndexSongNoise                 equ $05F5  ; NES RAM offset
BackgroundSample                        equ $05F6  ; NES RAM offset
SongRequest                             equ $0600  ; NES RAM offset
SampleRequest                           equ $0601  ; NES RAM offset
Tune1Request                            equ $0602  ; NES RAM offset
EffectRequest                           equ $0603  ; NES RAM offset
Tune0Request                            equ $0604  ; NES RAM offset
Tune0                                   equ $0605  ; NES RAM offset
Effect                                  equ $0606  ; NES RAM offset
Tune1                                   equ $0607  ; NES RAM offset
Sample                                  equ $0608  ; NES RAM offset
Song                                    equ $0609  ; NES RAM offset
NoteOffsetSongSq1                       equ $060A  ; NES RAM offset
NoteOffsetSongSq0                       equ $060B  ; NES RAM offset
NoteOffsetSongTrg                       equ $060C  ; NES RAM offset
NoteOffsetSongNoise                     equ $060D  ; NES RAM offset
TunePtr0                                equ $060E  ; NES RAM offset
NoteLengthSongSq0                       equ $060F  ; NES RAM offset
NoteLengthSongSq1                       equ $0610  ; NES RAM offset
NoteCounterSongSq1                      equ $0611  ; NES RAM offset
CustomEnvelopeOffsetSongSq1             equ $0612  ; NES RAM offset
NoteCounterSongSq0                      equ $0613  ; NES RAM offset
CustomEnvelopeOffsetSongSq0             equ $0614  ; NES RAM offset
NoteLengthSongTrg                       equ $0615  ; NES RAM offset
NoteCounterSongTrg                      equ $0616  ; NES RAM offset
NoteCounterSongNoise                    equ $0617  ; NES RAM offset
TunePtr1                                equ $0618  ; NES RAM offset
SongEnvelopeSelector                    equ $0619  ; NES RAM offset
SongVibrationCounterSq1                 equ $061B  ; NES RAM offset
SongVibrationCounterSq0                 equ $061C  ; NES RAM offset
SongVibrationCounterTrg                 equ $061D  ; NES RAM offset
SongRepetitionsTrg                      equ $061E  ; NES RAM offset
SongRepeatStartOffset                   equ $061F  ; NES RAM offset
CurRoomHistoryIndex                     equ $0620  ; NES RAM offset
RoomHistory                             equ $0621  ; NES RAM offset
WorldKillCount                          equ $0627  ; NES RAM offset
QuestNumbers                            equ $062D  ; NES RAM offset
DeathCounts                             equ $0630  ; NES RAM offset
IsSaveSlotActive                        equ $0633  ; NES RAM offset
IsRegisterSaveFileOptionEnabled         equ $0636  ; NES RAM offset
IsEliminateSaveFileOptionEnabled        equ $0637  ; NES RAM offset
Names                                   equ $0638  ; NES RAM offset
SaveSlotHearts                          equ $0650  ; NES RAM offset
SelectedItemSlot                        equ $0656  ; NES RAM offset
Items                                   equ $0657  ; NES RAM offset
InvBombs                                equ $0658  ; NES RAM offset
InvArrow                                equ $0659  ; NES RAM offset
Bow                                     equ $065A  ; NES RAM offset
InvCandle                               equ $065B  ; NES RAM offset
InvFood                                 equ $065D  ; NES RAM offset
Potion                                  equ $065E  ; NES RAM offset
InvRaft                                 equ $0660  ; NES RAM offset
InvBook                                 equ $0661  ; NES RAM offset
InvRing                                 equ $0662  ; NES RAM offset
InvLadder                               equ $0663  ; NES RAM offset
InvMagicKey                             equ $0664  ; NES RAM offset
InvBracelet                             equ $0665  ; NES RAM offset
InvLetter                               equ $0666  ; NES RAM offset
InvCompass                              equ $0667  ; NES RAM offset
InvMap                                  equ $0668  ; NES RAM offset
InvCompass9                             equ $0669  ; NES RAM offset
InvMap9                                 equ $066A  ; NES RAM offset
InvClock                                equ $066C  ; NES RAM offset
InvRupees                               equ $066D  ; NES RAM offset
InvKeys                                 equ $066E  ; NES RAM offset
HeartValues                             equ $066F  ; NES RAM offset
HeartPartial                            equ $0670  ; NES RAM offset
InvTriforce                             equ $0671  ; NES RAM offset
LastBossDefeated                        equ $0672  ; NES RAM offset
InvBoomerang                            equ $0674  ; NES RAM offset
InvMagicBoomerang                       equ $0675  ; NES RAM offset
InvMagicShield                          equ $0676  ; NES RAM offset
MaxBombs                                equ $067C  ; NES RAM offset
RupeesToAdd                             equ $067D  ; NES RAM offset
RupeesToSubtract                        equ $067E  ; NES RAM offset
WorldFlags                              equ $067F  ; NES RAM offset
PpuControl_2000                         equ $2000  ; NES I/O
PpuMask_2001                            equ $2001  ; NES I/O
PpuStatus_2002                          equ $2002  ; NES I/O
OamAddr_2003                            equ $2003  ; NES I/O
OamData_2004                            equ $2004  ; NES I/O
PpuScroll_2005                          equ $2005  ; NES I/O
PpuAddr_2006                            equ $2006  ; NES I/O
PpuData_2007                            equ $2007  ; NES I/O
Sq0Duty_4000                            equ $4000  ; NES I/O
Sq0Sweep_4001                           equ $4001  ; NES I/O
Sq0Timer_4002                           equ $4002  ; NES I/O
Sq0Length_4003                          equ $4003  ; NES I/O
Sq1Duty_4004                            equ $4004  ; NES I/O
Sq1Sweep_4005                           equ $4005  ; NES I/O
Sq1Timer_4006                           equ $4006  ; NES I/O
Sq1Length_4007                          equ $4007  ; NES I/O
TrgLinear_4008                          equ $4008  ; NES I/O
TrgTimer_400A                           equ $400A  ; NES I/O
TrgLength_400B                          equ $400B  ; NES I/O
NoiseVolume_400C                        equ $400C  ; NES I/O
NoisePeriod_400E                        equ $400E  ; NES I/O
NoiseLength_400F                        equ $400F  ; NES I/O
DmcFreq_4010                            equ $4010  ; NES I/O
DmcCounter_4011                         equ $4011  ; NES I/O
DmcAddress_4012                         equ $4012  ; NES I/O
DmcLength_4013                          equ $4013  ; NES I/O
SpriteDma_4014                          equ $4014  ; NES I/O
ApuStatus_4015                          equ $4015  ; NES I/O
Ctrl1_4016                              equ $4016  ; NES I/O
Ctrl2_FrameCtr_4017                     equ $4017  ; NES I/O
SaveRamBegin                            equ $6001  ; NES SRAM
SaveFileAName0                          equ $6002  ; NES SRAM
SaveFileAName1                          equ $600A  ; NES SRAM
SaveFileAName2                          equ $6012  ; NES SRAM
SaveFileAItems0                         equ $601A  ; NES SRAM
SaveFileAItems1                         equ $6042  ; NES SRAM
SaveFileAItems2                         equ $606A  ; NES SRAM
SaveFileAWorldFlags0                    equ $6092  ; NES SRAM
SaveFileAWorldFlags1                    equ $6212  ; NES SRAM
SaveFileAWorldFlags2                    equ $6392  ; NES SRAM
SaveFileASlotActive0                    equ $6512  ; NES SRAM
SaveFileASlotActive1                    equ $6513  ; NES SRAM
SaveFileASlotActive2                    equ $6514  ; NES SRAM
SaveFileADeathCount0                    equ $6515  ; NES SRAM
SaveFileADeathCount1                    equ $6516  ; NES SRAM
SaveFileADeathCount2                    equ $6517  ; NES SRAM
SaveFileAQuestNumber0                   equ $651B  ; NES SRAM
SaveFileAQuestNumber1                   equ $651C  ; NES SRAM
SaveFileAQuestNumber2                   equ $651D  ; NES SRAM
SaveFileOpenMarkers                     equ $651E  ; NES SRAM
SaveFileCloseMarkers                    equ $6521  ; NES SRAM
FileAChecksums                          equ $6524  ; NES SRAM
IsSaveFileBCommitted                    equ $652A  ; NES SRAM
PlayAreaTiles                           equ $6530  ; NES SRAM
LevelBlockAttrsA                        equ $687E  ; NES SRAM
LevelBlockAttrsB                        equ $68FE  ; NES SRAM
LevelBlockAttrsC                        equ $697E  ; NES SRAM
LevelBlockAttrsD                        equ $69FE  ; NES SRAM
LevelBlockAttrsE                        equ $6A7E  ; NES SRAM
LevelBlockAttrsF                        equ $6AFE  ; NES SRAM
LevelInfo_PalettesTransferBuf           equ $6B7E  ; NES SRAM
LevelInfo_FoeCounts                     equ $6BA2  ; NES SRAM
LevelInfo_StartY                        equ $6BA6  ; NES SRAM
LevelInfo_ShortcutOrItemPosArray        equ $6BA7  ; NES SRAM
LevelInfo_SubmenuMapRotation            equ $6BAB  ; NES SRAM
LevelInfo_StatusBarMapXOffset           equ $6BAC  ; NES SRAM
LevelInfo_StartRoomId                   equ $6BAD  ; NES SRAM
LevelInfo_TriforceRoomId                equ $6BAE  ; NES SRAM
LevelInfo_WorldFlagsAddr                equ $6BAF  ; NES SRAM
LevelInfo_LevelNumber                   equ $6BB1  ; NES SRAM
LevelInfo_CellarRoomIdArray             equ $6BB2  ; NES SRAM
LevelInfo_BossRoomId                    equ $6BBC  ; NES SRAM
LevelInfo_SubmenuMapMask                equ $6BBD  ; NES SRAM
LevelInfo_StatusBarMapTransferBuf       equ $6BCD  ; NES SRAM
LevelInfo_PaletteCycles                 equ $6BFA  ; NES SRAM
LevelInfo_DeathPaletteSeries            equ $6C5A  ; NES SRAM
SaveRamEnd                              equ $7FFF  ; NES SRAM
;==============================================================================
; Begin translated Z_03.asm code
;==============================================================================

; [skipped] .INCLUDE "Variables.inc"

; === .SEGMENT "BANK_03_00" ===


; Imports from program bank 07

; .IMPORT TurnOffAllVideo

; .EXPORT TransferLevelPatternBlocks

    even
LevelPatternBlockSrcAddrs:
    dc.l    PatternBlockUWSP127   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP127   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP127   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP358   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP469   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP358   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP469   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP127   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP358   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP469   ; NES addr vector (32-bit for M68K)

    even
BossPatternBlockSrcAddrs:
    dc.l    PatternBlockUWSPBoss1257   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss1257   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss1257   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss3468   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss3468   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss1257   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss3468   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss1257   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss3468   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSPBoss9   ; NES addr vector (32-bit for M68K)

    even
PatternBlockSrcAddrsUW:
    dc.l    PatternBlockUWBG   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockUWSP   ; NES addr vector (32-bit for M68K)

    even
PatternBlockSrcAddrsOW:
    dc.l    PatternBlockOWBG   ; NES addr vector (32-bit for M68K)
    dc.l    PatternBlockOWSP   ; NES addr vector (32-bit for M68K)

    even
PatternBlockPpuAddrs:
; [unknown directive] .DBYT $1700
; [unknown directive] .DBYT $08E0

    even
PatternBlockPpuAddrsExtra:
; [unknown directive] .DBYT $09E0
; [unknown directive] .DBYT $0C00

    even
PatternBlockSizesOW:
; [unknown directive] .DBYT $0820
; [unknown directive] .DBYT $0720

    even
PatternBlockSizesUW:
; [unknown directive] .DBYT $0820
; [unknown directive] .DBYT $0100
; [unknown directive] .DBYT $0220
; [unknown directive] .DBYT $0400

    even
TransferLevelPatternBlocks:
    bsr     TurnOffAllVideo
    bsr     _ppu_read_2  ; PPU $2002 read → D0
    bsr     ResetPatternBlockIndex
    move.b  ($0010,A4),D0
    bne  TransferLevelPatternBlocksUW
    even
_L_z03_TransferLevelPatternBlocks_LoopBlockOW:
    bsr     FetchPatternBlockInfoOW
    bsr     TransferPatternBlock_Bank3
    move.b  ($051D,A4),D0
    cmpi.b  #$02,D0
    bne  _L_z03_TransferLevelPatternBlocks_LoopBlockOW
    even
ResetPatternBlockIndex:
    moveq   #0,D0
    move.b  D0,($051D,A4)
    rts

    even
TransferLevelPatternBlocksUW:
    bsr     FetchPatternBlockAddrUW
    bsr     FetchPatternBlockSizeUW
    move.b  ($051D,A4),D0
    cmpi.b  #$02,D0
    bne  TransferLevelPatternBlocksUW
    ; At this point, we've transferred two common blocks
    ; (BG and sprites). Now UW, transfer bosses and other
    ; specialized sprite patterns.
    ;
    bsr     FetchPatternBlockAddrUWSpecial
    bsr     FetchPatternBlockSizeUW
    bsr     FetchPatternBlockUWBoss
    bsr     FetchPatternBlockSizeUW
    jmp     ResetPatternBlockIndex

    even
FetchPatternBlockAddrUW:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockSrcAddrsUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (PatternBlockSrcAddrsUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    rts

; Returns:
; [$00:01]: source address
; [$03:02]: size
;
    even
FetchPatternBlockInfoOW:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockSrcAddrsOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    lea     (PatternBlockSizesOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0002,A4)
    addq.b  #1,D2
    lea     (PatternBlockSrcAddrsOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    lea     (PatternBlockSizesOW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0003,A4)
    rts

    even
FetchPatternBlockAddrUWSpecial:
    move.b  ($0010,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (LevelPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (LevelPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    rts

    even
FetchPatternBlockUWBoss:
    move.b  ($0010,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (BossPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (BossPatternBlockSrcAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    rts

    even
FetchPatternBlockSizeUW:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockSizesUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0002,A4)
    addq.b  #1,D2
    lea     (PatternBlockSizesUW).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0003,A4)
; Params:
; [$00:01]: source address
; [$03:02]: size
;
; Look up and transfer destination PPU address by PatternBlockIndex.
;
    even
TransferPatternBlock_Bank3:
    move.b  ($051D,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (PatternBlockPpuAddrs).l,A0
    move.b  (A0,D2.W),D0
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    addq.b  #1,D2
    lea     (PatternBlockPpuAddrs).l,A0
    move.b  (A0,D2.W),D0
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    moveq   #0,D3
    even
_L_z03_TransferPatternBlock_Bank3_LoopCopy:
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    bsr     _ppu_write_7  ; PPU $2007 write, D0=val
    ; Increment source address.
    ;
    move.b  ($0000,A4),D0
    andi.b  #$EE,CCR  ; CLC: clear C+X
    move.b  #$01,D1
    addx.b  D1,D0   ; ADC #$01 (X flag = 6502 C)
    move.b  D0,($0000,A4)
    move.b  ($0001,A4),D0
    move.b  #$00,D1
    addx.b  D1,D0   ; ADC #$00 (X flag = 6502 C)
    move.b  D0,($0001,A4)
    ; Decrement count.
    ;
    move.b  ($0003,A4),D0
    ori.b   #$11,CCR  ; SEC: set C+X
    move.b  #$01,D1
    subx.b  D1,D0   ; SBC #$01
    move.b  D0,($0003,A4)
    move.b  ($0002,A4),D0
    move.b  #$00,D1
    subx.b  D1,D0   ; SBC #$00
    move.b  D0,($0002,A4)
    ; If count is not zero, go copy more.
    ;
    move.b  ($0002,A4),D0
    bne  _L_z03_TransferPatternBlock_Bank3_LoopCopy
    move.b  ($0003,A4),D0
    bne  _L_z03_TransferPatternBlock_Bank3_LoopCopy
    addq.b  #1,($051D,A4)
    rts

    even
PatternBlockUWBG:
; .INCBIN "dat/PatternBlockUWBG.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockOWBG:
; .INCBIN "dat/PatternBlockOWBG.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockOWSP:
; .INCBIN "dat/PatternBlockOWSP.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP358:
; .INCBIN "dat/PatternBlockUWSP358.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP469:
; .INCBIN "dat/PatternBlockUWSP469.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP:
; .INCBIN "dat/PatternBlockUWSP.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSP127:
; .INCBIN "dat/PatternBlockUWSP127.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSPBoss1257:
; .INCBIN "dat/PatternBlockUWSPBoss1257.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSPBoss3468:
; .INCBIN "dat/PatternBlockUWSPBoss3468.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
PatternBlockUWSPBoss9:
; .INCBIN "dat/PatternBlockUWSPBoss9.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr


; === .SEGMENT "BANK_03_ISR" ===



; Unknown block
    dc.b    $78, $D8, $A9, $00, $8D, $00, $20, $A2
    dc.b    $FF, $9A, $AD, $02, $20, $29, $80, $F0
    dc.b    $F9, $AD, $02, $20, $29, $80, $F0, $F9
    dc.b    $09, $FF, $8D, $00, $80, $8D, $00, $A0
    dc.b    $8D, $00, $C0, $8D, $00, $E0, $A9, $0F
    dc.b    $20, $98, $BF, $A9, $00, $8D, $00, $A0
    dc.b    $4A, $8D, $00, $A0, $4A, $8D, $00, $A0
    dc.b    $4A, $8D, $00, $A0, $4A, $8D, $00, $A0
    dc.b    $A9, $07, $20, $AC, $BF, $4C, $40, $E4
    dc.b    $8D, $00, $80, $4A, $8D, $00, $80, $4A
    dc.b    $8D, $00, $80, $4A, $8D, $00, $80, $4A
    dc.b    $8D, $00, $80, $60, $8D, $00, $E0, $4A
    dc.b    $8D, $00, $E0, $4A, $8D, $00, $E0, $4A
    dc.b    $8D, $00, $E0, $4A, $8D, $00, $E0, $60


; === .SEGMENT "BANK_03_VEC" ===



; Unknown block
    dc.b    $84, $E4, $50, $BF, $F0, $BF


;==============================================================================
; Import stubs (T2: defined locally so the file assembles standalone)
;==============================================================================
    even
TurnOffAllVideo:
    rts

