;==============================================================================
; z_06.asm — auto-generated by transpile_6502.py
; Source: reference/aldonunez/Z_06.asm
; DO NOT EDIT — regenerate with: python tools/transpile_6502.py
;
; Register convention:
;   D0 = 6502 A  (accumulator)
;   D1 = scratch
;   D2 = 6502 X  (X index register)
;   D3 = 6502 Y  (Y index register)
;   D4,D5 = scratch (used by indirect addressing sequences)
;   D6 = scratch
;   D7 = 6502 SP shadow (NES stack pointer, $0100 area)
;   A4 = NES RAM base ($FF0000) — init by genesis_shell.asm
;   A5 = NES stack pointer ($FF0200 initially, grows downward)
;==============================================================================

NES_RAM         equ $FF0000
NES_SRAM        equ $FF6000
NES_STACK_BASE  equ $FF0100

;==============================================================================
; NES RAM variable offsets (used as (offset,A4) — A4=NES_RAM)
; Source: Variables.inc + CommonVars.inc
;==============================================================================
GLEEOK_DIRCOUNTERH                      equ $0000  ; NES RAM offset
GLEEOK_DIRCOUNTERV                      equ $0001  ; NES RAM offset
GLEEOK_SPEEDX                           equ $0002  ; NES RAM offset
GLEEOK_SPEEDY                           equ $0003  ; NES RAM offset
GLEEOK_DIRCHANGECOUNTER                 equ $0004  ; NES RAM offset
GLEEOK_DELAY                            equ $0005  ; NES RAM offset
CurLevel                                equ $0010  ; NES RAM offset
IsUpdatingMode                          equ $0011  ; NES RAM offset
GameMode                                equ $0012  ; NES RAM offset
GameSubmode                             equ $0013  ; NES RAM offset
TileBufSelector                         equ $0014  ; NES RAM offset
FrameCounter                            equ $0015  ; NES RAM offset
CurSaveSlot                             equ $0016  ; NES RAM offset
Random                                  equ $0018  ; NES RAM offset
StunCycle                               equ $0026  ; NES RAM offset
DoorTimer                               equ $0027  ; NES RAM offset
ObjTimer                                equ $0028  ; NES RAM offset
FluteTimer                              equ $003C  ; NES RAM offset
ObjStunTimer                            equ $003D  ; NES RAM offset
ChaseLongTimer                          equ $004A  ; NES RAM offset
MonstersFromEdgesLongTimer              equ $004B  ; NES RAM offset
SwordBlockedLongTimer                   equ $004C  ; NES RAM offset
RedLeeverLongTimer                      equ $004D  ; NES RAM offset
EndingFlashLongTimer                    equ $004D  ; NES RAM offset
HelpDropCount                           equ $0050  ; NES RAM offset
HelpDropValue                           equ $0051  ; NES RAM offset
ProcessedNarrowObj                      equ $0052  ; NES RAM offset
DoorwayDir                              equ $0053  ; NES RAM offset
TriggeredDoorCmd                        equ $0054  ; NES RAM offset
TriggeredDoorDir                        equ $0055  ; NES RAM offset
Link_GoStraightWhenDiagInput            equ $0056  ; NES RAM offset
Link_GoStraight                         equ $0057  ; NES RAM offset
VScrollAddrHi                           equ $0058  ; NES RAM offset
EmptyMonsterSlot                        equ $0059  ; NES RAM offset
UndergroundExitType                     equ $005A  ; NES RAM offset
TargetMode                              equ $005B  ; NES RAM offset
SwitchNameTablesReq                     equ $005C  ; NES RAM offset
CurScanRoomId                           equ $005D  ; NES RAM offset
SubmenuScrollProgress                   equ $005E  ; NES RAM offset
OddBaseNameTableOverride                equ $005F  ; NES RAM offset
ChaseOtherTarget                        equ $0060  ; NES RAM offset
ChaseTargetX                            equ $0061  ; NES RAM offset
ChaseTargetY                            equ $0062  ; NES RAM offset
World_IsFillingHearts                   equ $0063  ; NES RAM offset
LadderSlot                              equ $0064  ; NES RAM offset
UndergroundEntranceTile                 equ $0065  ; NES RAM offset
SongScriptPtrLo                         equ $0066  ; NES RAM offset
SongScriptPtrHi                         equ $0067  ; NES RAM offset
EffectCounter                           equ $0069  ; NES RAM offset
CurNoteLowPeriodSq0                     equ $006A  ; NES RAM offset
CurNoteLowPeriodSq1                     equ $006B  ; NES RAM offset
SongPhraseIndex                         equ $006C  ; NES RAM offset
CustomEnvelopeOffsetTune1               equ $006D  ; NES RAM offset
NoteLengthTune1                         equ $006E  ; NES RAM offset
NoteCounterTune1                        equ $006F  ; NES RAM offset
ObjX                                    equ $0070  ; NES RAM offset
ObjY                                    equ $0084  ; NES RAM offset
ObjDir                                  equ $0098  ; NES RAM offset
ObjRoomItemId                           equ $0098  ; NES RAM offset
RoomItemId                              equ $00AB  ; NES RAM offset
ObjState                                equ $00AC  ; NES RAM offset
Item_ObjItemId                          equ $00AC  ; NES RAM offset
ObjShoveDir                             equ $00C0  ; NES RAM offset
ObjShoveDistance                        equ $00D3  ; NES RAM offset
Paused                                  equ $00E0  ; NES RAM offset
MenuState                               equ $00E1  ; NES RAM offset
VScrollAddrLo                           equ $00E2  ; NES RAM offset
IsSprite0CheckActive                    equ $00E3  ; NES RAM offset
DeathTurns                              equ $00E5  ; NES RAM offset
VScrollStartFrame                       equ $00E6  ; NES RAM offset
CurColumn                               equ $00E8  ; NES RAM offset
CurRow                                  equ $00E9  ; NES RAM offset
WhirlwindPrevRoomId                     equ $00EA  ; NES RAM offset
RoomId                                  equ $00EB  ; NES RAM offset
NextRoomId                              equ $00EC  ; NES RAM offset
PrevRow                                 equ $00ED  ; NES RAM offset
CurOpenedDoors                          equ $00EE  ; NES RAM offset
_Unknown_F3                             equ $00F3  ; NES RAM offset
InitializedGame                         equ $00F4  ; NES RAM offset
TransferredCommonPatterns               equ $00F5  ; NES RAM offset
TransferredDemoPatterns                 equ $00F6  ; NES RAM offset
ReturnToBank4                           equ $00F7  ; NES RAM offset
ButtonsPressed                          equ $00F8  ; NES RAM offset
ButtonsDown                             equ $00FA  ; NES RAM offset
CurVScroll                              equ $00FC  ; NES RAM offset
CurHScroll                              equ $00FD  ; NES RAM offset
CurPpuMask_2001                         equ $00FE  ; NES RAM offset
CurPpuControl_2000                      equ $00FF  ; NES RAM offset
PositiveGridCellSize                    equ $010E  ; NES RAM offset
NegativeGridCellSize                    equ $010F  ; NES RAM offset
Sprites                                 equ $0200  ; NES RAM offset
DynTileBufLen                           equ $0301  ; NES RAM offset
DynTileBuf                              equ $0302  ; NES RAM offset
OpenDoorwayMask                         equ $033F  ; NES RAM offset
CurObjIndex                             equ $0340  ; NES RAM offset
RollingSpriteIndex                      equ $0341  ; NES RAM offset
FirstSpriteIndex                        equ $0342  ; NES RAM offset
LeftSpriteOffset                        equ $0343  ; NES RAM offset
RightSpriteOffset                       equ $0344  ; NES RAM offset
RoomBoundLeft                           equ $0346  ; NES RAM offset
RoomBoundRight                          equ $0347  ; NES RAM offset
RoomBoundUp                             equ $0348  ; NES RAM offset
RoomBoundDown                           equ $0349  ; NES RAM offset
ObjectFirstUnwalkableTile               equ $034A  ; NES RAM offset
ShotCollidesWithLink                    equ $034B  ; NES RAM offset
ActiveMonsterShots                      equ $034C  ; NES RAM offset
RoomAllDead                             equ $034D  ; NES RAM offset
RoomObjCount                            equ $034E  ; NES RAM offset
ObjType                                 equ $034F  ; NES RAM offset
RoomKillCount                           equ $034F  ; NES RAM offset
RoomObjTemplateType                     equ $035F  ; NES RAM offset
ObjMovingLimit                          equ $0380  ; NES RAM offset
ObjAngleFrac                            equ $0380  ; NES RAM offset
Shot_ObjBounceDir                       equ $0380  ; NES RAM offset
Moldorm_ObjOldDir                       equ $0380  ; NES RAM offset
Gohma_ObjShootTimer                     equ $0380  ; NES RAM offset
Gleook_HeadInfo2                        equ $0381  ; NES RAM offset
Manhandla_SegmentJustDied               equ $0383  ; NES RAM offset
Manhandla_BounceDir                     equ $0385  ; NES RAM offset
ObjGridOffset                           equ $0394  ; NES RAM offset
ObjRemDistance                          equ $0394  ; NES RAM offset
ObjAngleWhole                           equ $0394  ; NES RAM offset
Shot_ObjBounceDist                      equ $0394  ; NES RAM offset
RedWizzrobe_ObjFadeCounter              equ $0394  ; NES RAM offset
Gleeok_NeckXs3                          equ $0395  ; NES RAM offset
ObjPosFrac                              equ $03A8  ; NES RAM offset
Item_ObjItemLifetime                    equ $03A8  ; NES RAM offset
Gleook_HeadInfo3                        equ $03A9  ; NES RAM offset
ObjQSpeedFrac                           equ $03BC  ; NES RAM offset
Moldorm_ObjBounceDir                    equ $03BC  ; NES RAM offset
Gleeok_NeckYs3                          equ $03BD  ; NES RAM offset
ObjAnimCounter                          equ $03D0  ; NES RAM offset
ObjAnimFrame                            equ $03E4  ; NES RAM offset
ObjInputDir                             equ $03F8  ; NES RAM offset
ObjMetastate                            equ $0405  ; NES RAM offset
Item_ObjMonsterType                     equ $0412  ; NES RAM offset
StairsTargetY                           equ $0412  ; NES RAM offset
ObjWantsToShoot                         equ $0412  ; NES RAM offset
ObjPushTimer                            equ $0412  ; NES RAM offset
TileObjRoomId                           equ $0412  ; NES RAM offset
Fireball_ObjDirToTargetX                equ $0412  ; NES RAM offset
Flyer_ObjSpeedFrac                      equ $0412  ; NES RAM offset
Jumper_ObjSpeedWholeY                   equ $0412  ; NES RAM offset
Wallmaster_ObjStep                      equ $0412  ; NES RAM offset
PolsVoice_ObjSpeedWhole                 equ $0412  ; NES RAM offset
BlueWizzrobe_ObjTurnCounter             equ $0412  ; NES RAM offset
RedWizzrobe_ObjAnimCounter              equ $0412  ; NES RAM offset
Manhandla_ObjSpeedAccum                 equ $0412  ; NES RAM offset
Gohma_ObjDistTraveled                   equ $0412  ; NES RAM offset
TriforceGlowTimer                       equ $0412  ; NES RAM offset
PeaceCharDelayCounter                   equ $0412  ; NES RAM offset
TriforceGlowCycle                       equ $0413  ; NES RAM offset
Gleeok_ObjHeadInfo                      equ $0413  ; NES RAM offset
Gleeok_ObjHeadDirCounterH               equ $0413  ; NES RAM offset
PeaceCharIndex                          equ $0413  ; NES RAM offset
CaveFlags                               equ $0413  ; NES RAM offset
Gleeok_ObjHeadDirCounterV               equ $0414  ; NES RAM offset
ScrolledScreenCount                     equ $0415  ; NES RAM offset
Gleeok_ObjHeadSpeedX                    equ $0415  ; NES RAM offset
PersonTextSelector                      equ $0415  ; NES RAM offset
Gleeok_ObjHeadSpeedY                    equ $0416  ; NES RAM offset
TextboxCharIndex                        equ $0416  ; NES RAM offset
PersonTextIndex                         equ $0416  ; NES RAM offset
DemoLineAttrVramAddrLo                  equ $0417  ; NES RAM offset
Gleeok_ObjHeadDirChangeCounter          equ $0417  ; NES RAM offset
DemoLineAttrVramAddrHi                  equ $0418  ; NES RAM offset
Gleeok_ObjHeadDelay                     equ $0418  ; NES RAM offset
DemoLineIndex                           equ $0419  ; NES RAM offset
DemoTimer                               equ $041A  ; NES RAM offset
ScrolledLineCount                       equ $041B  ; NES RAM offset
DemoLineTileVramAddrLo                  equ $041C  ; NES RAM offset
DemoLineTileVramAddrHi                  equ $041D  ; NES RAM offset
ObjTurnRate                             equ $041F  ; NES RAM offset
Fireball_ObjQSpeedX                     equ $041F  ; NES RAM offset
Flyer_ObjSpeed                          equ $041F  ; NES RAM offset
Jumper_ObjSpeedFracY                    equ $041F  ; NES RAM offset
Wallmaster_ObjTilesCrossed              equ $041F  ; NES RAM offset
Digdogger_ObjSpeedFrac                  equ $041F  ; NES RAM offset
PolsVoice_ObjLastTile                   equ $041F  ; NES RAM offset
Wizzrobe_ObjLastTile                    equ $041F  ; NES RAM offset
Manhandla_ObjSpeedFrac                  equ $041F  ; NES RAM offset
Gohma_ObjMoveAccum                      equ $041F  ; NES RAM offset
InitializedWaterfallAnimation           equ $041F  ; NES RAM offset
CharBoardIndex                          equ $041F  ; NES RAM offset
Gleook_HeadInfo0                        equ $0420  ; NES RAM offset
TitleWaveYs                             equ $0420  ; NES RAM offset
InitializedNameField                    equ $0420  ; NES RAM offset
NameCharOffset                          equ $0421  ; NES RAM offset
NameInputCharBuf                        equ $0422  ; NES RAM offset
CaveItemIds                             equ $0422  ; NES RAM offset
StillHoldingButton                      equ $0426  ; NES RAM offset
HeldButton                              equ $0427  ; NES RAM offset
SubsequentButtonRepeat                  equ $0428  ; NES RAM offset
ButtonRepeatTimer                       equ $0429  ; NES RAM offset
ModeE_WrappedAroundBoardY               equ $042A  ; NES RAM offset
ObjRefId                                equ $042C  ; NES RAM offset
ObjCaptureTimer                         equ $042C  ; NES RAM offset
Flyer_ObjTurns                          equ $042C  ; NES RAM offset
Digdogger_ObjSpeedWhole                 equ $042C  ; NES RAM offset
Dodongo_ObjBloatedSubstate              equ $042C  ; NES RAM offset
PolsVoice_ObjTargetY                    equ $042C  ; NES RAM offset
Manhandla_ObjSpeedWhole                 equ $042C  ; NES RAM offset
Gohma_ObjNextOpenEyeCounter             equ $042C  ; NES RAM offset
Ganon_ObjPhase                          equ $042C  ; NES RAM offset
DemoPhase                               equ $042C  ; NES RAM offset
DemoSubphase                            equ $042D  ; NES RAM offset
Gleook_HeadInfo1                        equ $042D  ; NES RAM offset
DemoLineTextIndex                       equ $042E  ; NES RAM offset
CaveCurPriceIndex                       equ $042E  ; NES RAM offset
DemoItemRow                             equ $042F  ; NES RAM offset
CaveCurPriceOffset                      equ $042F  ; NES RAM offset
CavePrices                              equ $0430  ; NES RAM offset
Fireball_ObjDirToTargetY                equ $0437  ; NES RAM offset
Flyer_ObjDistTraveled                   equ $0437  ; NES RAM offset
Digdogger_ObjTargetSpeedFrac            equ $0437  ; NES RAM offset
Dodongo_ObjBombHits                     equ $0437  ; NES RAM offset
Manhandla_ObjPrevFrame                  equ $0437  ; NES RAM offset
DemoPhase0Subphase1Cycle                equ $0437  ; NES RAM offset
DemoPhase0Subphase1Timer                equ $0438  ; NES RAM offset
Gleeok_NeckXs0                          equ $0438  ; NES RAM offset
CaveChosenIndex                         equ $0438  ; NES RAM offset
Fireball_ObjQSpeedY                     equ $0444  ; NES RAM offset
Flyer_ObjFlyingState                    equ $0444  ; NES RAM offset
Jumper_ObjTargetY                       equ $0444  ; NES RAM offset
Digdogger_ObjTargetSpeedWhole           equ $0444  ; NES RAM offset
PolsVoice_ObjSpeedFrac                  equ $0444  ; NES RAM offset
Gohma_ObjEyeOpenTimer                   equ $0444  ; NES RAM offset
DemoItemIds                             equ $0444  ; NES RAM offset
Ganon_ScenePhase                        equ $0445  ; NES RAM offset
Gleeok_NeckYs0                          equ $0445  ; NES RAM offset
MoneyGameAmounts                        equ $0448  ; NES RAM offset
ObjShootTimer                           equ $0451  ; NES RAM offset
Fireball_ObjPosFracX                    equ $0451  ; NES RAM offset
Jumper_ObjReversalCount                 equ $0451  ; NES RAM offset
Manhandla_ObjFrameAccum                 equ $0451  ; NES RAM offset
Gohma_ObjGoStraight                     equ $0451  ; NES RAM offset
Gleeok_NeckXs1                          equ $0452  ; NES RAM offset
Fireball_ObjPosFracY                    equ $045E  ; NES RAM offset
Digdogger_ObjSpeedFlag                  equ $045E  ; NES RAM offset
Dodongo_ObjBloatedTimer                 equ $045E  ; NES RAM offset
Gohma_ObjSprints                        equ $045E  ; NES RAM offset
Patra_ObjManeuverIndex                  equ $045E  ; NES RAM offset
Gleeok_NeckYs1                          equ $045F  ; NES RAM offset
TextboxCharPtr                          equ $045F  ; NES RAM offset
PersonTextPtr                           equ $045F  ; NES RAM offset
Flyer_ObjOffsetX                        equ $046B  ; NES RAM offset
Digdogger_ObjIsChild                    equ $046B  ; NES RAM offset
Gohma_ObjEyeState                       equ $046B  ; NES RAM offset
Ganon_ObjAnimationFrame                 equ $046B  ; NES RAM offset
Gleeok_NeckXs2                          equ $046C  ; NES RAM offset
ObjTurnTimer                            equ $0478  ; NES RAM offset
Flyer_ObjOffsetY                        equ $0478  ; NES RAM offset
Digdogger_ObjCurPart                    equ $0478  ; NES RAM offset
Aquamentus_ObjFireballOffset            equ $0478  ; NES RAM offset
Manhandla_ObjFrame                      equ $0478  ; NES RAM offset
Gohma_ObjEyeAnimCounter                 equ $0478  ; NES RAM offset
Ganon_ObjCloudDist                      equ $0478  ; NES RAM offset
Gleeok_NeckYs2                          equ $0479  ; NES RAM offset
ObjHP                                   equ $0485  ; NES RAM offset
ObjUninitialized                        equ $0492  ; NES RAM offset
ObjCollidedTile                         equ $049E  ; NES RAM offset
ObjInvincibilityMask                    equ $04B2  ; NES RAM offset
ObjAttr                                 equ $04BF  ; NES RAM offset
PersonFireballsEnabled                  equ $04CC  ; NES RAM offset
LevelBlockAttrsByteF                    equ $04CD  ; NES RAM offset
ShutterTrigger                          equ $04CE  ; NES RAM offset
BlockPushComplete                       equ $04CF  ; NES RAM offset
FlyingMaxSpeedFrac                      equ $04D1  ; NES RAM offset
GleeokCurNeck                           equ $04D7  ; NES RAM offset
GleeokSignedRefSegmentDistance          equ $04D8  ; NES RAM offset
GleeokPrimarySegmentLimits              equ $04D9  ; NES RAM offset
GleeokSecondarySegmentLimits            equ $04DB  ; NES RAM offset
GleeokTertiarySegmentLimits             equ $04DD  ; NES RAM offset
StatusBarMapTrigger                     equ $04E5  ; NES RAM offset
GleeokAnimationTimer                    equ $04E6  ; NES RAM offset
Lamnola_Speed                           equ $04E6  ; NES RAM offset
GleeokBodyAnimationFrame                equ $04E7  ; NES RAM offset
Lamnola_Type                            equ $04E7  ; NES RAM offset
Statue_ObjFireballTimer                 equ $04E8  ; NES RAM offset
ObjInvincibilityTimer                   equ $04F0  ; NES RAM offset
LeftAlignHalfWidthObj                   equ $0504  ; NES RAM offset
ItemTypeToLift                          equ $0505  ; NES RAM offset
ItemLiftTimer                           equ $0506  ; NES RAM offset
ChildDigdoggerCount                     equ $0507  ; NES RAM offset
SummonedWhirlwind                       equ $0508  ; NES RAM offset
TriforceFanfareActive                   equ $0509  ; NES RAM offset
CreditsRow                              equ $050A  ; NES RAM offset
CreditsTileOffset                       equ $050B  ; NES RAM offset
CreditsVramPage                         equ $050C  ; NES RAM offset
CreditsVramLine                         equ $050D  ; NES RAM offset
CreditsLineIndex                        equ $050E  ; NES RAM offset
LamnolaViableDirMask                    equ $050F  ; NES RAM offset
ActiveRedLeeverCount                    equ $0510  ; NES RAM offset
Gleeok_WrithingCounter                  equ $0510  ; NES RAM offset
GleeokDeadNeckMask                      equ $0511  ; NES RAM offset
LinkParalyzed                           equ $0512  ; NES RAM offset
UsedCandle                              equ $0513  ; NES RAM offset
ZoraActive                              equ $0514  ; NES RAM offset
ActiveBoulders                          equ $0515  ; NES RAM offset
SecretColorCycle                        equ $051A  ; NES RAM offset
UsedFlute                               equ $051B  ; NES RAM offset
FadeCycle                               equ $051C  ; NES RAM offset
PatternBlockIndex                       equ $051D  ; NES RAM offset
BrighteningRoom                         equ $051E  ; NES RAM offset
CandleState                             equ $051F  ; NES RAM offset
PrevOpenedDoors                         equ $0521  ; NES RAM offset
WhirlwindTeleportingState               equ $0522  ; NES RAM offset
TeleportingLevelIndex                   equ $0523  ; NES RAM offset
SpawnCycle                              equ $0524  ; NES RAM offset
CurEdgeSpawnCell                        equ $0525  ; NES RAM offset
CaveSourceRoomId                        equ $0526  ; NES RAM offset
CellarSourceRoomId                      equ $0527  ; NES RAM offset
SkippedDemo                             equ $0528  ; NES RAM offset
WorldKillCycle                          equ $052A  ; NES RAM offset
RoomTileObjType                         equ $052B  ; NES RAM offset
RoomTileObjX                            equ $052C  ; NES RAM offset
RoomTileObjY                            equ $052D  ; NES RAM offset
SwordBlocked                            equ $052E  ; NES RAM offset
MazeStep                                equ $052F  ; NES RAM offset
PlayAreaAttrs                           equ $0530  ; NES RAM offset
LevelKillCounts                         equ $0560  ; NES RAM offset
CurNoteLowPeriodTrg                     equ $05F0  ; NES RAM offset
SampleCounter                           equ $05F2  ; NES RAM offset
SeaSfxCounter                           equ $05F3  ; NES RAM offset
NoteLengthTableBase                     equ $05F4  ; NES RAM offset
FirstNoteIndexSongNoise                 equ $05F5  ; NES RAM offset
BackgroundSample                        equ $05F6  ; NES RAM offset
SongRequest                             equ $0600  ; NES RAM offset
SampleRequest                           equ $0601  ; NES RAM offset
Tune1Request                            equ $0602  ; NES RAM offset
EffectRequest                           equ $0603  ; NES RAM offset
Tune0Request                            equ $0604  ; NES RAM offset
Tune0                                   equ $0605  ; NES RAM offset
Effect                                  equ $0606  ; NES RAM offset
Tune1                                   equ $0607  ; NES RAM offset
Sample                                  equ $0608  ; NES RAM offset
Song                                    equ $0609  ; NES RAM offset
NoteOffsetSongSq1                       equ $060A  ; NES RAM offset
NoteOffsetSongSq0                       equ $060B  ; NES RAM offset
NoteOffsetSongTrg                       equ $060C  ; NES RAM offset
NoteOffsetSongNoise                     equ $060D  ; NES RAM offset
TunePtr0                                equ $060E  ; NES RAM offset
NoteLengthSongSq0                       equ $060F  ; NES RAM offset
NoteLengthSongSq1                       equ $0610  ; NES RAM offset
NoteCounterSongSq1                      equ $0611  ; NES RAM offset
CustomEnvelopeOffsetSongSq1             equ $0612  ; NES RAM offset
NoteCounterSongSq0                      equ $0613  ; NES RAM offset
CustomEnvelopeOffsetSongSq0             equ $0614  ; NES RAM offset
NoteLengthSongTrg                       equ $0615  ; NES RAM offset
NoteCounterSongTrg                      equ $0616  ; NES RAM offset
NoteCounterSongNoise                    equ $0617  ; NES RAM offset
TunePtr1                                equ $0618  ; NES RAM offset
SongEnvelopeSelector                    equ $0619  ; NES RAM offset
SongVibrationCounterSq1                 equ $061B  ; NES RAM offset
SongVibrationCounterSq0                 equ $061C  ; NES RAM offset
SongVibrationCounterTrg                 equ $061D  ; NES RAM offset
SongRepetitionsTrg                      equ $061E  ; NES RAM offset
SongRepeatStartOffset                   equ $061F  ; NES RAM offset
CurRoomHistoryIndex                     equ $0620  ; NES RAM offset
RoomHistory                             equ $0621  ; NES RAM offset
WorldKillCount                          equ $0627  ; NES RAM offset
QuestNumbers                            equ $062D  ; NES RAM offset
DeathCounts                             equ $0630  ; NES RAM offset
IsSaveSlotActive                        equ $0633  ; NES RAM offset
IsRegisterSaveFileOptionEnabled         equ $0636  ; NES RAM offset
IsEliminateSaveFileOptionEnabled        equ $0637  ; NES RAM offset
Names                                   equ $0638  ; NES RAM offset
SaveSlotHearts                          equ $0650  ; NES RAM offset
SelectedItemSlot                        equ $0656  ; NES RAM offset
Items                                   equ $0657  ; NES RAM offset
InvBombs                                equ $0658  ; NES RAM offset
InvArrow                                equ $0659  ; NES RAM offset
Bow                                     equ $065A  ; NES RAM offset
InvCandle                               equ $065B  ; NES RAM offset
InvFood                                 equ $065D  ; NES RAM offset
Potion                                  equ $065E  ; NES RAM offset
InvRaft                                 equ $0660  ; NES RAM offset
InvBook                                 equ $0661  ; NES RAM offset
InvRing                                 equ $0662  ; NES RAM offset
InvLadder                               equ $0663  ; NES RAM offset
InvMagicKey                             equ $0664  ; NES RAM offset
InvBracelet                             equ $0665  ; NES RAM offset
InvLetter                               equ $0666  ; NES RAM offset
InvCompass                              equ $0667  ; NES RAM offset
InvMap                                  equ $0668  ; NES RAM offset
InvCompass9                             equ $0669  ; NES RAM offset
InvMap9                                 equ $066A  ; NES RAM offset
InvClock                                equ $066C  ; NES RAM offset
InvRupees                               equ $066D  ; NES RAM offset
InvKeys                                 equ $066E  ; NES RAM offset
HeartValues                             equ $066F  ; NES RAM offset
HeartPartial                            equ $0670  ; NES RAM offset
InvTriforce                             equ $0671  ; NES RAM offset
LastBossDefeated                        equ $0672  ; NES RAM offset
InvBoomerang                            equ $0674  ; NES RAM offset
InvMagicBoomerang                       equ $0675  ; NES RAM offset
InvMagicShield                          equ $0676  ; NES RAM offset
MaxBombs                                equ $067C  ; NES RAM offset
RupeesToAdd                             equ $067D  ; NES RAM offset
RupeesToSubtract                        equ $067E  ; NES RAM offset
WorldFlags                              equ $067F  ; NES RAM offset
PpuControl_2000                         equ $2000  ; NES I/O
PpuMask_2001                            equ $2001  ; NES I/O
PpuStatus_2002                          equ $2002  ; NES I/O
OamAddr_2003                            equ $2003  ; NES I/O
OamData_2004                            equ $2004  ; NES I/O
PpuScroll_2005                          equ $2005  ; NES I/O
PpuAddr_2006                            equ $2006  ; NES I/O
PpuData_2007                            equ $2007  ; NES I/O
Sq0Duty_4000                            equ $4000  ; NES I/O
Sq0Sweep_4001                           equ $4001  ; NES I/O
Sq0Timer_4002                           equ $4002  ; NES I/O
Sq0Length_4003                          equ $4003  ; NES I/O
Sq1Duty_4004                            equ $4004  ; NES I/O
Sq1Sweep_4005                           equ $4005  ; NES I/O
Sq1Timer_4006                           equ $4006  ; NES I/O
Sq1Length_4007                          equ $4007  ; NES I/O
TrgLinear_4008                          equ $4008  ; NES I/O
TrgTimer_400A                           equ $400A  ; NES I/O
TrgLength_400B                          equ $400B  ; NES I/O
NoiseVolume_400C                        equ $400C  ; NES I/O
NoisePeriod_400E                        equ $400E  ; NES I/O
NoiseLength_400F                        equ $400F  ; NES I/O
DmcFreq_4010                            equ $4010  ; NES I/O
DmcCounter_4011                         equ $4011  ; NES I/O
DmcAddress_4012                         equ $4012  ; NES I/O
DmcLength_4013                          equ $4013  ; NES I/O
SpriteDma_4014                          equ $4014  ; NES I/O
ApuStatus_4015                          equ $4015  ; NES I/O
Ctrl1_4016                              equ $4016  ; NES I/O
Ctrl2_FrameCtr_4017                     equ $4017  ; NES I/O
SaveRamBegin                            equ $6001  ; NES SRAM
SaveFileAName0                          equ $6002  ; NES SRAM
SaveFileAName1                          equ $600A  ; NES SRAM
SaveFileAName2                          equ $6012  ; NES SRAM
SaveFileAItems0                         equ $601A  ; NES SRAM
SaveFileAItems1                         equ $6042  ; NES SRAM
SaveFileAItems2                         equ $606A  ; NES SRAM
SaveFileAWorldFlags0                    equ $6092  ; NES SRAM
SaveFileAWorldFlags1                    equ $6212  ; NES SRAM
SaveFileAWorldFlags2                    equ $6392  ; NES SRAM
SaveFileASlotActive0                    equ $6512  ; NES SRAM
SaveFileASlotActive1                    equ $6513  ; NES SRAM
SaveFileASlotActive2                    equ $6514  ; NES SRAM
SaveFileADeathCount0                    equ $6515  ; NES SRAM
SaveFileADeathCount1                    equ $6516  ; NES SRAM
SaveFileADeathCount2                    equ $6517  ; NES SRAM
SaveFileAQuestNumber0                   equ $651B  ; NES SRAM
SaveFileAQuestNumber1                   equ $651C  ; NES SRAM
SaveFileAQuestNumber2                   equ $651D  ; NES SRAM
SaveFileOpenMarkers                     equ $651E  ; NES SRAM
SaveFileCloseMarkers                    equ $6521  ; NES SRAM
FileAChecksums                          equ $6524  ; NES SRAM
IsSaveFileBCommitted                    equ $652A  ; NES SRAM
PlayAreaTiles                           equ $6530  ; NES SRAM
LevelBlockAttrsA                        equ $687E  ; NES SRAM
LevelBlockAttrsB                        equ $68FE  ; NES SRAM
LevelBlockAttrsC                        equ $697E  ; NES SRAM
LevelBlockAttrsD                        equ $69FE  ; NES SRAM
LevelBlockAttrsE                        equ $6A7E  ; NES SRAM
LevelBlockAttrsF                        equ $6AFE  ; NES SRAM
LevelInfo_PalettesTransferBuf           equ $6B7E  ; NES SRAM
LevelInfo_FoeCounts                     equ $6BA2  ; NES SRAM
LevelInfo_StartY                        equ $6BA6  ; NES SRAM
LevelInfo_ShortcutOrItemPosArray        equ $6BA7  ; NES SRAM
LevelInfo_SubmenuMapRotation            equ $6BAB  ; NES SRAM
LevelInfo_StatusBarMapXOffset           equ $6BAC  ; NES SRAM
LevelInfo_StartRoomId                   equ $6BAD  ; NES SRAM
LevelInfo_TriforceRoomId                equ $6BAE  ; NES SRAM
LevelInfo_WorldFlagsAddr                equ $6BAF  ; NES SRAM
LevelInfo_LevelNumber                   equ $6BB1  ; NES SRAM
LevelInfo_CellarRoomIdArray             equ $6BB2  ; NES SRAM
LevelInfo_BossRoomId                    equ $6BBC  ; NES SRAM
LevelInfo_SubmenuMapMask                equ $6BBD  ; NES SRAM
LevelInfo_StatusBarMapTransferBuf       equ $6BCD  ; NES SRAM
LevelInfo_PaletteCycles                 equ $6BFA  ; NES SRAM
LevelInfo_DeathPaletteSeries            equ $6C5A  ; NES SRAM
SaveRamEnd                              equ $7FFF  ; NES SRAM
;==============================================================================
; Begin translated Z_06.asm code
;==============================================================================

; [skipped] .INCLUDE "Variables.inc"

; === .SEGMENT "BANK_06_00" ===


; Imports from program bank 07

; .IMPORT TableJump

; .EXPORT CopyCommonDataToRam
; .EXPORT InitMode2_Submodes
; .EXPORT UpdateMode2Load_Full

    even
LevelBlockAddrsQ1:
    dc.l    LevelBlockOW   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW2Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW2Q1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW2Q1   ; NES addr vector (32-bit for M68K)

    even
LevelInfoAddrs:
    dc.l    LevelInfoOW   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW3   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW4   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW5   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW6   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW7   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW8   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUW9   ; NES addr vector (32-bit for M68K)

    even
CommonDataBlockAddr_Bank6:
    dc.l    CommonDataBlock_Bank6   ; NES addr vector (32-bit for M68K)

    even
LevelBlockAddrsQ2:
    dc.l    LevelBlockOW   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW1Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW2Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW2Q2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelBlockUW2Q2   ; NES addr vector (32-bit for M68K)

    even
InitMode2_Submodes:
    move.b  ($0013,A4),D0
    bsr     _m68k_tablejump  ; M68K-native table dispatch (replaces JSR TableJump)
    even
InitMode2_Submodes_JumpTable:
    dc.l    InitMode2_Sub0   ; NES addr vector (32-bit for M68K)
    dc.l    InitMode2_Sub1   ; NES addr vector (32-bit for M68K)

    even
InitMode2_Sub0:
    ; Copy level block for level.
    ;
    move.b  ($0010,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    move.b  ($0016,A4),D3
    lea     ($062D,A4),A0
    move.b  (A0,D3.W),D0
    bne  _L_z06_InitMode2_Sub0_SecondQuest
    ; First quest.
    ;
    lea     (LevelBlockAddrsQ1).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (LevelBlockAddrsQ1).l,A0
    move.b  (A0,D2.W),D0
    jmp     _L_z06_InitMode2_Sub0_Copy

    even
_L_z06_InitMode2_Sub0_SecondQuest:
    ; Second quest.
    ;
    lea     (LevelBlockAddrsQ2).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (LevelBlockAddrsQ2).l,A0
    move.b  (A0,D2.W),D0
    even
_L_z06_InitMode2_Sub0_Copy:
    move.b  D0,($0001,A4)
    bsr     FetchLevelBlockDestInfo
    bsr     CopyBlock
    rts

    even
InitMode2_Sub1:
    ; Copy level info.
    ;
    move.b  ($0010,A4),D0
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D2
    lea     (LevelInfoAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (LevelInfoAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    bsr     FetchLevelInfoDestInfo
    bsr     CopyBlock
    moveq   #0,D0
    move.b  D0,($0013,A4)
    addq.b  #1,($0011,A4)
    rts

    even
CopyCommonDataToRam:
    moveq   #0,D2
    lea     (CommonDataBlockAddr_Bank6).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    addq.b  #1,D2
    lea     (CommonDataBlockAddr_Bank6).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    bsr     FetchDestAddrForCommonDataBlock
    bsr     CopyBlock
    moveq   #0,D0
    move.b  D0,($0013,A4)
    rts

; Returns:
; [$02:03]: destination address
; [$04:05]: end address
;
; Destination address $687E.
    even
FetchLevelBlockDestInfo:
    moveq   #126,D0
    move.b  D0,($0002,A4)
    moveq   #104,D0
    move.b  D0,($0003,A4)
    moveq   #125,D0
    move.b  D0,($0004,A4)
    moveq   #107,D0
    move.b  D0,($0005,A4)
    rts

; Returns:
; [$02:03]: destination address
; [$04:05]: end address
;
; Destination address $6B7E.
    even
FetchLevelInfoDestInfo:
    moveq   #126,D0
    move.b  D0,($0002,A4)
    moveq   #107,D0
    move.b  D0,($0003,A4)
    moveq   #125,D0
    move.b  D0,($0004,A4)
    moveq   #108,D0
    move.b  D0,($0005,A4)
    rts

    even
FetchDestAddrForCommonDataBlock:
    move.b  #$F0,D0
    move.b  D0,($0002,A4)
    moveq   #103,D0
    move.b  D0,($0003,A4)
    moveq   #125,D0
    move.b  D0,($0004,A4)
    moveq   #104,D0
    move.b  D0,($0005,A4)
    rts

; Params:
; [$00:01]: source address
; [$02:03]: destination address
; [$04:05]: end destination address
;
; Also increments submode.
;
    even
CopyBlock:
    moveq   #0,D3
    even
_L_z06_CopyBlock_Loop:
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    move.b  ($02,A4),D1   ; ptr lo
    move.b  ($03,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4
    ext.l   D4
    add.l   #NES_RAM,D4
    movea.l D4,A0
    move.b  D0,(A0,D3.W)     ; STA ($nn),Y
    move.b  ($0002,A4),D0
    move.b  ($0004,A4),D1
    cmp.b   D1,D0
    bne  _L_z06_CopyBlock_Next
    move.b  ($0003,A4),D0
    move.b  ($0005,A4),D1
    cmp.b   D1,D0
    bne  _L_z06_CopyBlock_Next
    addq.b  #1,($0013,A4)
    rts

    even
_L_z06_CopyBlock_Next:
    move.b  ($0002,A4),D0
    andi.b  #$EE,CCR  ; CLC: clear C+X
    move.b  #$01,D1
    addx.b  D1,D0   ; ADC #$01 (X flag = 6502 C)
    move.b  D0,($0002,A4)
    move.b  ($0003,A4),D0
    move.b  #$00,D1
    addx.b  D1,D0   ; ADC #$00 (X flag = 6502 C)
    move.b  D0,($0003,A4)
    move.b  ($0000,A4),D0
    andi.b  #$EE,CCR  ; CLC: clear C+X
    move.b  #$01,D1
    addx.b  D1,D0   ; ADC #$01 (X flag = 6502 C)
    move.b  D0,($0000,A4)
    move.b  ($0001,A4),D0
    move.b  #$00,D1
    addx.b  D1,D0   ; ADC #$00 (X flag = 6502 C)
    move.b  D0,($0001,A4)
    jmp     _L_z06_CopyBlock_Loop

    even
UpdateMode2Load_Full:
    ; Make replacements for the second quest.
    ;
    move.b  ($0016,A4),D3
    lea     ($062D,A4),A0
    move.b  (A0,D3.W),D0
    beq  _L_z06_UpdateMode2Load_Full_Exit
    move.b  ($0010,A4),D0
    beq  _L_z06_UpdateMode2Load_Full_PatchQ2Rooms
    move.b  D0,D2
    lsl.b  #1,D0   ; ASL A
    move.b  D0,D3
    ; Get an address for the current level that points
    ; to an array of replacement bytes for Q2 UW level info.
    ;
    ; This address array doesn't access the OW element (0).
    ; So, it overlaps the last two bytes of LevelInfoUWQ2Replacements9.
    ;
    lea     (LevelInfoUWQ2ReplacementAddrs-2).l,A0
    move.b  (A0,D3.W),D0
    move.b  D0,($0000,A4)
    lea     (LevelInfoUWQ2ReplacementAddrs-1).l,A0
    move.b  (A0,D3.W),D0
    move.b  D0,($0001,A4)
    ; Get the number of replacement bytes for Q2 UW level info.
    ; This address array doesn't access the OW element (0).
    ;
    lea     (LevelInfoUWQ2ReplacementSizes-1).l,A0
    move.b  (A0,D2.W),D3
    even
_L_z06_UpdateMode2Load_Full_ReplaceInfoBytes:
    ; Copy bytes from Q2 replacement array to level info
    ; starting at offset $29 (shortcut position array).
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    lea     (NES_SRAM+$0BA7).l,A0
    move.b  D0,(A0,D3.W)
    subq.b  #1,D3
    bpl  _L_z06_UpdateMode2Load_Full_ReplaceInfoBytes
    even
_L_z06_UpdateMode2Load_Full_Exit:
    rts

    even
_L_z06_UpdateMode2Load_Full_PatchQ2Rooms:
    ; Replace attributes of several rooms in OW in second quest.
    ;
    moveq   #7,D3
    even
_L_z06_UpdateMode2Load_Full_ReplaceRoomBytes:
    lea     (LevelBlockAttrsBQ2ReplacementOffsets).l,A0
    move.b  (A0,D3.W),D2
    lea     (LevelBlockAttrsBQ2ReplacementValues).l,A0
    move.b  (A0,D3.W),D0
    lea     (NES_SRAM+$08FE).l,A0
    move.b  D0,(A0,D2.W)
    subq.b  #1,D3
    bpl  _L_z06_UpdateMode2Load_Full_ReplaceRoomBytes
    moveq   #123,D0
    move.b  D0,(NES_SRAM+$0A09).l
    moveq   #123,D0
    move.b  D0,(NES_SRAM+$0A3A).l
    moveq   #90,D0
    move.b  D0,(NES_SRAM+$0A72).l
    moveq   #114,D0
    move.b  D0,(NES_SRAM+$08BA).l
    moveq   #114,D0
    move.b  D0,(NES_SRAM+$08F2).l
    moveq   #1,D0
    move.b  D0,(NES_SRAM+$0B3A).l
    moveq   #0,D0
    move.b  D0,(NES_SRAM+$0B72).l
    rts

    even
LevelBlockAttrsBQ2ReplacementOffsets:
    dc.b    $0E, $0F, $22, $34, $3C, $45, $74, $8B

    even
LevelBlockAttrsBQ2ReplacementValues:
    dc.b    $7B, $83, $84, $0F, $0B, $12, $7A, $2F

    even
LevelInfoUWQ2Replacements1:
    dc.b    $C9, $AC, $89, $B7, $00, $E0, $77, $08
    dc.b    $FF, $06, $01, $28, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $07, $00, $00
    dc.b    $00, $00, $00, $00, $00, $FF, $DB, $00
    dc.b    $00, $00, $00, $00, $00, $00, $20, $65
    dc.b    $42, $FF, $20, $85, $02, $FF, $FB, $20
    dc.b    $A5, $02, $FF, $67, $20, $C5, $42, $FF
    dc.b    $FF

    even
LevelInfoUWQ2Replacements2:
    dc.b    $C9, $AC, $89, $87, $05, $00, $75, $20
    dc.b    $FF, $06, $03, $56, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $30, $00, $00
    dc.b    $00, $00, $00, $30, $00, $00, $00, $00
    dc.b    $7F, $03, $00, $00, $00, $00, $20, $67
    dc.b    $01, $FB, $20, $82, $01, $FF, $20, $87
    dc.b    $C3, $FF, $20, $C8, $01, $FF, $FF

    even
LevelInfoUWQ2Replacements3:
    dc.b    $C9, $AC, $89, $37, $0D, $C8, $79, $1B
    dc.b    $FF, $06, $02, $09, $0B, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $2B, $00, $00
    dc.b    $00, $00, $00, $00, $7F, $EC, $7F, $00
    dc.b    $00, $00, $00, $00, $00, $00, $20, $64
    dc.b    $03, $FB, $FF, $FB, $20, $84, $03, $FF
    dc.b    $67, $FF, $20, $A4, $43, $FF, $20, $C4
    dc.b    $03, $FF, $24, $FF, $FF

    even
LevelInfoUWQ2Replacements4:
    dc.b    $C9, $AC, $89, $86, $06, $10, $72, $00
    dc.b    $FF, $06, $05, $21, $58, $7A, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $10, $00, $00
    dc.b    $00, $00, $00, $00, $CF, $DB, $F3, $00
    dc.b    $00, $00, $00, $00, $00, $00, $20, $64
    dc.b    $43, $FF, $20, $85, $02, $FB, $FF, $20
    dc.b    $A4, $02, $FF, $67, $20, $C4, $43, $FF
    dc.b    $FF

    even
LevelInfoUWQ2Replacements5:
    dc.b    $C9, $AC, $89, $87, $0A, $B0, $7D, $4F
    dc.b    $FF, $06, $04, $0F, $6A, $7F, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $5F, $00, $00
    dc.b    $00, $00, $00, $00, $FF, $FF, $E7, $7E
    dc.b    $00, $00, $00, $00, $00, $00, $20, $64
    dc.b    $04, $FF, $FF, $FF, $FB, $20, $84, $04
    dc.b    $FF, $FF, $67, $FF, $20, $A4, $04, $FF
    dc.b    $FF, $FB, $FF, $20, $C4, $04, $FF, $FF
    dc.b    $FF, $67, $FF

    even
LevelInfoUWQ2Replacements6:
    dc.b    $49, $79, $89, $56, $04, $00, $74, $16
    dc.b    $FF, $06, $06, $03, $73, $46, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $26, $00, $00
    dc.b    $00, $00, $00, $04, $0C, $7E, $FF, $80
    dc.b    $F0, $00, $00, $00, $00, $00, $20, $65
    dc.b    $03, $FB, $FF, $67, $20, $68, $C2, $FF
    dc.b    $20, $86, $C3, $FF, $20, $85, $83, $FF
    dc.b    $FF, $67, $20, $A3, $02, $FB, $FF, $FF

    even
LevelInfoUWQ2Replacements7:
    dc.b    $C9, $AC, $89, $79, $0C, $C0, $7F, $2D
    dc.b    $7F, $07, $08, $02, $03, $04, $05, $20
    dc.b    $21, $26, $2B, $2C, $FF, $3D, $00, $00
    dc.b    $00, $00, $FE, $FE, $82, $82, $82, $BE
    dc.b    $80, $FF, $00, $00, $00, $00, $20, $62
    dc.b    $C3, $FF, $20, $63, $C3, $FF, $20, $64
    dc.b    $45, $67, $20, $69, $C4, $FF, $20, $87
    dc.b    $C2, $FF, $20, $C2, $46, $67, $FF

    even
LevelInfoUWQ2Replacements8:
    dc.b    $C9, $AC, $89, $57, $0C, $C0, $79, $1B
    dc.b    $7F, $07, $07, $27, $30, $37, $60, $67
    dc.b    $70, $FF, $FF, $FF, $FF, $1C, $00, $00
    dc.b    $00, $00, $01, $01, $7D, $5D, $5D, $41
    dc.b    $7F, $00, $00, $00, $00, $00, $20, $64
    dc.b    $45, $FB, $20, $84, $05, $FF, $FB, $FB
    dc.b    $24, $FF, $20, $A4, $43, $FF, $20, $A8
    dc.b    $01, $FF, $20, $C2, $46, $FB, $20, $C8
    dc.b    $01, $FF, $FF

    even
LevelInfoUWQ2Replacements9:
    dc.b    $C9, $AC, $89, $B6, $04, $00, $74, $07
    dc.b    $7F, $07, $09, $71, $72, $75, $76, $77
    dc.b    $FF, $FF, $FF, $FF, $FF, $17, $00, $00
    dc.b    $00, $00, $CC, $DE, $76, $7F, $7F, $76
    dc.b    $DE, $CC, $00, $00, $00, $00, $20, $62
    dc.b    $48, $FF, $20, $64, $44, $FB, $20, $83
    dc.b    $46, $FB, $20, $84, $44, $FF, $20, $A2
    dc.b    $08, $FF, $FF, $FB, $FF, $FF, $FB, $FF
    dc.b    $FF, $20, $C3, $46, $67, $20, $C5, $42
    dc.b    $FF, $FF

    even
LevelInfoUWQ2ReplacementAddrs:
    dc.l    LevelInfoUWQ2Replacements1   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements2   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements3   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements4   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements5   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements6   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements7   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements8   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfoUWQ2Replacements9   ; NES addr vector (32-bit for M68K)

    even
LevelInfoUWQ2ReplacementSizes:
    dc.b    $39, $37, $3D, $39, $43, $40, $3F, $43
    dc.b    $4A

; Unknown block
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    dc.b    $FF

    even
LevelBlockOW:
; .INCBIN "dat/LevelBlockOW.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelBlockUW1Q1:
; .INCBIN "dat/LevelBlockUW1Q1.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelBlockUW2Q1:
; .INCBIN "dat/LevelBlockUW2Q1.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelBlockUW1Q2:
; .INCBIN "dat/LevelBlockUW1Q2.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelBlockUW2Q2:
; .INCBIN "dat/LevelBlockUW2Q2.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoOW:
; .INCBIN "dat/LevelInfoOW.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW1:
; .INCBIN "dat/LevelInfoUW1.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW2:
; .INCBIN "dat/LevelInfoUW2.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW3:
; .INCBIN "dat/LevelInfoUW3.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW4:
; .INCBIN "dat/LevelInfoUW4.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW5:
; .INCBIN "dat/LevelInfoUW5.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW6:
; .INCBIN "dat/LevelInfoUW6.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW7:
; .INCBIN "dat/LevelInfoUW7.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW8:
; .INCBIN "dat/LevelInfoUW8.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
LevelInfoUW9:
; .INCBIN "dat/LevelInfoUW9.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
CommonDataBlock_Bank6:

; === .SEGMENT "BANK_06_DATA" ===


; .EXPORT ColumnDirectoryOW
; .EXPORT LevelNumberTransferBuf
; .EXPORT LevelPaletteRow7TransferBuf
; .EXPORT MenuPalettesTransferBuf
; .EXPORT TriforceRow0TransferBuf

    even
MenuPalettesTransferBuf:
    dc.b    $3F, $00, $20, $0F, $30, $00, $12, $0F
    dc.b    $16, $27, $36, $0F, $0C, $1C, $2C, $0F
    dc.b    $12, $1C, $2C, $0F, $29, $27, $07, $0F
    dc.b    $22, $27, $07, $0F, $26, $27, $07, $0F
    dc.b    $15, $27, $30, $FF

    even
LevelPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $0F, $0F, $0F, $FF

    even
LevelNumberTransferBuf:
    dc.b    $20, $42, $07, $15, $0E, $1F, $0E, $15
    dc.b    $62, $00, $FF

    even
ColumnDirectoryOW:
    dc.b    $D8, $9B, $0D, $9C, $3E, $9C, $80, $9C
    dc.b    $C4, $9C, $F6, $9C, $32, $9D, $6D, $9D
    dc.b    $A8, $9D, $E6, $9D, $27, $9E, $6C, $9E
    dc.b    $A9, $9E, $DF, $9E, $21, $9F, $55, $9F

    even
TriforceRow0TransferBuf:
    dc.b    $2A, $EE, $04, $ED, $E9, $EA, $EE, $FF

    even
TriforceRow1TransferBuf:
    dc.b    $2B, $0D, $06, $ED, $E9, $24, $24, $EA
    dc.b    $EE, $FF

    even
TriforceRow2TransferBuf:
    dc.b    $2B, $2C, $08, $ED, $E9, $24, $24, $24
    dc.b    $24, $EA, $EE, $FF

    even
TriforceRow3TransferBuf:
    dc.b    $2B, $4B, $0A, $ED, $E9, $24, $24, $24
    dc.b    $24, $24, $24, $EA, $EE, $FF

    even
TriforceTextTransferBuf:
    dc.b    $2B, $AC, $08, $1D, $1B, $12, $0F, $18
    dc.b    $1B, $0C, $0E


; === .SEGMENT "BANK_06_DLIST" ===


; .EXPORT TransferCurTileBuf

    even
TransferBufAddrs:
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    StoryTileAttrTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    Mode8TextTileBuffer   ; NES addr vector (32-bit for M68K)
    dc.l    LevelPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    AquamentusPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    OrangeBossPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    LevelNumberTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    StatusBarStaticsTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    GameTitleTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    MenuPalettesTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    Mode1TileTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    ModeFCharsTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfo_PalettesTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    BlankTextBoxLines   ; NES addr vector (32-bit for M68K)
    dc.l    GhostPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    GreenBgPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    BrownBgPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    CellarAttrsTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    BlankPersonWares   ; NES addr vector (32-bit for M68K)
    dc.l    Mode11DeadLinkPalette   ; NES addr vector (32-bit for M68K)
    dc.l    LevelNumberTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    InventoryTextTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SubmenuBoxesTopsTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SubmenuBoxesSidesTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    GanonPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SelectedItemBoxBottomTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    UseBButtonTextTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    InventoryBoxBottomTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    CaveBgPaletteRowsTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SubmenuMapRemainderTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SheetMapBottomEdgeTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    LevelInfo_StatusBarMapTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    GameOverTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SubmenuAttrs1TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SubmenuAttrs2TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    BlankBottomRowNT2TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    BlankRowTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SubmenuTriforceApexTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    TriforceRow0TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    TriforceRow1TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    TriforceRow2TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    TriforceRow3TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    SubmenuTriforceBottomTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    TriforceTextTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    Mode11BackgroundPaletteBottomHalfTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    Mode11PlayAreaAttrsTopHalfTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    Mode11PlayAreaAttrsBottomHalfTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    EndingPaletteTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    BombCapacityPriceTextTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)
    dc.l    LifeOrMoneyCostTextTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    WhitePaletteBottomHalfTransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    RedArmosPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    GleeokPaletteRow7TransferBuf   ; NES addr vector (32-bit for M68K)
    dc.l    DynTileBuf   ; NES addr vector (32-bit for M68K)

    even
TransferCurTileBuf:
    move.b  ($0014,A4),D2
    lea     (TransferBufAddrs).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0000,A4)
    lea     (TransferBufAddrs+1).l,A0
    move.b  (A0,D2.W),D0
    move.b  D0,($0001,A4)
    bsr     TransferTileBuf
    moveq   #63,D0
    move.b  D0,($0300,A4)
    moveq   #0,D2
    move.b  D2,($0014,A4)
    move.b  D2,($005C,A4)
    move.b  D2,($0301,A4)
    subq.b  #1,D2
    move.b  D2,($0302,A4)
    rts

    even
ContinueTransferTileBuf:
    ;
    ;
    ; Save VRAM address high byte.
    move.b  D0,-(A5)  ; PHA
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    addq.b  #1,D3
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    addq.b  #1,D3
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    lsl.b  #1,D0   ; ASL A
    move.b  D0,-(A5)  ; PHA
    move.b  ($00FF,A4),D0
    ori.b #$04,D0
    bcs  _anon_z06_0
    andi.b #$FB,D0
_anon_z06_0:
    bsr     _ppu_write_0  ; PPU $2000 write, D0=val
    move.b  D0,($00FF,A4)
    move.b  (A5)+,D0  ; PLA
    lsl.b  #1,D0   ; ASL A
    move.w  SR,D1
    move.b  D1,-(A5)  ; PHP: push CCR
    bcc  _anon_z06_1
    ori.b #$02,D0
    addq.b  #1,D3
_anon_z06_1:
    move.b  (A5)+,D1  ; PLP: pop to CCR
    move.b  D1,CCR
    ; If the count was 0 (bottom 6 bits),
    ; then make it 64.
    andi.b  #$EE,CCR  ; CLC: clear C+X
    bne  _anon_z06_2
    ori.b   #$11,CCR  ; SEC: set C+X
_anon_z06_2:
    roxr.b  #1,D0   ; ROR A
    lsr.b  #1,D0   ; LSR A
    ; We pulled the flags out, and we're left with a count in A.
    ; Move it to X.
    move.b  D0,D2
    even
_L_z06_ContinueTransferTileBuf_Loop:
    bcs  _anon_z06_3
    addq.b  #1,D3
_anon_z06_3:
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    bsr     _ppu_write_7  ; PPU $2007 write, D0=val
    subq.b  #1,D2
    bne  _L_z06_ContinueTransferTileBuf_Loop
    move.b  (A5)+,D0  ; PLA
    ; If we wrote to $3Fxx, then set PPUADDR to $3F00, then $0000.
    ;
    cmpi.b  #$3F,D0
    bne  _L_z06_ContinueTransferTileBuf_AdvanceSource
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    move.l  D0,-(SP)       ; save A (6502 STX/STY never modifies A)
    move.b  D2,D0  ; D2 → D0 for I/O write
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    move.l  (SP)+,D0       ; restore A
    move.l  D0,-(SP)       ; save A (6502 STX/STY never modifies A)
    move.b  D2,D0  ; D2 → D0 for I/O write
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    move.l  (SP)+,D0       ; restore A
    move.l  D0,-(SP)       ; save A (6502 STX/STY never modifies A)
    move.b  D2,D0  ; D2 → D0 for I/O write
    bsr     _ppu_write_6  ; PPU $2006 write, D0=val
    move.l  (SP)+,D0       ; restore A
    even
_L_z06_ContinueTransferTileBuf_AdvanceSource:
    ; Advance the source address to one after the last byte read.
    ;
    ori.b   #$11,CCR  ; SEC: set C+X
    move.b  D3,D0
    move.b  ($0000,A4),D1
    addx.b  D1,D0   ; ADC $00
    move.b  D0,($0000,A4)
    moveq   #0,D0
    move.b  ($0001,A4),D1
    addx.b  D1,D0   ; ADC $01
    move.b  D0,($0001,A4)
    even
TransferTileBuf:
    bsr     _ppu_read_2  ; PPU $2002 read → D0
    move.b  D0,D2
    moveq   #0,D3
    move.b  ($00,A4),D1   ; ptr lo
    move.b  ($01,A4),D4  ; ptr hi
    lsl.w   #8,D4
    or.w    D1,D4             ; D4 = NES ptr addr
    ext.l   D4
    add.l   #NES_RAM,D4       ; → Genesis addr
    movea.l D4,A0
    move.b  (A0,D3.W),D0     ; LDA ($nn),Y
    bpl  ContinueTransferTileBuf
    rts

    even
Mode1TileTransferBuf:
    dc.b    $23, $C0, $7F, $00, $23, $D4, $03, $40
    dc.b    $50, $50, $23, $DC, $03, $44, $55, $55
    dc.b    $23, $E4, $03, $44, $55, $55, $20, $A8
    dc.b    $0F, $62, $24, $1C, $24, $0E, $24, $15
    dc.b    $24, $0E, $24, $0C, $24, $1D, $24, $62
    dc.b    $21, $03, $01, $69, $21, $04, $58, $6A
    dc.b    $21, $1C, $01, $6B, $21, $23, $D0, $6C
    dc.b    $21, $3C, $D0, $6C, $23, $23, $01, $6E
    dc.b    $23, $24, $58, $6A, $23, $3C, $01, $6D
    dc.b    $21, $0A, $06, $24, $17, $0A, $16, $0E
    dc.b    $24, $21, $13, $06, $24, $15, $12, $0F
    dc.b    $0E, $24, $22, $A6, $12, $1B, $0E, $10
    dc.b    $12, $1C, $1D, $0E, $1B, $24, $22, $18
    dc.b    $1E, $1B, $24, $17, $0A, $16, $0E, $22
    dc.b    $E6, $10, $0E, $15, $12, $16, $12, $17
    dc.b    $0A, $1D, $12, $18, $17, $24, $16, $18
    dc.b    $0D, $0E, $FF

    even
ModeFCharsTransferBuf:
    dc.b    $22, $05, $01, $69, $22, $06, $55, $6A
    dc.b    $22, $1B, $01, $6B, $22, $25, $C7, $6C
    dc.b    $22, $3B, $C7, $6C, $23, $05, $01, $6E
    dc.b    $23, $06, $55, $6A, $23, $1B, $01, $6D
    dc.b    $22, $26, $15, $0A, $24, $0B, $24, $0C
    dc.b    $24, $0D, $24, $0E, $24, $0F, $24, $10
    dc.b    $24, $11, $24, $12, $24, $13, $24, $14
    dc.b    $22, $66, $15, $15, $24, $16, $24, $17
    dc.b    $24, $18, $24, $19, $24, $1A, $24, $1B
    dc.b    $24, $1C, $24, $1D, $24, $1E, $24, $1F
    dc.b    $22, $A6, $15, $20, $24, $21, $24, $22
    dc.b    $24, $23, $24, $62, $24, $63, $24, $28
    dc.b    $24, $29, $24, $2A, $24, $2B, $24, $2C
    dc.b    $22, $E6, $13, $00, $24, $01, $24, $02
    dc.b    $24, $03, $24, $04, $24, $05, $24, $06
    dc.b    $24, $07, $24, $08, $24, $09, $FF

    even
GanonPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $16, $2C, $3C, $FF

    even
EndingPaletteTransferBuf:
    dc.b    $3F, $08, $08, $0F, $22, $10, $00, $0F
    dc.b    $2A, $10, $00, $3F, $1C, $04, $0F, $27
    dc.b    $06, $16, $FF

    even
BlankTextBoxLines:
    dc.b    $21, $A4, $58, $24, $21, $C4, $58, $24
    dc.b    $FF

    even
BlankPersonWares:
    dc.b    $21, $E4, $58, $24, $22, $C8, $4D, $24
    dc.b    $FF

    even
SubmenuTriforceApexTransferBuf:
    dc.b    $2A, $CF, $02, $ED, $EE, $FF

    even
SubmenuTriforceBottomTransferBuf:
    dc.b    $2B, $6A, $0C, $EB, $EF, $F1, $F1, $F1
    dc.b    $F1, $F1, $F1, $F1, $F1, $F0, $EC, $FF

    even
GhostPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $30, $00, $12, $FF

    even
GreenBgPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $1A, $37, $12, $FF

    even
BrownBgPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $17, $37, $12, $FF

    even
CaveBgPaletteRowsTransferBuf:
    dc.b    $3F, $08, $08, $0F, $30, $00, $12, $0F
    dc.b    $07, $0F, $17, $FF

    even
CellarAttrsTransferBuf:
    dc.b    $23, $D0, $60, $AA, $23, $F0, $50, $AA
    dc.b    $FF

    even
WhitePaletteBottomHalfTransferBuf:
    dc.b    $3F, $08, $08, $0F, $30, $30, $30, $0F
    dc.b    $30, $30, $30, $FF

    even
RedArmosPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $0F, $1C, $16, $FF

    even
GleeokPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $2A, $1A, $0C, $FF

    even
AquamentusPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $0A, $29, $30, $FF

    even
OrangeBossPaletteRow7TransferBuf:
    dc.b    $3F, $1C, $04, $0F, $17, $27, $30, $FF

    even
BombCapacityPriceTextTransferBuf:
    dc.b    $22, $CD, $04, $62, $01, $00, $00, $FF

    even
LifeOrMoneyCostTextTransferBuf:
    dc.b    $22, $CB, $0A, $62, $01, $24, $24, $24
    dc.b    $24, $24, $62, $05, $00, $FF

    even
Mode8TextTileBuffer:
    dc.b    $23, $C0, $7F, $00, $21, $4A, $08, $0C
    dc.b    $18, $17, $1D, $12, $17, $1E, $0E, $21
    dc.b    $AA, $04, $1C, $0A, $1F, $0E, $22, $0A
    dc.b    $05, $1B, $0E, $1D, $1B, $22, $FF

    even
StatusBarStaticsTransferBuf:
    dc.b    $23, $C2, $0E, $40, $00, $00, $44, $55
    dc.b    $55, $00, $00, $04, $00, $00, $44, $55
    dc.b    $55, $20, $6F, $0E, $69, $0B, $6B, $69
    dc.b    $0A, $6B, $24, $24, $62, $15, $12, $0F
    dc.b    $0E, $62, $20, $CF, $06, $6E, $6A, $6D
    dc.b    $6E, $6A, $6D, $20, $8F, $C2, $6C, $20
    dc.b    $91, $C2, $6C, $20, $92, $C2, $6C, $20
    dc.b    $94, $C2, $6C, $20, $6B, $84, $F7, $24
    dc.b    $F9, $61, $FF

    even
InventoryTextTransferBuf:
    dc.b    $29, $84, $09, $12, $17, $1F, $0E, $17
    dc.b    $1D, $18, $1B, $22, $FF

    even
SubmenuBoxesTopsTransferBuf:
    dc.b    $29, $C7, $04, $69, $6A, $6A, $6B, $29
    dc.b    $CF, $01, $69, $29, $D0, $4B, $6A, $29
    dc.b    $DB, $01, $6B, $FF

    even
SubmenuBoxesSidesTransferBuf:
    dc.b    $29, $E7, $C2, $6C, $29, $EA, $C2, $6C
    dc.b    $29, $EF, $C4, $6C, $29, $FB, $C4, $6C
    dc.b    $FF

    even
SelectedItemBoxBottomTransferBuf:
    dc.b    $2A, $27, $04, $6E, $6A, $6A, $6D, $FF

    even
UseBButtonTextTransferBuf:
    dc.b    $2A, $42, $0C, $1E, $1C, $0E, $24, $0B
    dc.b    $24, $0B, $1E, $1D, $1D, $18, $17, $FF

    even
InventoryBoxBottomTransferBuf:
    dc.b    $2A, $64, $08, $0F, $18, $1B, $24, $1D
    dc.b    $11, $12, $1C, $2A, $6F, $01, $6E, $2A
    dc.b    $70, $4B, $6A, $2A, $7B, $01, $6D, $FF

    even
SubmenuMapRemainderTransferBuf:
    dc.b    $2B, $43, $07, $0C, $18, $16, $19, $0A
    dc.b    $1C, $1C, $2A, $A5, $03, $16, $0A, $19
    dc.b    $2A, $8C, $10, $F5, $F5, $FD, $F5, $F5
    dc.b    $FD, $F5, $F5, $FD, $F5, $F5, $F5, $FD
    dc.b    $F5, $F5, $F5, $FF

    even
SheetMapBottomEdgeTransferBuf:
    dc.b    $2B, $AC, $10, $F5, $FE, $F5, $F5, $F5
    dc.b    $FE, $F5, $F5, $F5, $F5, $FE, $F5, $F5
    dc.b    $F5, $FE, $F5, $FF

    even
SubmenuAttrs1TransferBuf:
    dc.b    $2B, $D9, $43, $05, $2B, $DC, $4B, $00
    dc.b    $FF

    even
SubmenuAttrs2TransferBuf:
    dc.b    $2B, $E9, $56, $55, $FF

    even
BlankBottomRowNT2TransferBuf:
    dc.b    $2B, $A0, $60, $24, $FF

    even
BlankRowTransferBuf:
    dc.b    $28, $E0, $60, $24, $FF

    even
Mode11DeadLinkPalette:
    dc.b    $3F, $10, $04, $0F, $10, $30, $00, $FF

    even
GameOverTransferBuf:
    dc.b    $23, $E3, $03, $0F, $0F, $CF, $22, $4C
    dc.b    $0A, $10, $0A, $16, $0E, $24, $18, $1F
    dc.b    $0E, $1B, $24, $22, $6C, $4A, $24, $FF

    even
Mode11BackgroundPaletteBottomHalfTransferBuf:
    dc.b    $3F, $08, $08, $0F, $17, $16, $26, $0F
    dc.b    $17, $16, $26, $FF

    even
Mode11PlayAreaAttrsTopHalfTransferBuf:
    dc.b    $23, $D0, $58, $FF, $FF

    even
Mode11PlayAreaAttrsBottomHalfTransferBuf:
    dc.b    $23, $E8, $58, $FF, $FF

    even
StoryTileAttrTransferBuf:
; .INCBIN "dat/StoryTileAttrTransferBuf.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr

    even
GameTitleTransferBuf:
; .INCBIN "dat/GameTitleTransferBuf.dat" not found — stub 128 zero bytes
    rept    128
        dc.b    0
    endr


; === .SEGMENT "BANK_06_ISR" ===



; Unknown block
    dc.b    $78, $D8, $A9, $00, $8D, $00, $20, $A2
    dc.b    $FF, $9A, $AD, $02, $20, $29, $80, $F0
    dc.b    $F9, $AD, $02, $20, $29, $80, $F0, $F9
    dc.b    $09, $FF, $8D, $00, $80, $8D, $00, $A0
    dc.b    $8D, $00, $C0, $8D, $00, $E0, $A9, $0F
    dc.b    $20, $98, $BF, $A9, $00, $8D, $00, $A0
    dc.b    $4A, $8D, $00, $A0, $4A, $8D, $00, $A0
    dc.b    $4A, $8D, $00, $A0, $4A, $8D, $00, $A0
    dc.b    $A9, $07, $20, $AC, $BF, $4C, $40, $E4
    dc.b    $8D, $00, $80, $4A, $8D, $00, $80, $4A
    dc.b    $8D, $00, $80, $4A, $8D, $00, $80, $4A
    dc.b    $8D, $00, $80, $60, $8D, $00, $E0, $4A
    dc.b    $8D, $00, $E0, $4A, $8D, $00, $E0, $4A
    dc.b    $8D, $00, $E0, $4A, $8D, $00, $E0, $60


; === .SEGMENT "BANK_06_VEC" ===



; Unknown block
    dc.b    $84, $E4, $50, $BF, $F0, $BF


;==============================================================================
; Import stubs (T2: defined locally so the file assembles standalone)
;==============================================================================
    even
TableJump:
    rts

