/* Auto-generated by tools/extract_frontend.py - do not edit. */
const unsigned long nes_frontend_save_size = 12UL;
const unsigned char nes_frontend_save[12] = {
    0x50, 0x52, 0x54, 0x06, 0x06, 0x06, 0x38, 0x40, 0x48, 0x06, 0x06, 0x06,
};
