/* Auto-generated by tools/levelinfo_start_rooms_gen.py - do not edit.
 *
 * Data source: RoomRom/data/uw_level{N}_quest{Q}_rooms.json
 *              (start_room_id field).
 *
 * The warp coordinator looks up the destination room for a (level, quest)
 * pair through this table. Slice 1 (Task 5.4) emits only L1Q1 by design;
 * see tools/levelinfo_start_rooms_gen.py SLICE_1_ENABLED for the policy.
 */

#ifndef ROOMROM_LEVELINFO_START_ROOMS_H
#define ROOMROM_LEVELINFO_START_ROOMS_H

struct levelinfo_start_room {
    unsigned char level;
    unsigned char quest;
    unsigned char start_room_id;
};

extern const struct levelinfo_start_room levelinfo_start_rooms[];
extern const unsigned char levelinfo_start_rooms_count;

/* Look up the canonical UW start room for (level, quest).
 * Returns 1 on hit and writes *out_room_id; returns 0 on manifest miss
 * and leaves *out_room_id unchanged. level == 0 (overworld) is always
 * a manifest miss. */
unsigned char levelinfo_start_room_for(unsigned char level,
                                       unsigned char quest,
                                       unsigned char *out_room_id);

#endif /* ROOMROM_LEVELINFO_START_ROOMS_H */
