/* Auto-generated by tools/uw_pushblock_meta_gen.py - do not edit. */

#include "uw_l1q1_pushblocks.h"

const struct uw_pushblock_meta uw_l1q1_pushblocks[] = {
    { 1u, 1u, 0x22u, 6u, 5u, 0x0Fu, 1u },  /* L1Q1 R$22 */
    { 1u, 1u, 0x36u, 3u, 5u, 0x0Fu, 0u },  /* L1Q1 R$36 */
    { 1u, 1u, 0x42u, 7u, 5u, 0x0Fu, 0u },  /* L1Q1 R$42 */
    { 1u, 1u, 0x43u, 7u, 5u, 0x0Fu, 0u },  /* L1Q1 R$43 */
    { 1u, 1u, 0x45u, 3u, 5u, 0x0Fu, 0u },  /* L1Q1 R$45 */
    { 1u, 1u, 0x52u, 7u, 5u, 0x0Fu, 0u },  /* L1Q1 R$52 */
    { 1u, 1u, 0x63u, 7u, 5u, 0x0Fu, 0u },  /* L1Q1 R$63 */
    { 1u, 1u, 0x74u, 4u, 5u, 0x0Fu, 0u },  /* L1Q1 R$74 */
};

const unsigned char uw_l1q1_pushblocks_count =
    (unsigned char)(sizeof(uw_l1q1_pushblocks) /
                    sizeof(uw_l1q1_pushblocks[0]));
