/* Auto-generated by tools/uw_expected_doors_gen.py - do not edit.
 *
 * Expected door types per L1Q1 room, decoded from data/rooms/dungeons.c
 * LevelBlockUW1Q1 attrs A/B per NES Z_05.asm:FindDoorAttrByDoorBit
 * (line 4520). Cross-checked against RoomRom/tools/uw_reachability.py
 * at gen time.
 *
 * Door direction indices: E=0 W=1 S=2 N=3 (matches DOOR_DIR_* in
 * RoomRom/src/uw_door_state.h).
 *
 * Door type values: 0=OPEN 1=WALL 2=FALSE 3=FALSE2 4=BOMBABLE 5=KEY
 * 6=KEY2 7=SHUTTER (matches DOOR_TYPE_*).
 *
 * `reachable` flag: 1 = combat-free reachable in slice-1; 0 = requires
 * combat to enter (boss room, triforce room).
 */

#ifndef ROOMROM_UW_L1Q1_EXPECTED_DOORS_H
#define ROOMROM_UW_L1Q1_EXPECTED_DOORS_H

struct uw_expected_door_row {
    unsigned char room_id;
    unsigned char door_type[4];   /* DOOR_DIR_E / W / S / N */
    unsigned char reachable;
};

extern const struct uw_expected_door_row uw_l1q1_expected_doors[];
extern const unsigned char uw_l1q1_expected_doors_count;

#endif /* ROOMROM_UW_L1Q1_EXPECTED_DOORS_H */
