/* Auto-generated by tools/uw_cellar_pairs_gen.py - do not edit. */

#include "uw_l1q1_cellar_pairs.h"

const struct uw_cellar_pair uw_l1q1_cellar_pairs[] = {
    { 1u, 1u, 0x22u, 0x7Fu },  /* L1Q1 */
};

const unsigned char uw_l1q1_cellar_pairs_count =
    (unsigned char)(sizeof(uw_l1q1_cellar_pairs) /
                    sizeof(uw_l1q1_cellar_pairs[0]));
