/* Auto-generated by tools/uw_cellar_pairs_gen.py - do not edit.
 *
 * UW cellar pairs for slice-1 (L1Q1). Each row maps a UW source room
 * containing a stair tile to the cellar reached via that stair.
 *
 * NES rule: cellar = entry in LevelInfoUW{N}.CellarRoomIdArray;
 *           source = LevelBlockAttrsA[cellar] OR AttrsB[cellar].
 *           Per Z_05.asm:CheckWarps UW branch (line 7264-7282).
 *
 * Cross-checked at gen time vs RoomRom/tools/uw_reachability.py
 * cellar_targets manifest path; mismatch fails build.
 */

#ifndef ROOMROM_UW_L1Q1_CELLAR_PAIRS_H
#define ROOMROM_UW_L1Q1_CELLAR_PAIRS_H

struct uw_cellar_pair {
    unsigned char level;
    unsigned char quest;
    unsigned char source_room_id;
    unsigned char cellar_room_id;
};

extern const struct uw_cellar_pair uw_l1q1_cellar_pairs[];
extern const unsigned char uw_l1q1_cellar_pairs_count;
extern const unsigned char uw_cellar_for_source_lookup[10][3][128];
extern const unsigned char uw_cellar_source_for_cellar_lookup[10][3][128];
extern const unsigned char uw_room_is_cellar_lookup[10][3][128];

/* Lookup helpers — implemented in uw_cellar_meta.c. */

#endif /* ROOMROM_UW_L1Q1_CELLAR_PAIRS_H */
