/* Auto-generated by tools/uw_pushblock_meta_gen.py - do not edit.
 *
 * UW push-block manifest for slice-1 (L1Q1). Each row maps a UW room
 * containing a pushable block to the metatile coord of that block.
 *
 * NES rule (Z_05.asm:FindAndCreatePushBlockObject lines 5461-5514):
 *   block = first $B0 tile found scanning BG row 10 left-to-right
 *           (cols 4..26).
 *   Other $B0 occurrences in the same room are static decorative
 *   wall tiles, NOT BlockObj.
 *
 * `allowed_dirs = $0F` because NES UpdateBlock0Idle derives push
 * direction from Link's relative position (Z_04.asm:632-685); any
 * side Link approaches from is valid.
 *
 * `trigger_kind`:
 *   0 = collision-only (push only opens path through block's metatile)
 *   1 = stair (CheckSecretTriggerBlockStairs, Z_05.asm:2471)
 *   2 = door  (CheckSecretTriggerBlockDoor,  Z_05.asm:2463)
 */

#ifndef ROOMROM_UW_L1Q1_PUSHBLOCKS_H
#define ROOMROM_UW_L1Q1_PUSHBLOCKS_H

struct uw_pushblock_meta {
    unsigned char level;
    unsigned char quest;
    unsigned char room_id;
    unsigned char block_col_mt;   /* 0..15 */
    unsigned char block_row_mt;   /* 0..10 */
    unsigned char allowed_dirs;   /* bit0=N bit1=S bit2=W bit3=E */
    unsigned char trigger_kind;   /* 0=collision 1=stair 2=door */
};

extern const struct uw_pushblock_meta uw_l1q1_pushblocks[];
extern const unsigned char uw_l1q1_pushblocks_count;

#endif /* ROOMROM_UW_L1Q1_PUSHBLOCKS_H */
