/* Auto-generated by tools/uw_expected_doors_gen.py - do not edit. */

#include "uw_l1q1_expected_doors.h"

const struct uw_expected_door_row uw_l1q1_expected_doors[] = {
    { 0x22u, { 5u, 1u, 1u, 1u }, 1u },  /* E=KEY W=WALL S=WALL N=WALL */
    { 0x23u, { 1u, 5u, 5u, 1u }, 1u },  /* E=WALL W=KEY S=KEY N=WALL */
    { 0x33u, { 1u, 1u, 0u, 5u }, 1u },  /* E=WALL W=WALL S=OPEN N=KEY */
    { 0x35u, { 7u, 1u, 5u, 1u }, 0u },  /* E=SHUTTER W=WALL S=KEY N=WALL */
    { 0x36u, { 1u, 0u, 1u, 1u }, 0u },  /* E=WALL W=OPEN S=WALL N=WALL */
    { 0x41u, { 0u, 1u, 1u, 1u }, 1u },  /* E=OPEN W=WALL S=WALL N=WALL */
    { 0x42u, { 0u, 7u, 5u, 1u }, 1u },  /* E=OPEN W=SHUTTER S=KEY N=WALL */
    { 0x43u, { 5u, 0u, 4u, 0u }, 1u },  /* E=KEY W=OPEN S=BOMBABLE N=OPEN */
    { 0x44u, { 0u, 5u, 4u, 1u }, 1u },  /* E=OPEN W=KEY S=BOMBABLE N=WALL */
    { 0x45u, { 1u, 0u, 1u, 5u }, 1u },  /* E=WALL W=OPEN S=WALL N=KEY */
    { 0x52u, { 7u, 1u, 1u, 5u }, 1u },  /* E=SHUTTER W=WALL S=WALL N=KEY */
    { 0x53u, { 0u, 0u, 0u, 4u }, 1u },  /* E=OPEN W=OPEN S=OPEN N=BOMBABLE */
    { 0x54u, { 1u, 0u, 1u, 4u }, 1u },  /* E=WALL W=OPEN S=WALL N=BOMBABLE */
    { 0x63u, { 1u, 1u, 5u, 0u }, 1u },  /* E=WALL W=WALL S=KEY N=OPEN */
    { 0x72u, { 0u, 1u, 1u, 1u }, 1u },  /* E=OPEN W=WALL S=WALL N=WALL */
    { 0x73u, { 0u, 0u, 0u, 5u }, 1u },  /* E=OPEN W=OPEN S=OPEN N=KEY */
    { 0x74u, { 1u, 0u, 1u, 1u }, 1u },  /* E=WALL W=OPEN S=WALL N=WALL */
};

const unsigned char uw_l1q1_expected_doors_count =
    (unsigned char)(sizeof(uw_l1q1_expected_doors) /
                    sizeof(uw_l1q1_expected_doors[0]));
