#!/usr/bin/env python3
"""Verify RoomRom/data/MANIFEST.sha256 matches the current RoomRom/data tree.

Mirror of tools/probes/check_data_manifest.py, scoped to RoomRom-only data
inputs. Per Codex parity audit (debate roomrom-default-rule, 2026-05-04
LIST 2): RoomRom-side data files (atlas_master.json, item_chr_manifest.json,
rom_inputs.lock, all 36 uw_level{1..9}_quest{1,2}_*.json, etc.) had no
SHA/provenance gate. Stale data could land silently. This closes that.

Usage:
    python tools/probes/check_roomrom_data_manifest.py            # verify
    python tools/probes/check_roomrom_data_manifest.py --gen      # write manifest

Run from the current Debug build/tooling path when RoomRom data changes.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ROOMROM_DATA_DIR = REPO_ROOT / "RoomRom" / "data"
MANIFEST_PATH = ROOMROM_DATA_DIR / "MANIFEST.sha256"


def hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def parse_manifest() -> dict[str, str]:
    out: dict[str, str] = {}
    if not MANIFEST_PATH.exists():
        return out
    for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            continue
        sha, rel = parts
        out[rel.strip()] = sha.strip()
    return out


def walk_data() -> dict[str, str]:
    out: dict[str, str] = {}
    for path in sorted(ROOMROM_DATA_DIR.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOMROM_DATA_DIR).as_posix()
        if rel == "MANIFEST.sha256":
            continue
        if path.name == ".gitkeep":
            continue
        out[rel] = hash_file(path)
    return out


def write_manifest(actual: dict[str, str]) -> None:
    lines = [
        "# RoomRom/data/MANIFEST.sha256",
        "# Generated by tools/probes/check_roomrom_data_manifest.py --gen",
        "# Per Codex parity audit (debate roomrom-default-rule, 2026-05-04 LIST 2).",
        "# Format: <sha256>  <relative-path>",
        "",
    ]
    for rel in sorted(actual):
        lines.append(f"{actual[rel]}  {rel}")
    lines.append("")
    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gen", action="store_true",
                    help="write MANIFEST.sha256 from current state")
    args = ap.parse_args(argv[1:])

    actual = walk_data()

    if args.gen:
        write_manifest(actual)
        print(f"[check_roomrom_data_manifest] wrote {len(actual)} entries -> "
              f"{MANIFEST_PATH.relative_to(REPO_ROOT)}")
        return 0

    expected = parse_manifest()

    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    mismatched = sorted(
        rel for rel in (set(expected) & set(actual))
        if expected[rel] != actual[rel]
    )

    if not expected:
        print("[check_roomrom_data_manifest] no manifest yet; pass "
              "(run with --gen to bootstrap)")
        return 0

    if not (missing or extra or mismatched):
        print(f"[check_roomrom_data_manifest] OK ({len(expected)} files match)")
        return 0

    if missing:
        print(f"[check_roomrom_data_manifest] MISSING ({len(missing)}):", file=sys.stderr)
        for rel in missing[:20]:
            print(f"  {rel}", file=sys.stderr)
        if len(missing) > 20:
            print(f"  ...+{len(missing) - 20}", file=sys.stderr)
    if extra:
        print(f"[check_roomrom_data_manifest] EXTRA ({len(extra)}):", file=sys.stderr)
        for rel in extra[:20]:
            print(f"  {rel}", file=sys.stderr)
        if len(extra) > 20:
            print(f"  ...+{len(extra) - 20}", file=sys.stderr)
    if mismatched:
        print(f"[check_roomrom_data_manifest] MISMATCH ({len(mismatched)}):", file=sys.stderr)
        for rel in mismatched[:20]:
            print(f"  {rel}", file=sys.stderr)
            print(f"    expected: {expected[rel]}", file=sys.stderr)
            print(f"    actual:   {actual[rel]}", file=sys.stderr)
        if len(mismatched) > 20:
            print(f"  ...+{len(mismatched) - 20}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
