"""chr_cycle_diff.py — pixel-diff NES test ROM vs Genesis debug scene
across all 256 (bank, sub_pal, sprite_page, 8x16) states.

Reads:
  C:/tmp/chr_cycle_nes/bank{B}_sub{S}_page{P}_8x16{M}.png  (NES side)
  C:/tmp/chr_cycle_gen/bank{B}_sub{S}_page{P}_8x16{M}.png  (Genesis side)

Both ROMs render:
  - BG: 16x16 tile grid in top-left (rows 0-15, cols 0-15; pixel area 0..127 x 0..127)
  - SPR: 8x8 sprite grid below BG (y=$80..$F0 = pixel 128..240, x=$00..$70 = pixel 0..119)

Per state:
  - Resize both PNGs to canonical NES 256x240 if needed (BizHawk may export Genesis as 320x224)
  - For each 8x8 cell in BG grid (16*16 = 256 cells), pixel-compare
  - For each 16x16 sprite slot (8*8 = 64 slots), pixel-compare
  - Tag mismatches with (bank, sub_pal, tile_id, slot_or_cell)

Output: docs/atlas/chr_cycle_diff.md summarising findings.
"""
from __future__ import annotations
import pathlib
import sys

from PIL import Image


REPO = pathlib.Path(__file__).resolve().parents[2]
NES_DIR = pathlib.Path("C:/tmp/chr_cycle_nes")
GEN_DIR = pathlib.Path("C:/tmp/chr_cycle_gen")
OUT_MD  = REPO / "docs" / "atlas" / "chr_cycle_diff.md"


def state_name(bank, sub_pal, page, mode):
    return f"bank{bank}_sub{sub_pal}_page{page}_8x16{mode}"


def pixel_diff(img_a: Image.Image, img_b: Image.Image,
               x0: int, y0: int, w: int, h: int) -> int:
    """Count pixels differing between img_a and img_b in [x0..x0+w, y0..y0+h]."""
    pa = img_a.load()
    pb = img_b.load()
    diff = 0
    for y in range(y0, y0 + h):
        for x in range(x0, x0 + w):
            if pa[x, y] != pb[x, y]:
                diff += 1
    return diff


def diff_state(bank, sub_pal, page, mode):
    """Returns dict with per-cell diff counts."""
    nes_path = NES_DIR / f"{state_name(bank, sub_pal, page, mode)}.png"
    gen_path = GEN_DIR / f"{state_name(bank, sub_pal, page, mode)}.png"
    if not nes_path.exists() or not gen_path.exists():
        return {"missing": True}

    nes_img = Image.open(nes_path).convert("RGB")
    gen_img = Image.open(gen_path).convert("RGB")

    # Resize Genesis to NES canonical 256x240 (NES native res).
    # Genesis emulator may export 320x224 or 256x224 depending on H32/H40.
    if gen_img.size != nes_img.size:
        gen_img = gen_img.resize(nes_img.size, Image.NEAREST)

    # BG cells: 16x16 tile grid, each tile is 8x8 px, region 0..127 x 0..127
    bg_diffs = []  # list of (tile_id, diff_count)
    for row in range(16):
        for col in range(16):
            tile_id = row * 16 + col
            d = pixel_diff(nes_img, gen_img, col * 8, row * 8, 8, 8)
            if d > 0:
                bg_diffs.append((tile_id, d))

    # SPR slots: 8x8 sprite grid, each 16x16 pixel cells (with padding)
    # at y=128..240 (8 rows of 14 px), x=0..127 (8 cols of 16 px)
    # In 8x8 sprite mode, each sprite is 8x8 in a 16-wide cell. Compare 8x8 region.
    spr_diffs = []
    for row in range(8):
        for col in range(8):
            slot = row * 8 + col
            # Sprite top-left in grid cell (col*16, 128+row*16) for 16-px cells
            d = pixel_diff(nes_img, gen_img, col * 16, 128 + row * 16, 8, 8)
            if d > 0:
                spr_diffs.append((slot, d))

    return {
        "bg_diffs": bg_diffs,
        "spr_diffs": spr_diffs,
        "missing": False,
    }


def main():
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)

    states = []
    for bank in range(8):
        for sub_pal in range(4):
            for page in range(4):
                for mode in range(2):
                    states.append((bank, sub_pal, page, mode))

    total = len(states)
    print(f"diffing {total} states ({len(states)} captures per side)")

    lines = ["# CHR Cycle Diff — NES Test ROM vs Genesis Debug.md\n\n"]
    lines.append(f"Generated by `tools/probes/chr_cycle_diff.py`. "
                 f"256 states ({total} captured) per side. Pixel-diff of "
                 f"16x16 BG cells + 8x8 SPR grid per state.\n\n")
    lines.append("## Summary table\n\n")
    lines.append("| Bank | Sub | Page | 8x16 | BG diffs | SPR diffs |\n")
    lines.append("|---|---|---|---|---|---|\n")

    total_bg = 0
    total_spr = 0
    missing = 0
    by_bg_tile = {}   # (bank, sub_pal, tile_id) -> total diff pixels
    by_spr_slot = {}  # (bank, page, slot) -> total diff pixels

    for bank, sub_pal, page, mode in states:
        r = diff_state(bank, sub_pal, page, mode)
        if r.get("missing"):
            lines.append(f"| {bank} | {sub_pal} | {page} | {mode} | (missing capture) | — |\n")
            missing += 1
            continue
        nbg = len(r["bg_diffs"])
        nspr = len(r["spr_diffs"])
        total_bg += nbg
        total_spr += nspr
        lines.append(f"| {bank} | {sub_pal} | {page} | {mode} | {nbg} cells | {nspr} slots |\n")
        for tile_id, d in r["bg_diffs"]:
            k = (bank, sub_pal, tile_id)
            by_bg_tile[k] = by_bg_tile.get(k, 0) + d
        for slot, d in r["spr_diffs"]:
            k = (bank, page, slot)
            by_spr_slot[k] = by_spr_slot.get(k, 0) + d

    lines.append(f"\n**Totals:** {total_bg} BG cell-states, {total_spr} SPR slot-states diff; "
                 f"{missing} missing captures.\n\n")

    if by_bg_tile:
        lines.append("## Top 30 worst BG (bank, sub_pal, tile_id) mismatches\n\n")
        lines.append("Sorted by total diff pixels across modes/pages.\n\n")
        ranked = sorted(by_bg_tile.items(), key=lambda x: -x[1])[:30]
        lines.append("| Bank | Sub | tile_id | Diff pixels |\n|---|---|---|---|\n")
        for (bank, sub, tile), d in ranked:
            lines.append(f"| {bank} | {sub} | ${tile:02X} | {d} |\n")
        lines.append("\n")

    if by_spr_slot:
        lines.append("## Top 30 worst SPR (bank, page, slot) mismatches\n\n")
        ranked = sorted(by_spr_slot.items(), key=lambda x: -x[1])[:30]
        lines.append("| Bank | Page | Slot | Diff pixels |\n|---|---|---|---|\n")
        for (bank, page, slot), d in ranked:
            lines.append(f"| {bank} | {page} | {slot} | {d} |\n")
        lines.append("\n")

    OUT_MD.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT_MD}")
    print(f"  total BG cell-state diffs: {total_bg}")
    print(f"  total SPR slot-state diffs: {total_spr}")
    print(f"  missing captures: {missing}")


if __name__ == "__main__":
    sys.exit(main())
