"""Classify every src/ file by role, emit docs/audit/file_classification.md."""

from __future__ import annotations

import sys
from pathlib import Path

from _common import SRC, write_audit, relative_to_repo


CATEGORIES = [
    "owned_c",
    "owned_c_frontend",
    "generated_data",
    "transpile_adapter",
    "transpiled_asm",
    "shim_asm",
    "platform_asm",
    "compat_wrapper",
    "header",
    "cruft",
]

FRONTEND_PREFIXES = ("src/intro_", "src/fs_", "src/frontend_")
COMPAT_NAMES = {"src/c_move_object.c", "src/c_wanderer.c"}
SHIM_NAMES = {"src/nes_io.asm", "src/c_shims.asm"}
PLATFORM_ASM_NAMES = {"src/genesis_shell.asm", "src/audio_driver.asm"}


def classify(rel: str) -> str:
    rel_norm = rel.replace("\\", "/")
    if rel_norm.endswith(".bak") or " - Copy" in rel_norm or rel_norm.endswith(".txt"):
        return "cruft"
    if rel_norm in COMPAT_NAMES:
        return "compat_wrapper"
    if rel_norm in SHIM_NAMES:
        return "shim_asm"
    if rel_norm in PLATFORM_ASM_NAMES:
        return "platform_asm"
    if rel_norm.startswith("src/zelda_translated/"):
        return "transpiled_asm"
    if rel_norm.startswith("src/gen/"):
        if "/z_" in rel_norm and rel_norm.endswith(".c"):
            return "transpile_adapter"
        return "generated_data"
    if rel_norm.endswith(".h"):
        return "header"
    if rel_norm.endswith(".c"):
        if any(rel_norm.startswith(p) for p in FRONTEND_PREFIXES):
            return "owned_c_frontend"
        return "owned_c"
    if rel_norm.endswith((".asm", ".inc")):
        return "cruft"
    return "cruft"


def main() -> int:
    buckets: dict[str, list[str]] = {c: [] for c in CATEGORIES}

    for path in sorted(SRC.rglob("*")):
        if not path.is_file():
            continue
        rel = relative_to_repo(path)
        cat = classify(rel)
        buckets.setdefault(cat, []).append(rel)

    lines: list[str] = ["# File Classification", ""]
    lines.append("Generated by `tools/probes/classify_files.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---|")
    for cat in CATEGORIES:
        lines.append(f"| `{cat}` | {len(buckets.get(cat, []))} |")
    lines.append("")

    for cat in CATEGORIES:
        files = buckets.get(cat, [])
        lines.append(f"## `{cat}` ({len(files)})")
        lines.append("")
        if not files:
            lines.append("_(none)_")
            lines.append("")
            continue
        for rel in files:
            lines.append(f"- `{rel}`")
        lines.append("")

    out = write_audit("file_classification.md", "\n".join(lines) + "\n")
    print(f"wrote {out}")
    for cat in CATEGORIES:
        print(f"  {cat:24s} {len(buckets.get(cat, []))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
