# tools/probes/scan_build_order.py
"""Generate docs/audit/build_order.md by parsing build.bat.

Extracts compile-order and link-order from the for-loops and link command in
build.bat. Output is a markdown report listing:

  - Stage 2a: C compilation order
  - Stage 2b: ASM assembly order
  - Stage 2c: link order
  - Stage 3:  objcopy / strip
"""

from __future__ import annotations

import re
import sys

from _common import REPO_ROOT, write_audit


FOR_LOOP = re.compile(r"^\s*for\s+%%(\w)\s+in\s+\(([^)]*)\)\s+do\b", re.IGNORECASE)
LINK_LINE = re.compile(r'^\s*"%M68K_LD%"\s+-', re.IGNORECASE)


def main() -> int:
    bat = (REPO_ROOT / "build.bat").read_text(encoding="utf-8", errors="replace")
    lines = bat.splitlines()

    loops: list[tuple[int, str, str]] = []  # (lineno, var, items_raw)
    for i, line in enumerate(lines, start=1):
        m = FOR_LOOP.match(line)
        if m:
            loops.append((i, m.group(1), m.group(2).strip()))

    link_lines = [(i, l.strip()) for i, l in enumerate(lines, start=1) if LINK_LINE.search(l)]

    out: list[str] = ["# Build Order Report", ""]
    out.append("Generated by `tools/probes/scan_build_order.py` from `build.bat`.")
    out.append("")
    out.append("## For-loops in build.bat")
    out.append("")
    if not loops:
        out.append("_No for-loops found. Inspect build.bat directly._")
    for lineno, var, items in loops:
        out.append(f"### `for %%{var}` at line {lineno}")
        out.append("")
        out.append("Items (in declaration order):")
        out.append("")
        for tok in items.split():
            out.append(f"- `{tok}`")
        out.append("")

    out.append("## Link command(s)")
    out.append("")
    if not link_lines:
        out.append("_No `m68k-elf-ld` invocations found._")
    for lineno, line in link_lines:
        out.append(f"- line {lineno}: `{line}`")
    out.append("")

    written = write_audit("build_order.md", "\n".join(out) + "\n")
    print(f"wrote {written}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
