# tools/probes/scan_legacy_callers.py
"""Generate docs/audit/legacy_callers.md.

Reports every call site of the legacy shim and transpiled-bank symbols that
S1+ stages must drain or replace:

  _ppu_*, _oam_*, _apu_*, _ctrl_*, _mmc1_*
  z00_*, z01_*, z02_*, z03_*, z04_*, z05_*, z06_*, z07_*

Output is grouped by symbol family with file:line references.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

from _common import SRC, write_audit, relative_to_repo

FAMILIES: list[tuple[str, re.Pattern]] = [
    ("_ppu_*",   re.compile(r"\b_ppu_[A-Za-z0-9_]+")),
    ("_oam_*",   re.compile(r"\b_oam_[A-Za-z0-9_]+")),
    ("_apu_*",   re.compile(r"\b_apu_[A-Za-z0-9_]+")),
    ("_ctrl_*",  re.compile(r"\b_ctrl_[A-Za-z0-9_]+")),
    ("_mmc1_*",  re.compile(r"\b_mmc1_[A-Za-z0-9_]+")),
    ("z01_*",    re.compile(r"\bz01_[A-Za-z0-9_]+")),
    ("z02_*",    re.compile(r"\bz02_[A-Za-z0-9_]+")),
    ("z03_*",    re.compile(r"\bz03_[A-Za-z0-9_]+")),
    ("z04_*",    re.compile(r"\bz04_[A-Za-z0-9_]+")),
    ("z05_*",    re.compile(r"\bz05_[A-Za-z0-9_]+")),
    ("z06_*",    re.compile(r"\bz06_[A-Za-z0-9_]+")),
    ("z07_*",    re.compile(r"\bz07_[A-Za-z0-9_]+")),
]

# Skip files that are themselves the source of truth for these symbols.
SKIP_FILES = {
    "src/zelda_translated",        # transpiled bank source
    "src/gen/z_",                  # transpile adapters
    "src/nes_io.asm",              # shim definitions
    "src/c_shims.asm",             # shim definitions
    "src/genesis_shell.asm",       # boot/IO definitions
}


def is_skipped(rel: str) -> bool:
    return any(rel.startswith(s) or s in rel for s in SKIP_FILES)


def main() -> int:
    hits: dict[str, list[tuple[str, int, str, str]]] = defaultdict(list)

    for path in sorted(SRC.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix not in (".c", ".h", ".asm", ".inc"):
            continue
        rel = relative_to_repo(path)
        if is_skipped(rel):
            continue

        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        for lineno, line in enumerate(text.splitlines(), start=1):
            stripped = line.strip()
            if not stripped or stripped.startswith(("/*", "*", "//", ";", "#")):
                # Still scan — comments mentioning symbols are also signal.
                pass
            for family, pat in FAMILIES:
                for m in pat.finditer(line):
                    hits[family].append((rel, lineno, m.group(0), stripped[:120]))

    lines: list[str] = ["# Legacy Symbol Caller Report", ""]
    lines.append("Generated by `tools/probes/scan_legacy_callers.py`. Regenerate after every drain.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Family | Call sites |")
    lines.append("|---|---|")
    for family, _ in FAMILIES:
        lines.append(f"| `{family}` | {len(hits[family])} |")
    lines.append("")

    for family, _ in FAMILIES:
        lines.append(f"## `{family}`")
        lines.append("")
        if not hits[family]:
            lines.append("_No callers._")
            lines.append("")
            continue
        for rel, lineno, sym, snippet in hits[family]:
            lines.append(f"- `{rel}:{lineno}` — `{sym}` — `{snippet}`")
        lines.append("")

    out = write_audit("legacy_callers.md", "\n".join(lines) + "\n")
    print(f"wrote {out}")
    print(f"total call sites: {sum(len(v) for v in hits.values())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
