# tools/probes/scan_frontend_deps.py
"""Generate docs/audit/frontend_deps.md.

For every file under src/ whose name matches frontend prefixes (intro_*, fs_*,
frontend_*, intro/, fs/), report:

  - all #include directives
  - all extern function/data declarations consumed
  - all VDP-direct register writes (VDP_DATA / VDP_CTRL_WORD / 0xC00000)

This is the input to S1's frontend re-pointing onto the new render API.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from _common import SRC, write_audit, relative_to_repo

FRONTEND_NAME = re.compile(r"^(intro|fs|frontend)_", re.IGNORECASE)

INCLUDE = re.compile(r'^\s*#\s*include\s+["<]([^">]+)[">]')
EXTERN  = re.compile(r"^\s*extern\s+([^;]+);")
VDP_DIRECT = re.compile(r"VDP_(DATA|CTRL)_WORD|0x00C0000[0-9A-F]|0xC0000[0-9A-F]")


def is_frontend(path: Path) -> bool:
    return bool(FRONTEND_NAME.match(path.name))


def main() -> int:
    lines: list[str] = ["# Frontend Dependency Report", ""]
    lines.append("Generated by `tools/probes/scan_frontend_deps.py`.")
    lines.append("")
    lines.append("Frontend = files matching `^(intro|fs|frontend)_` under `src/`.")
    lines.append("")

    files = [p for p in sorted(SRC.rglob("*")) if p.is_file() and is_frontend(p) and p.suffix in (".c", ".h")]

    for path in files:
        rel = relative_to_repo(path)
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        includes: list[str] = []
        externs: list[str] = []
        vdp_direct: list[tuple[int, str]] = []

        for lineno, line in enumerate(text.splitlines(), start=1):
            m = INCLUDE.match(line)
            if m:
                includes.append(m.group(1))
                continue
            m = EXTERN.match(line)
            if m:
                externs.append(m.group(1).strip())
                continue
            if VDP_DIRECT.search(line):
                vdp_direct.append((lineno, line.strip()[:120]))

        lines.append(f"## `{rel}`")
        lines.append("")
        lines.append("**Includes:**")
        if includes:
            for inc in includes:
                lines.append(f"- `{inc}`")
        else:
            lines.append("_(none)_")
        lines.append("")
        lines.append("**Externs declared:**")
        if externs:
            for ext in externs:
                lines.append(f"- `{ext}`")
        else:
            lines.append("_(none)_")
        lines.append("")
        lines.append("**VDP-direct register access:**")
        if vdp_direct:
            for lineno, snippet in vdp_direct:
                lines.append(f"- `{rel}:{lineno}` — `{snippet}`")
        else:
            lines.append("_(none)_")
        lines.append("")

    out = write_audit("frontend_deps.md", "\n".join(lines) + "\n")
    print(f"wrote {out} ({len(files)} frontend files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
