# tools/probes/scan_redux_touchpoints.py
"""Generate docs/audit/redux_touchpoints.md.

Reports every existing reference to Zelda-Redux behavior in the FINAL TRY
codebase: comments mentioning Redux, palette overrides borrowed from Redux,
FS extensions (PLAYERS / OPTIONS rows), silent-FS handling, and any other
deviation from vanilla NES Zelda 1 that the rewrite must preserve.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from _common import SRC, write_audit, relative_to_repo

REDUX_PAT = re.compile(r"redux", re.IGNORECASE)
OPTIONS_PAT = re.compile(r"\bOPTIONS\b|\bopt_|FS_OPTIONS")
PLAYERS_PAT = re.compile(r"\bPLAYERS\b")


def main() -> int:
    hits: list[tuple[str, int, str, str]] = []  # (rel, lineno, tag, snippet)

    for path in sorted(SRC.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix not in (".c", ".h", ".asm", ".inc"):
            continue
        rel = relative_to_repo(path)
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            tags: list[str] = []
            if REDUX_PAT.search(line):
                tags.append("Redux")
            if OPTIONS_PAT.search(line):
                tags.append("OPTIONS")
            if PLAYERS_PAT.search(line):
                tags.append("PLAYERS")
            if not tags:
                continue
            hits.append((rel, lineno, ",".join(tags), line.strip()[:160]))

    lines: list[str] = ["# Zelda Redux Touchpoint Inventory", ""]
    lines.append("Generated by `tools/probes/scan_redux_touchpoints.py`.")
    lines.append("")
    lines.append("Every site below is preserved (or re-implemented natively) by the rewrite.")
    lines.append("S8a wires these into the OPTIONS subsystem (`src/game/options/`).")
    lines.append("")
    lines.append(f"Total touchpoints: **{len(hits)}**")
    lines.append("")
    lines.append("| File | Line | Tags | Snippet |")
    lines.append("|---|---|---|---|")
    for rel, lineno, tags, snippet in hits:
        safe = snippet.replace("|", "\\|")
        lines.append(f"| `{rel}` | {lineno} | {tags} | `{safe}` |")

    out = write_audit("redux_touchpoints.md", "\n".join(lines) + "\n")
    print(f"wrote {out} ({len(hits)} touchpoints)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
