#!/usr/bin/env python3
"""Regenerate the Q1 LevelBlock+LevelInfo regions of data/rooms/dungeons.c
from LIVE NES SRAM dumps (tools/parity/cave_golden ... C:/tmp/nes_levelsram/).

WHY: the reference dat/LevelBlock*.dat + dat/LevelInfo*.dat do NOT match what
NES loads into SRAM (NES applies load transforms the extraction never captured
— byte-proven: dat LBA_C[$63]=$2A but live NES SRAM=$FD; dat FoeCounts at
offset 32, NES SRAM at $6BA2/offset 36). extract_rooms.py built rooms_dungeons[]
1:1 from those dats, so dungeon enemy templates (LBA C/D) + FoeCounts are wrong
-> Gen dungeon rooms spawn the wrong enemy type + count. This post-processor
overrides those regions with the live-loaded tables so the install (which
copies the blob 1:1 into NES SRAM) reproduces NES exactly. Re-runnable.

Blob layout (data/rooms/MANIFEST.json + src/game/world/level_info_install.c):
  [0..767]      LevelBlockUW1Q1  (shared L1-L6 Q1)
  [768..1535]   LevelBlockUW2Q1  (shared L7-L9 Q1)
  [1536..2303]  LevelBlockUW1Q2  (NOT touched here — Phase 7)
  [2304..3071]  LevelBlockUW2Q2  (NOT touched here — Phase 7)
  [3072+(lvl-1)*256 .. +256]  LevelInfoUW<lvl>  (quest-independent slot; Q1)

SRAM dump = 1024 bytes per level: [0..767]=$687E LevelBlockAttrs A-F,
[768..1023]=$6B7E LevelInfo. StartRoomId (LevelInfo offset 47) is clobbered
to the OW save room by the forced probe entry -> fixed here from the manifest.
"""
import re, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
DUN_C = ROOT / "data" / "rooms" / "dungeons.c"
SRAM  = pathlib.Path(r"C:\tmp\nes_levelsram")
MANI  = ROOT / "RoomRom" / "data"

LEVELINFO_BASE = 3072
LEVELINFO_STRIDE = 256
BLOCK_BYTES = 768


def load_dump(lvl, quest=1):
    p = SRAM / f"nes_sram_L{lvl}Q{quest}.bin"
    return bytearray(p.read_bytes())


def manifest_start_room(lvl, quest=1):
    d = json.loads((MANI / f"uw_level{lvl}_quest{quest}_rooms.json").read_text())
    return int(d["start_room_id"], 16)


def parse_blob(text):
    body = text[text.find("{") + 1: text.rfind("}")]
    return [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+|\d+", body)]


def emit_c(blob):
    lines = ["/* Auto-generated by tools/extract_rooms.py - do not edit. */",
             "/* Q1 LevelBlock+LevelInfo regions regenerated from LIVE NES SRAM by",
             " * tools/parity/cave_golden/regen_dungeon_blob_from_sram.py (dat<->SRAM",
             " * transform: reference dats do not match NES-loaded tables). */",
             f"const unsigned long rooms_dungeons_size = {len(blob)}UL;",
             f"const unsigned char rooms_dungeons[{len(blob)}] = {{"]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


FOECOUNTS_OFF = 36   # LevelInfo offset of FoeCounts[0..3] ($6BA2 - $6B7E)
FOECOUNTS_LEN = 4


def main():
    dumps = {lvl: load_dump(lvl) for lvl in range(1, 10)}

    # The forced mode-$10 probe entry leaves the LevelBlock (LBA A-F) clean
    # (verified: $63 ObjType byte-matches live NES) but CLOBBERS some LevelInfo
    # post-palette fields (StartRoomId offset 47 -> OW save room; BossRoomId
    # offset 62 reads $07 vs the dat-transform $35). So we trust the live dump
    # ONLY for the LevelBlock + the enemy-critical FoeCounts (offset 36-39,
    # byte-proven correct via the spawn). All other LevelInfo bytes (palette,
    # StartRoomId, BossRoomId, ...) stay as the original blob -> no regression
    # to BG palette (byte-exact) or boss-room/start-room logic.

    # Verify the shared-block invariant (L1-6 share UW1, L7-9 share UW2).
    blk_uw1 = bytes(dumps[1][0:BLOCK_BYTES])
    blk_uw2 = bytes(dumps[7][0:BLOCK_BYTES])
    for lvl in range(2, 7):
        if bytes(dumps[lvl][0:BLOCK_BYTES]) != blk_uw1:
            print(f"WARN L{lvl} block != L1 UW1 block (not shared?)")
    for lvl in (8, 9):
        if bytes(dumps[lvl][0:BLOCK_BYTES]) != blk_uw2:
            print(f"WARN L{lvl} block != L7 UW2 block (not shared?)")

    blob = parse_blob(DUN_C.read_text())
    orig = list(blob)

    # Override the UW LevelBlocks. NES PatchQ2Rooms (Z_06.asm:237) patches only
    # OVERWORLD LevelBlockAttrsB (cave/dungeon routing), NOT underworld room
    # contents -> dungeon interiors are quest-independent (byte-proven: live NES
    # UW SRAM L*Q1 == L*Q2). So both quests' blocks get the same live images:
    #   [0..767]      UW1Q1    [768..1535]   UW2Q1
    #   [1536..2303]  UW1Q2    [2304..3071]  UW2Q2
    blob[0:BLOCK_BYTES] = list(blk_uw1)
    blob[BLOCK_BYTES:2 * BLOCK_BYTES] = list(blk_uw2)
    blob[2 * BLOCK_BYTES:3 * BLOCK_BYTES] = list(blk_uw1)
    blob[3 * BLOCK_BYTES:4 * BLOCK_BYTES] = list(blk_uw2)
    # Override ONLY FoeCounts in each per-level LevelInfo slot (quest-
    # independent). The rest of LevelInfo (palette/StartRoomId/BossRoomId/...)
    # stays as the original blob to avoid regressing on the probe-clobbered
    # fields.
    for lvl in range(1, 10):
        off = LEVELINFO_BASE + (lvl - 1) * LEVELINFO_STRIDE
        src = dumps[lvl]
        blob[off + FOECOUNTS_OFF: off + FOECOUNTS_OFF + FOECOUNTS_LEN] = \
            list(src[768 + FOECOUNTS_OFF: 768 + FOECOUNTS_OFF + FOECOUNTS_LEN])

    changed = sum(1 for a, b in zip(orig, blob) if a != b)
    DUN_C.write_text(emit_c(blob))
    print(f"regen: {changed} bytes changed in {DUN_C.name} (len {len(blob)})")
    print(f"  UW1Q1 LBA_C[$63]=0x{blob[0x163]:02X} (live 0xFD) "
          f"LBA_C[$73]=0x{blob[0x173]:02X} (live 0x6A)")
    print(f"  L1 FoeCounts={[hex(blob[LEVELINFO_BASE+36+i]) for i in range(4)]} (live 03 05 06 08)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
