#!/usr/bin/env python3
"""Restore dungeon room blocks from the user's supported NES ROM.

The historical filename is retained for existing callers. Captured SRAM is no
longer an input: old captures contained Q2 blocks and replaced both quests.
Read the Q1 and Q2 pointers actually used by Z_06.asm:InitMode2_Sub0.
By default only room attributes change. --level-info restores nine LevelInfo
records; --overworld-source restores its shared LevelInfo/common prefix.
Other generated regions and existing Redux graphics are preserved.
"""
import argparse
import hashlib
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from extract_rooms import read_bank6_pointer

SUPPORTED_SHA256 = "8f72dc2e98572eb4ba7c3a902bca5f69c448fc4391837e5f8f0d4556280440ac"
BANK_SIZE = 0x4000
BLOCK_SIZE = 0x300


def room_blocks(rom: bytes) -> bytes:
    if hashlib.sha256(rom).hexdigest() != SUPPORTED_SHA256:
        raise ValueError("Unsupported NES ROM revision; source file is unchanged")
    bank = rom[16 + 6 * BANK_SIZE:16 + 7 * BANK_SIZE]

    def block(table: int, level: int) -> bytes:
        offset = table + 2 * level
        address = int.from_bytes(bank[offset:offset + 2], "little")
        start = address - 0x8000
        if not 0 <= start <= BANK_SIZE - BLOCK_SIZE:
            raise ValueError("Level block pointer outside PRG bank 6")
        return bank[start:start + BLOCK_SIZE]

    # Z_06.asm starts with 10 Q1 pointers, 10 LevelInfo pointers,
    # one common-data pointer, then 10 Q2 pointers ($8000 / $802A).
    return b"".join(block(table, level)
                    for table in (0, 0x2A) for level in (1, 7))


def regenerate(rom: bytes, source: str, level_info: bool = False) -> tuple[str, int]:
    start, end = source.index("{") + 1, source.rindex("}")
    body = source[start:end]
    tokens = list(re.finditer(r"0x[0-9a-fA-F]+|\d+", body))
    if len(tokens) < 4 * BLOCK_SIZE:
        raise ValueError("Dungeon blob is missing one or more room blocks")
    replacement = room_blocks(rom)
    if level_info:
        bank = rom[16 + 6 * BANK_SIZE:16 + 7 * BANK_SIZE]
        replacement += b"".join(read_bank6_pointer(bank, 0x14 + level * 2, 256)
                                for level in range(1, 10))
    if len(tokens) < len(replacement):
        raise ValueError("Dungeon blob missing requested LevelInfo regions")
    changed = 0
    # Preserve every byte and all formatting outside the requested regions.
    for token, value in reversed(list(zip(tokens[:len(replacement)], replacement))):
        if int(token.group(), 0) != value:
            changed += 1
            body = body[:token.start()] + f"0x{value:02x}" + body[token.end():]
    header = ("/* Auto-generated by tools/extract_rooms.py. */\n"
              "/* Room blocks restored from the user-supplied NES ROM's Q1/Q2\n"
              " * pointer tables by regen_dungeon_blob_from_sram.py. */\n")
    declaration = source.index("const unsigned long rooms_dungeons_size")
    return header + source[declaration:start] + body + source[end:], changed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--source", type=Path, default=Path("data/rooms/dungeons.c"))
    parser.add_argument("--out", type=Path)
    parser.add_argument("--level-info", action="store_true",
                        help="Also restore all nine pointer-derived LevelInfo records")
    parser.add_argument("--overworld-source", type=Path,
                        help="Also restore OW LevelInfo and common-data regions in this C blob")
    args = parser.parse_args()
    rom = args.rom.read_bytes()
    result, changed = regenerate(rom, args.source.read_text(encoding="utf-8"), args.level_info)
    output = args.out or args.source
    output.write_text(result, encoding="utf-8")
    print(f"Restored ROM-derived regions; changed {changed} bytes: {output}")
    if args.overworld_source:
        bank = rom[16 + 6 * BANK_SIZE:16 + 7 * BANK_SIZE]
        payload = read_bank6_pointer(bank, 0x14, 256) + read_bank6_pointer(bank, 0x28, 142)
        source = args.overworld_source.read_text(encoding="utf-8")
        start, end = source.index("{") + 1, source.rindex("}")
        body = source[start:end]
        tokens = list(re.finditer(r"0x[0-9a-fA-F]+|\d+", body))
        if len(tokens) < 768 + len(payload):
            raise ValueError("Overworld blob missing LevelInfo/common regions")
        changed = 0
        for token, value in reversed(list(zip(tokens[768:768 + len(payload)], payload))):
            if int(token.group(), 0) != value:
                changed += 1
                body = body[:token.start()] + f"0x{value:02x}" + body[token.end():]
        args.overworld_source.write_text(source[:start] + body + source[end:], encoding="utf-8")
        print(f"Restored OW LevelInfo/common; changed {changed} bytes")


if __name__ == "__main__":
    main()
