"""determinism_gate.py — deterministic-rebuild gate for builds/Debug.md.

SCOPE, stated precisely because the distinction is load-bearing:

  This gate proves the build is DETERMINISTIC — building twice from the
  same tree, with the intermediate cache wiped between runs, produces a
  byte-identical ROM.

  It does NOT prove FROM-SCRATCH REPRODUCIBILITY. That is
  from_scratch_gate.py, which additionally regenerates every asset from a
  user-supplied NES ROM. This gate builds from the generated assets that
  are already present in the tree.

Reporting one as the other would be the exact failure RULE V1 exists to
prevent, so the verdict line names which claim it makes.

Usage:
    python tools/builder/determinism_gate.py
    python tools/builder/determinism_gate.py --emit-evidence builder

Exit codes:
    0  byte-identical across two clean rebuilds
    1  build failed
    3  byte mismatch (determinism break)
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ROM_OUT = ROOT / "builds" / "Debug.md"
BUILD_CACHE = ROOT / "build" / "debug_project" / "out"
REPORT = ROOT / "docs" / "audit" / "determinism_status.md"

# Files whose contents determine the ROM. Recorded as evidence inputs so
# the cell goes RED the moment any of them changes.
TRACKED_INPUTS = (
    "tools/debug/build_debug.py",
    "tools/builder/determinism_gate.py",
    "tools/sgdk_pin.json",
)


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def build_once() -> int:
    shutil.rmtree(BUILD_CACHE, ignore_errors=True)
    r = subprocess.run(
        [sys.executable, str(ROOT / "tools" / "debug" / "build_debug.py")],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        print(r.stdout[-2000:], file=sys.stderr)
        print(r.stderr[-2000:], file=sys.stderr)
    return r.returncode


def run_gate() -> tuple[int, str]:
    """Return (exit_code, verdict_line)."""
    print("[1/2] building A (cache wiped)...")
    if build_once() != 0 or not ROM_OUT.exists():
        return 1, "determinism_gate: BUILD A FAILED"
    hash_a = sha256_file(ROM_OUT)
    size_a = ROM_OUT.stat().st_size
    print(f"      A sha256={hash_a[:16]}... size={size_a}")

    print("[2/2] building B (cache wiped)...")
    if build_once() != 0 or not ROM_OUT.exists():
        return 1, "determinism_gate: BUILD B FAILED"
    hash_b = sha256_file(ROM_OUT)
    size_b = ROM_OUT.stat().st_size
    print(f"      B sha256={hash_b[:16]}... size={size_b}")

    if hash_a != hash_b or size_a != size_b:
        return 3, (
            f"determinism_gate: DETERMINISM BREAK — A={hash_a[:16]} "
            f"B={hash_b[:16]}"
        )
    return 0, (
        f"determinism_gate: deterministic rebuild byte-identical, "
        f"{size_a} bytes, sha256 {hash_a} "
        f"(NOT from-scratch reproduction; see from_scratch_gate.py)"
    )


def write_report(verdict_line: str) -> None:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(
        "# determinism_gate — BEHAVIOR axis verdict\n\n"
        "> Generated by `tools/builder/determinism_gate.py`.\n"
        "> Proves the build is deterministic. Does NOT prove from-scratch\n"
        "> reproduction from a user ROM — that is `from_scratch_gate.py`,\n"
        "> which has never been run.\n\n"
        f"{verdict_line}\n",
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser(prog="determinism_gate.py")
    ap.add_argument("--emit-evidence", metavar="SYSTEM",
                    help="print a signed evidence block for SYSTEM's BEHAVIOR axis")
    args = ap.parse_args()

    rc, verdict_line = run_gate()
    print(verdict_line)
    write_report(verdict_line)
    if rc != 0:
        return rc

    if args.emit_evidence:
        sys.path.insert(
            0, str(ROOT / "tools" / "audit" / "completion")
        )
        from emit import EvidenceRecorder  # noqa: PLC0415

        rec = EvidenceRecorder(root=ROOT)
        for rel in TRACKED_INPUTS:
            target = ROOT / rel
            if target.exists():
                rec.read(target)
        print(
            rec.emit(
                system=args.emit_evidence,
                axis="BEHAVIOR",
                artifact=REPORT,
                verdict_line=verdict_line,
                command=(
                    "python tools/builder/determinism_gate.py "
                    f"--emit-evidence {args.emit_evidence}"
                ),
                emitted_by="tools/builder/determinism_gate.py",
                tolerance=(
                    "Zero tolerance: the two builds must be byte-identical. "
                    "No accepted deltas. Scope is deterministic rebuild only; "
                    "from-scratch reproduction from a user ROM is unproven "
                    "and tracked as a RED gap on the PLAYABLE axis."
                ),
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
