"""extractor_coverage_gate.py — every extractor must be wired into build.py.

The builder's promise is "drag in your ROM, get a Genesis ROM". That
only holds if build.py invokes every extractor needed to regenerate the
assets the public package deliberately excludes.

Before 2026-08-03 build.py wired exactly one of twelve, and passed
`--rom` to all of them — a flag only extract_nes_banks.py accepts. The
argparse-less scripts ignored it and fell back to their own lookup, so
the user's ROM never reached them. This gate exists so that cannot
silently recur: add tools/extract_foo.py without wiring it, and the gate
goes RED.

SCOPE: proves every extractor is WIRED with its correct calling
convention. Does NOT prove the extractors produce correct output from a
real ROM — that is from_scratch_gate.py, which needs a user ROM.

Usage:
    python tools/builder/extractor_coverage_gate.py
    python tools/builder/extractor_coverage_gate.py --emit-evidence builder

Exit codes:
    0  every extractor accounted for
    1  one or more unwired, or wired but missing from disk
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "docs" / "audit" / "extractor_coverage_status.md"
VALID_CONVENTIONS = {"env", "argv", "flag", "none"}


def discover() -> set[str]:
    """Every tools/extract_*.py on disk."""
    return {p.name for p in (ROOT / "tools").glob("extract_*.py")}


def load_wiring() -> tuple[dict[str, str], dict[str, str]]:
    """Return ({name: convention}, {name: why-manual}).

    EXTRACTORS rows are (name, convention, extra_flags); the flags are
    reported in the artifact but do not affect coverage.
    """
    sys.path.insert(0, str(ROOT / "tools" / "builder"))
    import build  # noqa: PLC0415

    wired = {}
    for row in build.EXTRACTORS:
        name, convention = row[0], row[1]
        extra = row[2] if len(row) > 2 else ()
        wired[name] = convention + (" " + " ".join(extra) if extra else "")
    return wired, dict(build.MANUAL_EXTRACTORS)


def run_gate() -> tuple[int, str]:
    on_disk = discover()
    wired, manual = load_wiring()
    accounted = set(wired) | set(manual)

    unwired = sorted(on_disk - accounted)
    phantom = sorted(accounted - on_disk)
    bad_conv = sorted(
        n for n, c in wired.items() if c.split()[0] not in VALID_CONVENTIONS
    )

    problems: list[str] = []
    if unwired:
        problems.append(f"unwired: {', '.join(unwired)}")
    if phantom:
        problems.append(f"wired but not on disk: {', '.join(phantom)}")
    if bad_conv:
        problems.append(f"invalid convention: {', '.join(bad_conv)}")

    if problems:
        return 1, "extractor_coverage: FAIL — " + "; ".join(problems)

    return 0, (
        f"extractor_coverage: {len(wired)} extractor(s) wired into build.py, "
        f"{len(manual)} documented as manual, {len(on_disk)} on disk, "
        "0 unwired"
    )


def write_report(verdict_line: str, wired: dict[str, str], manual: dict[str, str]) -> None:
    lines = [
        "# extractor_coverage — CODE axis verdict",
        "",
        "> Generated by `tools/builder/extractor_coverage_gate.py`.",
        "> Proves every extractor is wired with its correct calling",
        "> convention. Does NOT prove the extractors produce correct output",
        "> from a real ROM — that is `from_scratch_gate.py`.",
        "",
        verdict_line,
        "",
        "## Wiring",
        "",
        "| Extractor | ROM convention |",
        "|---|---|",
    ]
    lines += [f"| `{n}` | {c} |" for n, c in wired.items()]
    lines += ["", "## Manual (cannot run unattended from a ROM path)", ""]
    lines += [f"- `{n}` — {why}" for n, why in manual.items()]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(prog="extractor_coverage_gate.py")
    ap.add_argument("--emit-evidence", metavar="SYSTEM",
                    help="print a signed evidence block for SYSTEM's CODE axis")
    args = ap.parse_args()

    rc, verdict_line = run_gate()
    wired, manual = load_wiring()
    print(verdict_line)
    write_report(verdict_line, wired, manual)
    if rc != 0:
        return rc

    if args.emit_evidence:
        sys.path.insert(0, str(ROOT / "tools" / "audit" / "completion"))
        from emit import EvidenceRecorder  # noqa: PLC0415

        rec = EvidenceRecorder(root=ROOT)
        rec.read(ROOT / "tools" / "builder" / "build.py")
        rec.read(ROOT / "tools" / "builder" / "extractor_coverage_gate.py")
        for name in wired:
            target = ROOT / "tools" / name
            if target.exists():
                rec.read(target)
        print(
            rec.emit(
                system=args.emit_evidence,
                axis="CODE",
                artifact=REPORT,
                verdict_line=verdict_line,
                command=(
                    "python tools/builder/extractor_coverage_gate.py "
                    f"--emit-evidence {args.emit_evidence}"
                ),
                emitted_by="tools/builder/extractor_coverage_gate.py",
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
