#!/usr/bin/env python3
"""Inject uncaptured/cross-block boss and Triforce rooms into the UW aggregate so
gen_uw_blob.py emits them. nt is generated byte-exact (gen_uw_room_tiles); attr
from same-(block,door-config) capture majority; palram from a same-(map,quest,
level) captured room. Then re-run gen_uw_blob.py + gen_bg_sparse.py. Offline.

Only injects rooms that are genuinely BLACK at runtime: direct lookup miss AND
no same-BLOCK sibling capture (find_blob_entry's fallback can't reach them)."""
import json, re, pathlib, sys, collections
ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "builder"))
import gen_uw_room_tiles as G

AGG = ROOT / "RoomRom" / "out" / "nes_uw_aggregate.json"

# ---- parse captured blob for attr + palette sources ----
txt = (ROOT / "RoomRom" / "src" / "uw_room_blob.c").read_text(errors="replace")
def grab(name):
    m = re.search(r"\b"+name+r"\b[^{]*\{", txt); i=m.end(); d=1; s=i
    while d:
        c=txt[i]
        if c=='{': d+=1
        elif c=='}': d-=1
        i+=1
    return txt[s:i-1]
INDEX = [[int(x,16) for x in re.findall(r"0x[0-9a-fA-F]+", r)] for r in re.findall(r"\{([^}]*)\}", grab("g_uw_room_index"))]
_attr = re.findall(r"\{([^{}]*)\}", grab("g_uw_room_attr"))
_pal  = re.findall(r"\{([^{}]*)\}", grab("g_uw_room_palette"))
def attr_of(e): return [int(x,16) for x in re.findall(r"0x[0-9a-fA-F]+", _attr[e])]
def pal_of(e):  return [int(x,16) for x in re.findall(r"0x[0-9a-fA-F]+", _pal[e])]

agg = json.loads(AGG.read_text(encoding="utf-8"))
entries = agg["entries"]

# attr by (block, door-config) -> majority; palette by (map,quest,level) -> any
attr_votes = collections.defaultdict(collections.Counter)
pal_by_lvl = collections.defaultdict(list)
present = set()           # (map,quest,level,room) with a direct entry
block_present = collections.defaultdict(set)  # (map,quest,block) -> {rooms}
for e_i, row in enumerate(INDEX):
    if len(row)!=4: continue
    mp,q,lv,room = row; blk = G.block_of(lv)
    dt = G.door_types(blk,q,room)
    attr_votes[(blk,dt['N'],dt['S'],dt['E'],dt['W'])][tuple(attr_of(e_i))] += 1
    pal_by_lvl[(mp,q,lv)].append(pal_of(e_i))
    present.add((mp,q,lv,room)); block_present[(mp,q,blk)].add(room)

def pick_attr(blk,q,room):
    dt=G.door_types(blk,q,room); key=(blk,dt['N'],dt['S'],dt['E'],dt['W'])
    if attr_votes.get(key): return list(attr_votes[key].most_common(1)[0][0])
    # fallback: block-wide most common attr
    allc=collections.Counter()
    for k,c in attr_votes.items():
        if k[0]==blk: allc.update(c)
    return list(allc.most_common(1)[0][0])
def pick_pal(mp,q,lv):
    if pal_by_lvl.get((mp,q,lv)): return pal_by_lvl[(mp,q,lv)][0]
    for qq in (1,2):
        if pal_by_lvl.get((mp,qq,lv)): return pal_by_lvl[(mp,qq,lv)][0]
    raise RuntimeError(f"no palette source for map{mp} q{q} L{lv}")

# ---- find uncovered required rooms (Original map0, both quests) ----
def required_rooms(lv,q):
    p=ROOT/f"RoomRom/data/uw_level{lv}_quest{q}_rooms.json"
    if not p.exists(): return []
    manifest = json.loads(p.read_text())
    # The traversal-derived `rooms` list omits some terminal rewards.
    # Explicit roles are required too; a successful boss exit reaches them.
    return sorted({int(manifest[key], 0)
                   for key in ("boss_room_id", "triforce_room_id")
                   if manifest.get(key) is not None})

inject=[]
for mp in (0,):                      # orig only (redux uses different data)
    for q in (1,2):
        for lv in range(1,10):
            for room in required_rooms(lv,q):
                blk=G.block_of(lv)
                if (mp,q,lv,room) in present: continue         # direct hit
                if room in block_present[(mp,q,blk)]: continue # sibling fallback covers it
                inject.append((mp,q,lv,room,blk))

# idempotence: drop any already in the aggregate (e.g. a prior run)
have = {(e["map_id"],e["quest"],e["level"],e["room_id"]) for e in entries}
inject = [x for x in inject if (x[0],x[1],x[2],x[3]) not in have]
print("Uncovered boss/reward rooms to inject:", [(m,q,l,hex(r)) for m,q,l,r,b in inject])
if not inject:
    print("nothing to inject (already present)"); sys.exit(0)
for mp,q,lv,room,blk in inject:
    nt22 = G.compose(blk,q,room)                 # 22 rows (NT 8..29)
    nt30 = [[0]*32 for _ in range(8)] + [nt22[r*32:(r+1)*32] for r in range(22)]
    entries.append({
        "rom": "orig" if mp==0 else "redux",
        "map_id": mp, "quest": q, "level": lv, "room_id": room,
        "source_block": f"SYNTH_{blk}Q{q}",   # marks generator-derived
        "settle_frames": 0,
        "nt": nt30, "attr": pick_attr(blk,q,room), "palram": pick_pal(mp,q,lv),
    })
    print("  + map%d Q%d L%d room=0x%02X uid=%d" % (mp,q,lv,room,G.uid_of(blk,q,room)))

AGG.write_text(json.dumps(agg), encoding="utf-8")
print("aggregate now %d entries -> %s" % (len(entries), AGG))
