#!/usr/bin/env python3
"""active_scope.py — emit machine + human "where do I work right now" pointer.

Per debate 004 ask 4 + 8.

Reads the master plan's Current Next Action section to determine the
active phase. Emits two artifacts:
  - .active_scope          : key=value file consumed by pre-commit hook
  - docs/audit/active_scope.md : human-readable mirror, git-tracked

Phase -> worktree mapping is derived from the master plan's per-phase
Worktree: header lines (added in debate 004 cleanup). Where the phase
lacks a worktree line, falls back to a static map below.

Run on phase-close commit hook OR manually:
  python tools/audit/active_scope.py
  python tools/audit/active_scope.py --phase 5    # override
  python tools/audit/active_scope.py --check path/to/edited/file
"""
import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MASTER_PLAN = REPO / "docs" / "superpowers" / "plans" / "2026-05-02-title-roomrom-full-port-master-plan.md"
SCOPE_FILE = REPO / ".active_scope"
DOC_FILE = REPO / "docs" / "audit" / "active_scope.md"

# Static phase -> (worktree, ALLOW paths, BLOCK paths) fallback. Used
# when the master plan's per-phase Worktree: line is absent or unparseable.
PHASE_FALLBACK: dict[int, dict[str, list[str] | str]] = {
    0:  {"worktree": "main",     "allow": ["build.bat", "tools/", "docs/"],
         "block": ["RoomRom/src/"]},
    1:  {"worktree": "main",     "allow": ["tools/builder/", "tools/", "data/"],
         "block": ["RoomRom/src/"]},
    2:  {"worktree": "RoomRom",  "allow": ["RoomRom/src/", "RoomRom/data/", "RoomRom/tools/"],
         "block": ["src/frontend/", "src/game/"]},
    3:  {"worktree": "RoomRom",  "allow": ["RoomRom/src/", "RoomRom/data/"],
         "block": ["src/frontend/", "src/game/"]},
    4:  {"worktree": "RoomRom",  "allow": ["RoomRom/src/"],
         "block": ["src/frontend/", "src/game/"]},
    5:  {"worktree": "RoomRom",  "allow": ["RoomRom/src/"],
         "block": ["src/frontend/", "src/game/"]},
    6:  {"worktree": "RoomRom",  "allow": ["RoomRom/src/"],
         "block": ["src/frontend/", "src/game/"]},
    7:  {"worktree": "RoomRom",  "allow": ["RoomRom/src/"],
         "block": ["src/frontend/", "src/game/"]},
    8:  {"worktree": "RoomRom",  "allow": ["RoomRom/src/"],
         "block": ["src/frontend/", "src/game/"]},
    9:  {"worktree": "split",    "allow": ["src/game/options/", "src/frontend/options/", "RoomRom/src/"],
         "block": []},
    10: {"worktree": "main",     "allow": ["src/audio_driver.asm", "data/audio/", "src/sgdk_adapter/audio_adapter.c"],
         "block": ["RoomRom/src/"]},
    11: {"worktree": "main",     "allow": ["src/frontend/"],
         "block": ["RoomRom/src/", "src/game/"]},
    12: {"worktree": "main",     "allow": ["src/game/", "src/frontend/", "build.bat"],
         "block": []},
}

# Substrate paths are always edit-allowed FROM main. RoomRom rebases.
SUBSTRATE_PATHS = [
    "src/sgdk_adapter/", "src/abi/", "src/state/", "data/", "src/audio_driver.asm",
]


def parse_current_phase() -> int | None:
    """Find the active phase from master plan's Current Next Action section."""
    if not MASTER_PLAN.exists():
        return None
    text = MASTER_PLAN.read_text(encoding="utf-8")
    # Look for the first unchecked Tier-1 item or "## Phase N" reference
    # in the "Current Next Action" section.
    m = re.search(r"## Current Next Action(.+?)(?=^## )", text,
                  re.MULTILINE | re.DOTALL)
    if not m:
        return None
    section = m.group(1)
    # First "Phase N" mention wins.
    pm = re.search(r"Phase\s+(\d+)", section)
    if pm:
        return int(pm.group(1))
    return None


def build_scope(phase: int) -> dict:
    fallback = PHASE_FALLBACK.get(phase, {
        "worktree": "main",
        "allow": [],
        "block": [],
    })
    return {
        "phase": phase,
        "worktree": fallback["worktree"],
        "allow": fallback["allow"],
        "block": fallback["block"],
        "substrate_ok_from": "main",
        "substrate_paths": SUBSTRATE_PATHS,
    }


def write_scope_file(scope: dict) -> None:
    lines = [
        "# Auto-generated by tools/audit/active_scope.py — do not edit.",
        f"PHASE={scope['phase']}",
        f"WORKTREE={scope['worktree']}",
        f"ALLOW={','.join(scope['allow'])}",
        f"BLOCK={','.join(scope['block'])}",
        f"SUBSTRATE_OK_FROM={scope['substrate_ok_from']}",
        f"SUBSTRATE_PATHS={','.join(scope['substrate_paths'])}",
    ]
    SCOPE_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_doc_mirror(scope: dict) -> None:
    DOC_FILE.parent.mkdir(parents=True, exist_ok=True)
    md = [
        "# Active Scope Pointer",
        "",
        "> Auto-generated by `tools/audit/active_scope.py`. Do not edit by hand.",
        "> Re-run on phase-close commit. Pre-commit hook reads `.active_scope`.",
        "",
        f"- **Active phase:** Phase {scope['phase']}",
        f"- **Active worktree:** `{scope['worktree']}`",
        "",
        "## Allowed edit paths",
        "",
    ]
    if scope['allow']:
        for p in scope['allow']:
            md.append(f"- `{p}`")
    else:
        md.append("- (none restricted; phase-wide)")
    md += ["", "## Blocked edit paths (this phase)", ""]
    if scope['block']:
        for p in scope['block']:
            md.append(f"- `{p}`")
    else:
        md.append("- (none blocked; phase-wide)")
    md += [
        "",
        "## Substrate (always main-only writer; RoomRom rebases)",
        "",
    ]
    for p in scope['substrate_paths']:
        md.append(f"- `{p}`")
    md += [
        "",
        "## Bypassing the scope",
        "",
        "Edits outside ALLOW or inside BLOCK trigger pre-commit warnings,",
        "not blocks. Override is the user's call. The pointer is advisory; the",
        "shared-substrate gate (`tools/gates/check_substrate_dual_rom.py`) and",
        "the frontend boundary gate (`tools/gates/check_frontend_boundary.py`)",
        "are mechanical.",
    ]
    DOC_FILE.write_text("\n".join(md) + "\n", encoding="utf-8")


def is_path_in_scope(path_str: str, scope: dict) -> tuple[bool, str]:
    """Return (in_scope, reason). True = OK. False = warn-worthy."""
    p = path_str.replace("\\", "/")
    for blocked in scope["block"]:
        if p.startswith(blocked):
            return False, f"under BLOCK '{blocked}' for Phase {scope['phase']}"
    for sub in scope["substrate_paths"]:
        if p.startswith(sub):
            return True, f"substrate (writer must be {scope['substrate_ok_from']} worktree)"
    if not scope["allow"]:
        return True, "no ALLOW restriction"
    for allowed in scope["allow"]:
        if p.startswith(allowed):
            return True, f"under ALLOW '{allowed}'"
    return False, f"not under any ALLOW for Phase {scope['phase']}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--phase", type=int, help="override detected phase")
    ap.add_argument("--check", metavar="PATH",
                    help="check whether PATH is in current scope; "
                         "exit 0 if OK, 0+warn if out of scope (advisory)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    phase = args.phase if args.phase is not None else parse_current_phase()
    if phase is None:
        print("WARN: could not detect active phase from master plan; "
              "using Phase 2 fallback.", file=sys.stderr)
        phase = 2

    scope = build_scope(phase)

    if args.check:
        in_scope, reason = is_path_in_scope(args.check, scope)
        marker = "OK" if in_scope else "WARN"
        print(f"{marker}: {args.check} — {reason}")
        return 0

    write_scope_file(scope)
    write_doc_mirror(scope)
    if not args.quiet:
        print(f"Active scope: Phase {scope['phase']} / worktree {scope['worktree']}")
        print(f"  wrote {SCOPE_FILE.relative_to(REPO).as_posix()}")
        print(f"  wrote {DOC_FILE.relative_to(REPO).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
