#!/usr/bin/env python3
"""merge_readiness.py — Phase 12 promotion readiness dashboard.

Per debate 004 ask 4 + 10.

Reports per-RoomRom-module promotion eligibility plus repo-wide drift
indicators. Output goes to stdout AND `builds/merge_readiness.md`.

Module readiness columns:
  Typed       : module's state header has typed struct (per state_contract.md)
  NoFE        : no #include of src/frontend/* headers
  NoCol       : no symbol collision with src/game/* (post-promotion namespace)
  Provenance  : has a parity-oracle-schema instance per Phase 1.5

Repo-wide indicators:
  substrate drift : files under src/sgdk_adapter|src/abi|src/state|data
                    differing between Title build and last RoomRom build
  ABI symbol delta: symbol-table additions/removals in src/abi exports
  parity oracle   : Phase 1.5 capture pass-rate (placeholder until Phase 1.5
                    captures populate)
  determinism     : Title.md SHA256 stability across same-source rebuild
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROOMROM_SRC = REPO / "RoomRom" / "src"
SRC_FRONTEND = REPO / "src" / "frontend"
SRC_GAME = REPO / "src" / "game"
OUT_PATH = REPO / "builds" / "merge_readiness.md"

INCLUDE_RE = re.compile(r'^\s*#\s*include\s*[<"]([^>"]+)[>"]', re.MULTILINE)


def list_roomrom_modules() -> list[Path]:
    """Top-level RoomRom/src/*.c source modules. Subdirs aggregated by parent."""
    if not ROOMROM_SRC.exists():
        return []
    out = []
    for p in sorted(ROOMROM_SRC.rglob("*.c")):
        out.append(p)
    return out


def has_typed_state_header(module: Path) -> bool:
    """Heuristic: module is Typed if its corresponding state header (if any)
    in src/state/ contains a `typedef struct` declaration."""
    name = module.stem  # e.g. roomrom_link, roomrom_sprites
    candidates = [
        REPO / "src" / "state" / f"{name}_state.h",
        REPO / "src" / "state" / f"{name.replace('roomrom_', '')}_state.h",
    ]
    for c in candidates:
        if c.exists():
            text = c.read_text(encoding="utf-8", errors="replace")
            if "typedef struct" in text:
                return True
    # Modules without a corresponding state header pass by default.
    return True


def includes_frontend(module: Path) -> bool:
    text = module.read_text(encoding="utf-8", errors="replace")
    for m in INCLUDE_RE.finditer(text):
        inc = m.group(1)
        if (inc.startswith("frontend/") or inc.startswith("../frontend/")
                or inc.startswith("src/frontend/")):
            return True
    return False


def collides_with_game(module: Path) -> bool:
    """Heuristic: a module collides if a same-named .c file already exists
    in src/game/ (would be a Phase 12 promotion conflict)."""
    name = module.stem.replace("roomrom_", "")
    for p in SRC_GAME.rglob(f"{name}.c"):
        if p.exists():
            return True
    return False


def has_provenance(module: Path) -> bool:
    """Placeholder: returns False until Phase 1.5 capture artifacts populate."""
    capture_root = REPO / "build" / "generated" / "nes_reference"
    return capture_root.exists() and any(capture_root.iterdir())


def git_short_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"],
            text=True,
        ).strip()
    except subprocess.CalledProcessError:
        return "unknown"


def title_md_sha() -> str:
    p = REPO / "builds" / "Title.md"
    if not p.exists():
        return "missing"
    import hashlib
    h = hashlib.sha256(p.read_bytes()).hexdigest()
    return h[:12]


def fmt_check(b: bool) -> str:
    return "Y" if b else "N"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--quiet", action="store_true",
                    help="suppress stdout; only write file")
    args = ap.parse_args()

    modules = list_roomrom_modules()
    rows: list[tuple[str, bool, bool, bool, bool, bool]] = []
    for m in modules:
        typed = has_typed_state_header(m)
        nofe = not includes_frontend(m)
        nocol = not collides_with_game(m)
        prov = has_provenance(m)
        ready = typed and nofe and nocol and prov
        rows.append((str(m.relative_to(REPO).as_posix()), typed, nofe,
                     nocol, prov, ready))

    eligible = sum(1 for r in rows if r[5])
    total = len(rows)
    overall = "GREEN" if (eligible == total and total > 0) else (
        "YELLOW" if eligible >= total // 2 else "RED")

    git_sha = git_short_sha()
    title_sha = title_md_sha()

    lines = [
        "# Phase 12 Merge Readiness Dashboard",
        "",
        f"> Auto-generated by `tools/audit/merge_readiness.py`. Run on demand.",
        "",
        f"- **Repo HEAD:** `{git_sha}`",
        f"- **Title.md SHA256 (first 12):** `{title_sha}`",
        f"- **Overall:** **{overall}**",
        f"- **Eligible modules:** {eligible}/{total} "
        f"({(eligible * 100 // total) if total else 0}%)",
        "",
        "## Per-RoomRom-module readiness",
        "",
        "| Module | Typed | NoFE | NoCol | Provenance | READY |",
        "|--------|-------|------|-------|-----------|-------|",
    ]
    for path, typed, nofe, nocol, prov, ready in rows:
        lines.append(
            f"| `{path}` | {fmt_check(typed)} | {fmt_check(nofe)} | "
            f"{fmt_check(nocol)} | {fmt_check(prov)} | "
            f"{'**YES**' if ready else 'NO'} |"
        )

    lines += [
        "",
        "## Repo-wide indicators",
        "",
        "- **Substrate drift:** check `tools/gates/check_substrate_dual_rom.py`",
        "- **Frontend boundary:** check `tools/gates/check_frontend_boundary.py`",
        "- **Legacy alias gate:** check `tools/gates/check_no_whatif.py`",
        "- **Active scope pointer:** see `docs/audit/active_scope.md`",
        "- **Parity oracle:** placeholder — Phase 1.5 capture artifacts not "
        "yet populated (`build/generated/nes_reference/`)",
        "",
        "## Blockers",
        "",
    ]
    blockers = []
    for path, typed, nofe, nocol, prov, ready in rows:
        if ready:
            continue
        reasons = []
        if not typed: reasons.append("typed-state missing")
        if not nofe:  reasons.append("includes frontend/")
        if not nocol: reasons.append(f"src/game/ name collision")
        if not prov:  reasons.append("provenance pending Phase 1.5")
        blockers.append(f"- `{path}`: " + "; ".join(reasons))
    lines += blockers if blockers else ["- (none)"]

    out = "\n".join(lines) + "\n"
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(out, encoding="utf-8")

    if not args.quiet:
        print(out)
        print(f"\nWrote {OUT_PATH.relative_to(REPO).as_posix()}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
