/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
#ifndef ROOMROM_ATLAS_DISPATCH_H
#define ROOMROM_ATLAS_DISPATCH_H

#include "atlas_static_assert.h"

/* NES sprite dispatch classes (from Anim_WriteSpecificItemSprites
 * and ObjAnimAttr dispatch paths in Z_01.asm / Z_07.asm). */
typedef enum {
    NES_NARROW    = 0,  /* 8x8 or 8x16: single sprite */
    NES_SLIM      = 1,  /* 16x8 stretched: two 8x8 side-by-side */
    NES_MIRRORED  = 2,  /* 16x8 mirrored: right = left hflipped */
    NES_FLIPPABLE = 3,  /* 16x16 or 16x8 h-flippable pair */
} atlas_nes_dispatch_class_t;

typedef struct {
    unsigned char w;                       /* SGDK SPRITE_SIZE width tiles */
    unsigned char h;                       /* SGDK SPRITE_SIZE height tiles */
    atlas_nes_dispatch_class_t nes_class;
} atlas_dispatch_t;

/* ATLAS_ASSERT_SIZE: compile-time check that a renderer's claimed
 * SPRITE_SIZE matches the registry dispatch for 'name'.
 *
 * Because _Static_assert requires a constant-expression predicate,
 * the dispatch struct literal is NOT used directly. Instead each
 * per-category header emits plain #defines:
 *   #define W_<NAME>  <width>
 *   #define H_<NAME>  <height>
 * which ARE integer constant expressions. ATLAS_ASSERT_SIZE then
 * _Static_asserts against those defines. */
#define ATLAS_ASSERT_SIZE(name, expect_w, expect_h) \
    ATLAS_STATIC_ASSERT( \
        W_##name == (expect_w) && H_##name == (expect_h), \
        #name " SPRITE_SIZE mismatch vs registry dispatch")

/* ATLAS_ASSERT_BG_TILE: same compile-time check as ATLAS_ASSERT_SIZE,
 * named to indicate BG-tile (tilemap) dispatch rather than sprite
 * dispatch. Implementation is identical; the distinct name documents
 * intent at the call site and allows future divergence if BG and
 * sprite dispatch classes need to be checked differently. */
#define ATLAS_ASSERT_BG_TILE(name, expect_w, expect_h) \
    ATLAS_STATIC_ASSERT( \
        W_##name == (expect_w) && H_##name == (expect_h), \
        #name " BG tile size mismatch vs registry dispatch")

#endif /* ROOMROM_ATLAS_DISPATCH_H */

