/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
/* bg_overworld: BG tiles are already handled by expanded_bg_chr.c and
 * roomrom_bg_palette.c. This stub extends the atlas namespace for
 * scene VRAM contract referencing. Phase 4 wires DMA upload. */
#ifndef ROOMROM_ATLAS_BG_OVERWORLD_CHR_H
#define ROOMROM_ATLAS_BG_OVERWORLD_CHR_H

#define ROOMROM_ATLAS_BG_OVERWORLD_BYTES 0u

/* Entries (8 total) ? offset defines deferred to Phase 4 */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_COMMONSPRITEPATTERNS_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_COMMONBACKGROUNDPATTERNS_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_COMMONMISCPATTERNS_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_DEMOSPRITEPATTERNS_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_DEMOBACKGROUNDPATTERNS_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_PATTERNBLOCKOWBG_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_PATTERNBLOCKOWSP_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_OVERWORLD_BG_GAMETITLETRANSFERBUF_OFFSET 0u  /* stub */

#endif /* ROOMROM_ATLAS_BG_OVERWORLD_CHR_H */

