/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
#include "atlas/bg_overworld_chr.h"

/* TODO (Phase 4): BG CHR upload is handled by expanded_bg_chr.c.
 * This file exists to satisfy atlas namespace; no byte data here. */

