/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
/* bg_underworld: BG tiles are already handled by expanded_bg_chr.c and
 * roomrom_bg_palette.c. This stub extends the atlas namespace for
 * scene VRAM contract referencing. Phase 4 wires DMA upload. */
#ifndef ROOMROM_ATLAS_BG_UNDERWORLD_CHR_H
#define ROOMROM_ATLAS_BG_UNDERWORLD_CHR_H

#define ROOMROM_ATLAS_BG_UNDERWORLD_BYTES 0u

/* Entries (8 total) ? offset defines deferred to Phase 4 */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWBG_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWSP358_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWSP469_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWSP_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWSP127_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWSPBOSS1257_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWSPBOSS3468_OFFSET 0u  /* stub */
#define ROOMROM_ATLAS_BG_UNDERWORLD_BG_PATTERNBLOCKUWSPBOSS9_OFFSET 0u  /* stub */

#endif /* ROOMROM_ATLAS_BG_UNDERWORLD_CHR_H */

