/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
/* items_chr_x4: 4x pixel-biased sub-pal expansion of the 8-item
 * legacy weapon atlas (item_chr_manifest.json), generated by
 * gen_atlas.py --items-blob-legacy mode.
 *
 * Byte layout per row: pal0_bytes || pal1_bytes || pal2_bytes || pal3_bytes
 * Per-pal stride = 992 bytes (31 Genesis tiles).
 * Pixel bias rule: out = (in==0) ? 0 : (sub_pal*4 + in).
 * Byte-identical to expand_sprite_chr.py -> roomrom_item_chr_x4.
 */
#ifndef ROOMROM_ATLAS_ITEMS_X4_H
#define ROOMROM_ATLAS_ITEMS_X4_H

#define ROOMROM_ATLAS_ITEMS_X4_VARIANT_COUNT 2u
#define ROOMROM_ATLAS_ITEMS_X4_PER_PAL_BYTES  992u
#define ROOMROM_ATLAS_ITEMS_X4_BYTES          3968u

extern const unsigned char roomrom_atlas_items_x4
    [ROOMROM_ATLAS_ITEMS_X4_VARIANT_COUNT][ROOMROM_ATLAS_ITEMS_X4_BYTES];

#endif /* ROOMROM_ATLAS_ITEMS_X4_H */

