/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
/* items_chr_x4: 4x pixel-biased sub-pal expansion of the 8-item
 * legacy weapon atlas (item_chr_manifest.json), generated by
 * gen_atlas.py FU2 items_blob_legacy mode.
 *
 * Byte layout per row: pal0_bytes || pal1_bytes || pal2_bytes || pal3_bytes
 * Per-pal stride = 3328 bytes (104 Genesis tiles).
 * Pixel bias rule: out = (in==0) ? 0 : (sub_pal*4 + in).
 * Byte-identical to expand_sprite_chr.py -> roomrom_item_chr_x4.
 */
#ifndef ROOMROM_ATLAS_ITEMS_X4_H
#define ROOMROM_ATLAS_ITEMS_X4_H

#define ROOMROM_ATLAS_ITEMS_X4_VARIANT_COUNT    2u
#define ROOMROM_ATLAS_ITEMS_X4_TILE_COUNT       104u
#define ROOMROM_ATLAS_ITEMS_X4_PER_PAL_BYTES    3328u
#define ROOMROM_ATLAS_ITEMS_X4_BYTES            3328u

/* Tile-index constants: byte_offset = TILE_INDEX * 32
 * These supersede the legacy ROOMROM_ITEM_TILE_* constants from
 * roomrom_item_chr.h; values are identical. */
#define ROOMROM_ITEM_TILE_SWORD_VERT 0u
#define ROOMROM_ITEM_TILE_SWORD_HORZ 2u
#define ROOMROM_ITEM_TILE_BOOMERANG 6u
#define ROOMROM_ITEM_TILE_ARROW_VERT 14u
#define ROOMROM_ITEM_TILE_ARROW_HORZ 16u
#define ROOMROM_ITEM_TILE_BOMB 20u
#define ROOMROM_ITEM_TILE_EXPLOSION 22u
#define ROOMROM_ITEM_TILE_SWORD_DIAG 34u
#define ROOMROM_ITEM_TILE_CANDLE_FIRE_F0 38u
#define ROOMROM_ITEM_TILE_CANDLE_FIRE_F1 42u
#define ROOMROM_ITEM_TILE_CANDLE_FIRE_F2 46u
#define ROOMROM_ITEM_TILE_CANDLE_FIRE_F3 50u
#define ROOMROM_ITEM_TILE_COMPASS 54u
#define ROOMROM_ITEM_TILE_MAP 56u
#define ROOMROM_ITEM_TILE_HEART_CONTAINER 58u
#define ROOMROM_ITEM_TILE_BIG_KEY 62u
#define ROOMROM_ITEM_TILE_BOOK_OF_MAGIC 64u
#define ROOMROM_ITEM_TILE_RAFT 66u
#define ROOMROM_ITEM_TILE_LADDER 68u
#define ROOMROM_ITEM_TILE_RING 70u
#define ROOMROM_ITEM_TILE_MAGIC_KEY 72u
#define ROOMROM_ITEM_TILE_BRACELET 74u
#define ROOMROM_ITEM_TILE_BOW 76u
#define ROOMROM_ITEM_TILE_RECORDER 78u
#define ROOMROM_ITEM_TILE_FOOD 80u
#define ROOMROM_ITEM_TILE_POTION 82u
#define ROOMROM_ITEM_TILE_TRIFORCE_PIECE 84u
#define ROOMROM_ITEM_TILE_MAGIC_SHOT_V 88u
#define ROOMROM_ITEM_TILE_MAGIC_SHOT_H 92u
#define ROOMROM_ITEM_TILE_FAIRY_SPARK_F0 96u
#define ROOMROM_ITEM_TILE_FAIRY_SPARK_F1 98u
#define ROOMROM_ITEM_TILE_DROP_HEART 100u
#define ROOMROM_ITEM_TILE_DROP_CLOCK 102u

extern const unsigned char roomrom_atlas_items_x4
    [ROOMROM_ATLAS_ITEMS_X4_VARIANT_COUNT][ROOMROM_ATLAS_ITEMS_X4_BYTES];

#endif /* ROOMROM_ATLAS_ITEMS_X4_H */

