/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
#include "atlas/roomrom_scene_vram_contracts.h"

/* Per-scene VRAM contract definitions.
 * tile_count values are conservative placeholders; Phase 4 refines
 * to actual Genesis tile counts after CHR expansion wiring lands. */

const roomrom_vram_contract_t roomrom_vram_contract_boot_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_boot_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_boot_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_title_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_title_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_title_title = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 32u),
    /* tile_count */ 26u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 832u,
};

const roomrom_vram_contract_t roomrom_vram_contract_fileselect_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_fileselect_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_fileselect_title = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 32u),
    /* tile_count */ 26u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 832u,
};

const roomrom_vram_contract_t roomrom_vram_contract_fileselect_npc = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 58u),
    /* tile_count */ 12u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1856u,
};

const roomrom_vram_contract_t roomrom_vram_contract_fileselect_fileselect = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 70u),
    /* tile_count */ 45u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1440u,
};

const roomrom_vram_contract_t roomrom_vram_contract_overworld_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_overworld_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_overworld_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_overworld_bg_ow = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_overworld_npc = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 32u),
    /* tile_count */ 12u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1856u,
};

const roomrom_vram_contract_t roomrom_vram_contract_overworld_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 114u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_link = {
    /* tile_base  */ ROOMROM_SPR_TILE_BASE,
    /* tile_count */ 32u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_items = {
    /* tile_base  */ ROOMROM_ITEM_TILE_BASE_PAL(0),
    /* tile_count */ 37u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1920u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_hud = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 22u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 1024u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_bg_uw = {
    /* tile_base  */ ROOMROM_BG_TILE_BASE_PAL(0),
    /* tile_count */ 0u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 0u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_enemies = {
    /* tile_base  */ (ROOMROM_SPR_TILE_BASE + 44u),
    /* tile_count */ 136u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 4352u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_bosses = {
    /* tile_base  */ ROOMROM_BOSS_TILE_BASE,
    /* tile_count */ 64u,
    /* blob_offset */ 0u,
    /* blob_bytes  */ 2048u,
};

