/* Auto-generated by RoomRom/tools/gen_atlas.py - do not edit. */
#ifndef ROOMROM_SCENE_VRAM_CONTRACTS_H
#define ROOMROM_SCENE_VRAM_CONTRACTS_H

/* Extends roomrom_vram_map.h ? does NOT replace it. */
#include "../roomrom_vram_map.h"

/* ---------------------------------------------------------------
 * Scene identifiers
 * --------------------------------------------------------------- */
typedef enum {
    ROOMROM_SCENE_BOOT = 0,
    ROOMROM_SCENE_TITLE = 1,
    ROOMROM_SCENE_FILESELECT = 2,
    ROOMROM_SCENE_OVERWORLD = 3,
    ROOMROM_SCENE_UW_L1 = 4,
    ROOMROM_SCENE_UW_L2 = 5,
    ROOMROM_SCENE_UW_L3 = 6,
    ROOMROM_SCENE_UW_L4 = 7,
    ROOMROM_SCENE_UW_L5 = 8,
    ROOMROM_SCENE_UW_L6 = 9,
    ROOMROM_SCENE_UW_L7 = 10,
    ROOMROM_SCENE_UW_L8 = 11,
    ROOMROM_SCENE_UW_L9 = 12,
    ROOMROM_SCENE_COUNT
} roomrom_scene_id_t;

/* ---------------------------------------------------------------
 * VRAM contract: per-(scene, category) tile range.
 * tile_base  = absolute Genesis VRAM tile index
 * tile_count = number of tiles resident in VRAM for this category
 *              when the scene is active (0 = deferred / Phase 4)
 * blob_offset = byte offset into the category's atlas blob
 * blob_bytes  = byte count from that offset (0 = deferred)
 * --------------------------------------------------------------- */
typedef struct {
    unsigned short tile_base;
    unsigned short tile_count;
    unsigned short blob_offset;
    unsigned short blob_bytes;
} roomrom_vram_contract_t;

extern const roomrom_vram_contract_t roomrom_vram_contract_boot_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_boot_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_boot_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_title_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_title_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_title_title;
extern const roomrom_vram_contract_t roomrom_vram_contract_fileselect_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_fileselect_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_fileselect_title;
extern const roomrom_vram_contract_t roomrom_vram_contract_fileselect_npc;
extern const roomrom_vram_contract_t roomrom_vram_contract_fileselect_fileselect;
extern const roomrom_vram_contract_t roomrom_vram_contract_overworld_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_overworld_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_overworld_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_overworld_bg_ow;
extern const roomrom_vram_contract_t roomrom_vram_contract_overworld_npc;
extern const roomrom_vram_contract_t roomrom_vram_contract_overworld_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_link;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_items;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_hud;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_bg_uw;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_enemies;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l1_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l2_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l3_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l4_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l5_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l6_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l7_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l8_bosses;
extern const roomrom_vram_contract_t roomrom_vram_contract_uw_l9_bosses;

#endif /* ROOMROM_SCENE_VRAM_CONTRACTS_H */

