/* Auto-generated by RoomRom/tools/gen_bg_sparse.py. Do not edit. */
#ifndef ROOMROM_BG_SPARSE_CHR_H
#define ROOMROM_BG_SPARSE_CHR_H

/* Phase J sparse BG atlas: per-variant flat tile array indexed by
 * bg_sparse_tile_lut[nes_tile_id][nes_sub_pal] -> slot index (0..N-1).
 * Sentinel 0xFFFF = (tile_id, sub_pal) never referenced by any room.
 * Each variant's blob is bias-encoded (out=(in==0)?0:(s*4+in)) so the
 * tile renders correctly via PAL0 pixel-bias when looked up at its slot.
 *
 * NOTE Phase J Step 2: data emitted; legacy expanded_bg_chr.{c,h} also
 * in tree. Renderer switch is Step 3 (not this commit). Atlas + LUT
 * are ready but not yet wired. */

#define BG_SPARSE_TILE_COUNT      290u
#define BG_SPARSE_BLOB_BYTES      9280u

extern const unsigned char  bg_sparse_chr_orig_ow [9280];
extern const unsigned char  bg_sparse_chr_orig_uw [9280];
extern const unsigned char  bg_sparse_chr_redux_ow[9280];
extern const unsigned short bg_sparse_tile_lut[256][4];

#endif /* ROOMROM_BG_SPARSE_CHR_H */
