/* Auto-generated by RoomRom/tools/gen_bg_sparse.py. Do not edit. */
#ifndef ROOMROM_BG_SPARSE_CHR_H
#define ROOMROM_BG_SPARSE_CHR_H

/* Phase J sparse BG atlas: per-variant flat tile array indexed by
 * bg_sparse_tile_lut[nes_tile_id][nes_sub_pal] -> slot index (0..N-1).
 * Sentinel 0xFFFF = (tile_id, sub_pal) never referenced by any room.
 * Each variant's blob is bias-encoded (out=(in==0)?0:(s*4+in)) so the
 * tile renders correctly via PAL0 pixel-bias when looked up at its slot.
 *
 * Phase J.2 (2026-05-18): 4 variants — orig+redux x OW+UW. Redux UW
 * uses unified_source mode (redux_uw_bg_chr is a flat 256-tile bank
 * that replaces the entire BG bank, common+scene+misc included). */

#define BG_SPARSE_TILE_COUNT      589u
#define BG_SPARSE_BLOB_BYTES      18848u

extern const unsigned char  bg_sparse_chr_orig_ow  [18848];
extern const unsigned char  bg_sparse_chr_orig_uw  [18848];
extern const unsigned char  bg_sparse_chr_redux_ow [18848];
extern const unsigned char  bg_sparse_chr_redux_uw [18848];
extern const unsigned short bg_sparse_tile_lut[256][4];

#endif /* ROOMROM_BG_SPARSE_CHR_H */
