/* Auto-generated by RoomRom/tools/gen_item_chr_blob.py - do not edit. */
#ifndef ROOMROM_ITEM_CHR_H
#define ROOMROM_ITEM_CHR_H

#define ROOMROM_ITEM_CHR_VARIANT_COUNT 2u
#define ROOMROM_ITEM_CHR_TILE_COUNT 26u
#define ROOMROM_ITEM_CHR_BYTES 832u

#define ROOMROM_ITEM_TILE_SWORD_VERT 0u
#define ROOMROM_ITEM_TILE_SWORD_HORZ 2u
#define ROOMROM_ITEM_TILE_BOOMERANG 6u
#define ROOMROM_ITEM_TILE_ARROW_VERT 14u
#define ROOMROM_ITEM_TILE_ARROW_HORZ 16u
#define ROOMROM_ITEM_TILE_BOMB 20u
#define ROOMROM_ITEM_TILE_EXPLOSION 22u

extern const unsigned long roomrom_item_chr_size;
extern const unsigned short roomrom_item_chr_byte_count;
extern const unsigned char roomrom_item_chr
    [ROOMROM_ITEM_CHR_VARIANT_COUNT][ROOMROM_ITEM_CHR_BYTES];

#endif
