/* Generated by RoomRom/tools/gen_bg_palette_blob.py. Do not edit. */
#ifndef ROOMROM_OW_PALETTE_H
#define ROOMROM_OW_PALETTE_H

/* g_roomrom_ow_palram[map][i] holds NES Overworld PALRAM bytes
 * (i in [0..31]: bytes 0..15 = BG sub-pals, 16..31 = SPR sub-pals).
 * map index 0 = original, 1 = redux. */
extern const unsigned char g_roomrom_ow_palram[2][32];

#endif
