/* uw_collision_data.h — auto-generated by tools/builder/gen_uw_collision_c.py */
/* DO NOT EDIT. */
#ifndef UW_COLLISION_DATA_H
#define UW_COLLISION_DATA_H

/* 2-bit metatile classification per debate ph5-t52-precheck Q3 (Option B).
 * Byte-per-cell storage (only low 2 bits used; upper 6 bits zero). */
#define UW_CLASS_WALK    0u
#define UW_CLASS_WALL    1u
#define UW_CLASS_WATER   2u
#define UW_CLASS_HAZARD  3u   /* reserved for 5.3 hazard floor work */

/* [unique_room_id][col][row] metatile class (UW_CLASS_*).
 * col 0..15, row 0..10 in metatile coords. Border cells = UW_CLASS_WALL. */
extern const unsigned char uw_collision_grid[64][16][11];

/* [set][room_id] unique_room_id (0..63).
 * set: 0=levels1-6 Q1, 1=levels1-6 Q2, 2=levels7-9 Q1, 3=levels7-9 Q2 */
extern const unsigned char uw_lba_d[4][128];

/* Return the LBA_D set index for a given level (1-9) and quest (1-2). */
static inline unsigned char uw_lba_d_set(unsigned char level, unsigned char quest)
{
    unsigned char base = (level >= 7) ? 2u : 0u;
    return (unsigned char)(base + (quest == 2u ? 1u : 0u));
}

/* Raw metatile class (UW_CLASS_*) at (col, row) in the given room.
 * Use this for 5.3+ semantics (water/hazard/stair logic). */
static inline unsigned char uw_room_metatile_class(
    unsigned char level, unsigned char quest,
    unsigned char room_id, unsigned char col, unsigned char row)
{
    unsigned char set = uw_lba_d_set(level, quest);
    unsigned char uid = uw_lba_d[set][room_id];
    return uw_collision_grid[uid][col][row];
}

/* Walkable test: 1 if class == WALK. WATER/WALL/HAZARD all block Link by
 * default; raft/conditional walkability is runtime game state, not stored
 * in this table. */
static inline unsigned char uw_room_walkable(
    unsigned char level, unsigned char quest,
    unsigned char room_id, unsigned char col, unsigned char row)
{
    return (unsigned char)(uw_room_metatile_class(level, quest, room_id,
                                                  col, row) == UW_CLASS_WALK);
}

#endif /* UW_COLLISION_DATA_H */
