/* sfx_pcm.h - auto-generated by tools/extract_dmc_samples.py
 * DO NOT EDIT BY HAND. Regenerate from Legend of Zelda, The (USA).nes.
 *
 * Seven NES DMC samples ripped from the stock ROM, decoded and bandlimited
 * to 14000 Hz for the SGDK XGM (Doppler) driver. Format is 8-bit
 * SIGNED two's-complement, 0x00 = silence, length padded to 256-byte
 * boundary with 0x00 silence. (Stored as u8 because XGM_setPCM takes u8*,
 * but the Z80 mixer interprets each byte as int8 — see drv_xgm.s80:405.)
 *
 * Sample IDs start at 64 (XGM reserves 1..63 for music).
 */
#ifndef SFX_PCM_H
#define SFX_PCM_H

#include "types.h"

#define SFX_PCM_COUNT       7
#define SFX_PCM_RATE_HZ     14000
#define SFX_PCM_ID_BASE     64

#define SFX_PCM_SFX_01_ID    64
#define SFX_PCM_SFX_01_LEN   6400
extern const u8 sfx_pcm_sfx_01[6400];

#define SFX_PCM_SFX_02_ID    65
#define SFX_PCM_SFX_02_LEN   10496
extern const u8 sfx_pcm_sfx_02[10496];

#define SFX_PCM_SFX_03_ID    66
#define SFX_PCM_SFX_03_LEN   5632
extern const u8 sfx_pcm_sfx_03[5632];

#define SFX_PCM_SFX_04_ID    67
#define SFX_PCM_SFX_04_LEN   768
extern const u8 sfx_pcm_sfx_04[768];

#define SFX_PCM_SFX_05_ID    68
#define SFX_PCM_SFX_05_LEN   12800
extern const u8 sfx_pcm_sfx_05[12800];

#define SFX_PCM_SFX_06_ID    69
#define SFX_PCM_SFX_06_LEN   7936
extern const u8 sfx_pcm_sfx_06[7936];

#define SFX_PCM_SFX_07_ID    70
#define SFX_PCM_SFX_07_LEN   15104
extern const u8 sfx_pcm_sfx_07[15104];

typedef struct {
    const u8 *data;
    u32       len;
    u8        id;
} sfx_pcm_entry_t;

extern const sfx_pcm_entry_t sfx_pcm_table[SFX_PCM_COUNT];

#endif
