#!/usr/bin/env python3
"""Parse reference/aldonunez/dat/GameTitleTransferBuf.dat into a 32x30
Genesis tilemap. NES transfer-record format:
  [hi, lo, count, byte_0, ..., byte_(count-1)]
records repeated, terminated by $FF as the next hi byte.

NES NT0 layout:
  $2000-$23BF = tiles (30 rows x 32 cols)
  $23C0-$23FF = attribute table (16 cols x 15 rows of 2-bit-per-quadrant
                bytes, each byte covers a 4x4-cell region with 2x2 quadrants)

Genesis cell encoding: priority(1) | palette(2) | hflip(1) | vflip(1) | tile(11)
We build cells as (palette << 13) | tile_idx; no flip/priority for title.

Output: intro_title_tilemap.c with intro_title_tilemap_rows + tilemap data.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DAT  = ROOT / "reference" / "aldonunez" / "dat" / "GameTitleTransferBuf.dat"
OUT  = Path(__file__).parent / "intro_title_tilemap.c"

def parse(data: bytes):
    NT_TILES = bytearray(32 * 30)
    ATTR     = bytearray(64)
    i = 0
    while i < len(data):
        hi = data[i]
        if hi == 0xFF:
            break
        lo = data[i+1]
        cnt = data[i+2]
        addr = (hi << 8) | lo
        i += 3
        chunk = data[i:i+cnt]
        i += cnt
        for k, b in enumerate(chunk):
            a = addr + k
            if 0x2000 <= a < 0x23C0:
                NT_TILES[a - 0x2000] = b
            elif 0x23C0 <= a < 0x2400:
                ATTR[a - 0x23C0] = b
    return NT_TILES, ATTR

def cell_palette(col: int, row: int, attr: bytearray) -> int:
    """NES attribute byte covers a 4x4-cell region (bytes laid out 8 across,
    8 rows = 64 bytes). Within each byte, 2 bits per 2x2-cell quadrant:
      bits 0-1 = top-left quadrant
      bits 2-3 = top-right
      bits 4-5 = bottom-left
      bits 6-7 = bottom-right
    """
    attr_idx = (row // 4) * 8 + (col // 4)
    quad_x   = (col % 4) // 2
    quad_y   = (row % 4) // 2
    shift    = (quad_y * 2 + quad_x) * 2
    return (attr[attr_idx] >> shift) & 3

def main() -> int:
    data = DAT.read_bytes()
    NT_TILES, ATTR = parse(data)

    cells = []
    for row in range(30):
        for col in range(32):
            tile = NT_TILES[row * 32 + col]
            pal  = cell_palette(col, row, ATTR)
            cell = (pal << 13) | (tile & 0x7FF)
            cells.append(cell)

    lines = [
        "/* Auto-generated by tools/intro_demo/extract_title_tilemap.py */\n",
        "/* NES title nametable (32 cols x 30 rows) parsed from\n",
        " * GameTitleTransferBuf.dat with per-cell palette index from\n",
        " * NES attribute table. Plane A is 32x32 — rows 30,31 left blank\n",
        " * by main.c. */\n",
        "const unsigned short intro_title_tilemap_rows = 30;\n",
        f"const unsigned short intro_title_tilemap[{len(cells)}] = {{\n",
    ]
    for r in range(30):
        row_cells = cells[r*32:(r+1)*32]
        line = "    " + ", ".join(f"0x{c:04X}" for c in row_cells) + ","
        lines.append(line + "\n")
    lines.append("};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}: 30 rows ({len(cells)} cells)")

    nonblank_per_row = []
    for r in range(30):
        nonblank = sum(1 for c in cells[r*32:(r+1)*32] if (c & 0x7FF) != 0x24)
        nonblank_per_row.append(nonblank)
    print("non-blank cells per row:", nonblank_per_row)
    return 0

if __name__ == "__main__":
    sys.exit(main())
