#!/usr/bin/env python3
"""Convert NES title PALRAM (palram_title.bin, 32 bytes captured at NES
intro frame 100) to Genesis CRAM layout (64 words). Layout matches the
combined-palette packing used elsewhere in intro_demo:

  Gen pal P slots 0-3  = NES BG  pal P  (PALRAM $3F00 + P*4)
  Gen pal P slots 4-7  = NES SPR pal P  (PALRAM $3F10 + P*4)
  Gen pal P slots 8-15 = 0 (unused for title)

Output: intro_title_palette.c with intro_title_palette[64].
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
from extract_intro_assets import nes_color_to_gen_cram

PALRAM = Path(__file__).parent / "nes_full" / "palram_title.bin"
OUT    = Path(__file__).parent / "intro_title_palette.c"

def main() -> int:
    pal = PALRAM.read_bytes()
    if len(pal) != 32:
        raise ValueError(f"palram_title.bin must be 32 bytes, got {len(pal)}")
    cram = [0] * 64
    for p in range(4):
        for c in range(4):
            cram[p*16 + c]     = nes_color_to_gen_cram(pal[p*4 + c])
            cram[p*16 + 4 + c] = nes_color_to_gen_cram(pal[16 + p*4 + c])

    lines = [
        "/* Auto-generated by tools/intro_demo/extract_title_palette.py */\n",
        "/* NES title PALRAM (frame 100) packed into combined Gen CRAM\n",
        " * layout (BG pals slots 0-3, sprite pals slots 4-7). */\n",
        "const unsigned short intro_title_palette[64] = {\n",
    ]
    for i in range(0, 64, 8):
        lines.append("    " + ", ".join(f"0x{w:04X}" for w in cram[i:i+8]) + ",\n")
    lines.append("};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}")
    print("Sample slots:")
    for p in range(4):
        row = " ".join(f"0x{cram[p*16+c]:04X}" for c in range(8))
        print(f"  pal{p} 0..7: {row}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
