#!/usr/bin/env python3
"""Extract title sprite tiles from a NES CHR snapshot captured at the
title frame (chr_title.bin, 8KB). Sprite pattern table at offset $1000.
Re-encode 256 tiles with color_shift=4.

The .dat files (CommonSpritePatterns + DemoSpritePatterns) are missing
many tiles needed for title sprite rendering (waterfall crests $A2/$A4
etc, sword pieces). The live NES CHR snapshot is the authoritative source.

Output: intro_title_sprite_chr.c
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).parent))
from extract_sprite_chr import nes_tile_to_gen_tile

CHR_TITLE = Path(__file__).parent / "nes_full" / "chr_title.bin"
OUT       = Path(__file__).parent / "intro_title_sprite_chr.c"

def main() -> int:
    chr_data = CHR_TITLE.read_bytes()
    if len(chr_data) != 8192:
        raise ValueError(f"chr_title.bin must be 8192 bytes, got {len(chr_data)}")
    sprite_chr = chr_data[0x1000:0x2000]   # 4KB sprite pattern table
    n_tiles = len(sprite_chr) // 16
    gen = bytearray()
    for T in range(n_tiles):
        tile = sprite_chr[T*16:(T+1)*16]
        gen += nes_tile_to_gen_tile(tile, color_shift=4)

    lines = [
        "/* Auto-generated by tools/intro_demo/extract_title_sprite_chr.py */\n",
        f"/* Title sprite CHR: NES PPU $1000-$1FFF at title frame ({n_tiles} tiles)\n",
        " * 2bpp -> 4bpp Genesis, color_shift=4. Pixel values 1-3 reference\n",
        " * pal slots 5-7 of cell's palette. Uploaded at VRAM $2000 during\n",
        " * the title phase. */\n",
        f"const unsigned char intro_title_sprite_chr[{len(gen)}] = {{\n",
    ]
    for i in range(0, len(gen), 16):
        row = ", ".join(f"0x{b:02X}" for b in gen[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append(f"const unsigned long intro_title_sprite_chr_size = {len(gen)};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}: {len(gen)} bytes ({n_tiles} tiles)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
