#!/usr/bin/env python3
"""Extract title BG tiles from CommonBackgroundPatterns.dat, re-encoded
2bpp -> 4bpp Genesis. Pull the full set of 256 NES BG tiles; the title
tilemap (intro_title_tilemap.c) references a subset by NES tile index.
Genesis VRAM headroom is plenty for 256 tiles (= 8KB at $0000-$1FFF).

Output: intro_title_bg_chr.c with intro_title_bg_chr[] + size constant.
Pixel values 1-3 reference slots 1-3 of cell's palette directly (no
color shift — BG tiles in story+title both use this convention).
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).parent))
from extract_sprite_chr import nes_tile_to_gen_tile

BG_DAT = ROOT / "reference" / "aldonunez" / "dat" / "CommonBackgroundPatterns.dat"
OUT    = Path(__file__).parent / "intro_title_bg_chr.c"

def main() -> int:
    bg_data = BG_DAT.read_bytes()
    n_tiles = len(bg_data) // 16
    gen = bytearray()
    for T in range(n_tiles):
        tile = bg_data[T*16:(T+1)*16]
        gen += nes_tile_to_gen_tile(tile, color_shift=0)

    lines = [
        "/* Auto-generated by tools/intro_demo/extract_title_bg_chr.py */\n",
        f"/* Title BG CHR: NES CommonBackgroundPatterns.dat ({n_tiles} tiles)\n",
        " * 2bpp -> 4bpp Genesis, no color shift. Pixel values 1-3 reference\n",
        " * pal slots 1-3 of cell's palette. Uploaded at VRAM $0000 during\n",
        " * the title phase. */\n",
        f"const unsigned char intro_title_bg_chr[{len(gen)}] = {{\n",
    ]
    for i in range(0, len(gen), 16):
        row = ", ".join(f"0x{b:02X}" for b in gen[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append(f"const unsigned long intro_title_bg_chr_size = {len(gen)};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}: {len(gen)} bytes ({n_tiles} tiles)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
