#!/usr/bin/env python3
"""Convert CommonBackgroundPatterns.dat (NES 2bpp CHR) to Genesis 4bpp CHR
emitted as a C array. This is the FONT data missing from the original
extract_intro_assets.py pipeline.

NES tile = 16 bytes (2 bitplanes of 8 bytes each)
Genesis tile = 32 bytes (4bpp packed pixels, 4 bits per pixel)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC  = ROOT / "reference" / "aldonunez" / "dat" / "CommonBackgroundPatterns.dat"
OUT  = Path(__file__).parent / "intro_common_bg_chr.c"

def nes_tile_to_gen_tile(nes: bytes) -> bytes:
    """16-byte NES 2bpp tile -> 32-byte Genesis 4bpp tile."""
    out = bytearray(32)
    for row in range(8):
        p0 = nes[row]
        p1 = nes[row + 8]
        for col in range(8):
            bit = 7 - col
            color = ((p0 >> bit) & 1) | (((p1 >> bit) & 1) << 1)
            byte_off = row * 4 + col // 2
            if col & 1:
                out[byte_off] |= color & 0x0F
            else:
                out[byte_off] |= (color & 0x0F) << 4
    return bytes(out)

def main() -> int:
    data = SRC.read_bytes()
    if len(data) % 16 != 0:
        print(f"warning: {SRC.name} size {len(data)} not multiple of 16", file=sys.stderr)
    n_tiles = len(data) // 16
    gen = bytearray()
    for i in range(0, len(data) - 15, 16):
        gen += nes_tile_to_gen_tile(data[i:i+16])

    lines = [f"/* Auto-generated by tools/intro_demo/extract_common_bg.py - do not edit. */\n",
             f"/* CommonBackgroundPatterns.dat -> NES tile $00-${n_tiles-1:02X} -> Gen 4bpp */\n",
             f"const unsigned char intro_common_bg_chr[{len(gen)}] = {{\n"]
    for i in range(0, len(gen), 16):
        row = ", ".join(f"0x{b:02X}" for b in gen[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append(f"const unsigned long intro_common_bg_chr_size = {len(gen)};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT} ({len(gen)} bytes Gen CHR = {n_tiles} tiles)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
