#!/usr/bin/env python3
"""Extract NES Zelda sprite CHR (Common + Demo concatenated) -> Genesis 4bpp.

NES sprite layout per Z_01.asm:1604-1614:
  CommonSpritePatterns.dat -> NES PPU $0000 (112 tiles)
  DemoSpritePatterns.dat   -> NES PPU $0700 (144 tiles)

Concatenated into one continuous Genesis CHR blob = 256 NES sprite tiles.
NES tile T -> Genesis tile (sprite_base + T) in our VRAM layout.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COMMON = ROOT / "reference" / "aldonunez" / "dat" / "CommonSpritePatterns.dat"
DEMO   = ROOT / "reference" / "aldonunez" / "dat" / "DemoSpritePatterns.dat"
OUT    = Path(__file__).parent / "intro_sprite_chr.c"

def nes_tile_to_gen_tile(nes: bytes) -> bytes:
    out = bytearray(32)
    for row in range(8):
        p0 = nes[row]; p1 = nes[row + 8]
        for col in range(8):
            bit = 7 - col
            color = ((p0 >> bit) & 1) | (((p1 >> bit) & 1) << 1)
            byte_off = row * 4 + col // 2
            if col & 1:
                out[byte_off] |= color & 0x0F
            else:
                out[byte_off] |= (color & 0x0F) << 4
    return bytes(out)

def main() -> int:
    data = COMMON.read_bytes() + DEMO.read_bytes()
    n_tiles = len(data) // 16
    gen = bytearray()
    for i in range(0, n_tiles * 16, 16):
        gen += nes_tile_to_gen_tile(data[i:i+16])

    lines = [f"/* Auto-generated by tools/intro_demo/extract_sprite_chr.py - do not edit. */\n",
             f"/* Common + Demo sprite patterns: {n_tiles} NES tiles -> {len(gen)} bytes Gen 4bpp */\n",
             f"const unsigned char intro_sprite_chr[{len(gen)}] = {{\n"]
    for i in range(0, len(gen), 16):
        row = ", ".join(f"0x{b:02X}" for b in gen[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append(f"const unsigned long intro_sprite_chr_size = {len(gen)};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}: {len(gen)} bytes ({n_tiles} tiles)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
