#!/usr/bin/env python3
"""Extract HEART/RUPEE/TRIFORCE NES tiles re-encoded with color_shift=8.

These tiles reference Genesis palette slots 8-11 instead of the normal
sprite slots 4-7. Slots 8-11 hold a duplicate of the sprite colors so the
art looks identical at idle, but the demo's per-frame palette animation
toggles slots 8-11 only — making just heart/rupee/triforce blink while
all other items (which still use slots 4-7) stay static.

Output layout (6 NES tiles, 192 bytes Gen 4bpp):
  blob[0] = NES misc tile $F2 (heart top)
  blob[1] = NES misc tile $F3 (heart bot)
  blob[2] = NES sprite tile $32 (rupee top)
  blob[3] = NES sprite tile $33 (rupee bot)
  blob[4] = NES sprite tile $6E (triforce top)
  blob[5] = NES sprite tile $6F (triforce bot)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COMMON_SP = ROOT / "reference" / "aldonunez" / "dat" / "CommonSpritePatterns.dat"
DEMO_SP   = ROOT / "reference" / "aldonunez" / "dat" / "DemoSpritePatterns.dat"
MISC      = ROOT / "reference" / "aldonunez" / "dat" / "CommonMiscPatterns.dat"
OUT       = Path(__file__).parent / "intro_blink_chr.c"

sys.path.insert(0, str(Path(__file__).parent))
from extract_sprite_chr import nes_tile_to_gen_tile

# NES tile indices to re-encode (in this exact order).
# Heart pair: $F2/$F3 from misc CHR (NES tiles $F2-$FF live in CommonMiscPatterns)
# Rupee pair: $32/$33 from sprite CHR
# Triforce pair: $6E/$6F from sprite CHR
# Each entry: (source_table, NES tile, color_shift).
#   shift=8  -> tile pixels reference Genesis palette slots 8-11
#   shift=12 -> tile pixels reference Genesis palette slots 12-15
# Heart (item 0x22): single-tile narrow, NES misc $F2/$F3.
# Container heart (item 0x1A): wide mirror, NES sprite $68/$69.
# Triforce: NES sprite $6E/$6F.
# Rupee (item 0x18): narrow, NES sprite $32/$33. Uses shift=12 so it can
# have its own dedicated palette colors at pal 2 slots 12-15.
TILES = [
    ("misc",   0xF2, 8),
    ("misc",   0xF3, 8),
    ("sprite", 0x68, 8),
    ("sprite", 0x69, 8),
    ("sprite", 0x6E, 8),
    ("sprite", 0x6F, 8),
    ("sprite", 0x32, 12),
    ("sprite", 0x33, 12),
]

def main() -> int:
    sprite_data = COMMON_SP.read_bytes() + DEMO_SP.read_bytes()
    misc_data   = MISC.read_bytes()
    misc_base   = 0xF2  # CommonMiscPatterns starts at NES tile $F2

    gen = bytearray()
    for source, T, shift in TILES:
        if source == "sprite":
            off = T * 16
            tile = sprite_data[off:off+16]
        else:  # misc
            off = (T - misc_base) * 16
            tile = misc_data[off:off+16]
        gen += nes_tile_to_gen_tile(tile, color_shift=shift)

    lines = [f"/* Auto-generated by tools/intro_demo/extract_blink_chr.py - do not edit. */\n",
             f"/* Heart/rupee/triforce tiles encoded with color_shift=8 for blink anim. */\n",
             f"const unsigned char intro_blink_chr[{len(gen)}] = {{\n"]
    for i in range(0, len(gen), 16):
        row = ", ".join(f"0x{b:02X}" for b in gen[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append(f"const unsigned long intro_blink_chr_size = {len(gen)};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}: {len(gen)} bytes ({len(TILES)} tiles)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
