#!/usr/bin/env python3
"""Extract CommonMiscPatterns.dat (NES BG tiles $F2-$FF) to Genesis 4bpp.

Loads to NES PPU $1F20 (per Z_02.asm:64-67). 14 tiles = 224 bytes.
This data is referenced by 8x16 sprite-mode items with ODD tile numbers
(e.g. HEART at tile $F3) — those route to the BG pattern table at $1000+
where tile $F2/$F3 lives.

Output: intro_misc_chr.c with intro_misc_chr[] (14 tiles, 448 bytes Gen 4bpp).
We DON'T color-shift here; these tiles are referenced as BG cells (palette
slots 0-3 expected). Items using these tiles will need their cells to use
appropriate Genesis palette so colors look right.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC  = ROOT / "reference" / "aldonunez" / "dat" / "CommonMiscPatterns.dat"
OUT  = Path(__file__).parent / "intro_misc_chr.c"

sys.path.insert(0, str(Path(__file__).parent))
from extract_sprite_chr import nes_tile_to_gen_tile

def main() -> int:
    data = SRC.read_bytes()
    n_tiles = len(data) // 16
    gen = bytearray()
    for i in range(0, n_tiles * 16, 16):
        # color_shift=4 so these tiles use slots 4-7 (sprite palettes) — items
        # rendered with these tiles use Gen pal 1/2/3 same as other icons.
        gen += nes_tile_to_gen_tile(data[i:i+16], color_shift=4)

    lines = [f"/* Auto-generated by tools/intro_demo/extract_misc_chr.py - do not edit. */\n",
             f"/* CommonMiscPatterns.dat -> NES BG tiles \\$F2-\\$FF -> Gen 4bpp ({n_tiles} tiles) */\n",
             f"const unsigned char intro_misc_chr[{len(gen)}] = {{\n"]
    for i in range(0, len(gen), 16):
        row = ", ".join(f"0x{b:02X}" for b in gen[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append(f"const unsigned long intro_misc_chr_size = {len(gen)};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}: {len(gen)} bytes ({n_tiles} tiles)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
