#!/usr/bin/env python3
"""Build ONE combined Genesis CRAM with both story and treasures palettes
packed into all 64 slots — leveraging Genesis's 16-colors-per-palette.

Layout per Genesis palette:
  slot 0      = backdrop (transparent / black)
  slots 1-3   = NES BG palette colors (story phase)
  slots 4     = backdrop again (so re-encoded sprite tiles also have black bg)
  slots 5-7   = NES sprite palette colors (treasures phase)

Source data:
  Story BG palettes: src/gen/intro_palette.c (already extracted, 4-color
    block per Gen palette in slots 0-3, slots 4-15 = 0).
  Sprite palettes: tools/intro_demo/nes_full/palram_3380.bin
    (NES PALRAM dump at mid-item-scroll).

Output: tools/intro_demo/intro_combined_palette.c
"""
import sys, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
from extract_intro_assets import nes_color_to_gen_cram

STORY_C  = ROOT / "src" / "gen" / "intro_palette.c"
PAL_DUMP = Path(__file__).parent / "nes_full" / "palram_3380.bin"
OUT      = Path(__file__).parent / "intro_combined_palette.c"

def parse_story_cram() -> list[int]:
    txt = STORY_C.read_text()
    words = [int(m, 16) for m in re.findall(r"0x([0-9A-Fa-f]{4})", txt)]
    if len(words) != 64:
        raise ValueError(f"intro_palette has {len(words)} words, expected 64")
    return words

def main() -> int:
    story = parse_story_cram()
    palram = PAL_DUMP.read_bytes()
    if len(palram) != 32:
        raise ValueError(f"palram dump bad size {len(palram)}")

    cram = list(story)  # start with story palette in slots 0-3 of each
    # GameCube-version story-scroll color overrides:
    #   pal 1 color 1 = bright red  (GANON, GANON'S, header THE LEGEND OF ZELDA)
    #   pal 2 color 1 = rupee blue  (PRINCESS, ZELDA)
    #   pal 3 color 1 = bright green (LINK)
    cram[1*16 + 1] = 0x000E   # bright red
    cram[2*16 + 1] = 0x0E88   # rupee blue (NES sprite pal 1 color 2 — light blue rupee body)
    cram[3*16 + 1] = 0x00E0   # bright green
    # NES sprite palettes are at $3F10-$3F1F (palram bytes 16-31).
    # Pack into slots 4-7 of Gen pals 1,2,3 (sprite pal 0 -> Gen pal 1,
    # sprite pal 1 -> Gen pal 2, sprite pal 2 -> Gen pal 3).
    # Slot 4 forced to backdrop (color 0 of sprite pal = $00 grey).
    for sp in range(3):
        for c in range(4):
            nes_color = palram[16 + sp * 4 + c]
            cram[(sp + 1) * 16 + 4 + c] = nes_color_to_gen_cram(nes_color)

    # Emit
    lines = ["/* Auto-generated by tools/intro_demo/extract_combined_palette.py */\n",
             "/* Layout per Genesis palette:\n",
             " *   slots 0-3 = NES BG palette (story phase)\n",
             " *   slots 4-7 = NES sprite palette (treasures phase, items use re-encoded tiles)\n",
             " * Pal 0: text white. Pal 1/2/3: story+sprite combined. */\n",
             "const unsigned short intro_combined_palette[64] = {\n"]
    for i in range(0, 64, 8):
        lines.append("    " + ", ".join(f"0x{w:04X}" for w in cram[i:i+8]) + ",\n")
    lines.append("};\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}")
    print("Sample slots:")
    for p in range(4):
        row = " ".join(f"0x{cram[p*16+c]:04X}" for c in range(8))
        print(f"  pal{p} 0..7: {row}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
