/* Generated by RoomRom/tools/gen_bg_palette_blob.py. Do not edit. */
#include "ow_palette.h"

#include "render_abi.h"    /* render_load_palette */
#include "bg_palette.h"    /* nes_to_cram */
#include "platform_abi.h"  /* nes_ram */
#include "ow_subpal3_table.h"     /* k_ow_subpal3_per_room — NES truth */
#include "ow_bg_palram_table.h"   /* k_ow_bg_palram_per_room — NES truth */

/* Default OW PALRAM. Sub-pal 3 ($3F1C..$3F1F) = $0F $0C $1C $2C
 * (default cyan from LevelInfoOW.dat). NES per-room patch via Z_07.asm:1423
 * PatchAndCueLevelPalettesTransferAndAdvanceSubmode overrides this per
 * @ChooseTileObjPalette dispatch (Z_07.asm:1496-1527). Call
 * roomrom_ow_palette_patch_subpal3 after load_palram_full to apply. */
/* NES OW PALRAM runtime-patched values. Captured live from NES at
 * frame 240 post-warp via probe_nes_full_room_dump.lua across all
 * 128 OW rooms. All rooms share same BG sub-pal 2/3 = $17 $16 $26
 * (Lost Hills brown/red/pink) — overrides LevelInfoOW.dat defaults
 * which had $1A $37 $12 (green) and $17 $37 $12 (brown-green).
 * Sub-pal 3 SPR patched per-room via ow_subpal3_table. */
const unsigned char g_roomrom_ow_palram[2][32] = {
    /* orig */ { 0x0F, 0x30, 0x00, 0x12, 0x0F, 0x16, 0x27, 0x36, 0x0F, 0x17, 0x16, 0x26, 0x0F, 0x17, 0x16, 0x26, 0x0F, 0x29, 0x27, 0x17, 0x0F, 0x02, 0x22, 0x30, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x0C, 0x1C, 0x2C },
    /* redux */ { 0x0F, 0x30, 0x00, 0x12, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x17, 0x16, 0x26, 0x0F, 0x17, 0x16, 0x26, 0x0F, 0x29, 0x27, 0x17, 0x0F, 0x02, 0x22, 0x30, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x0C, 0x1C, 0x2C },
};

/* NES truth lookup. Per-room sub-pal 3 colors captured live from
 * NES Z1 via probe_nes_ow_subpal3_scan.lua. Bypasses NES Z_07.asm
 * @ChooseTileObjPalette dispatch since LevelBlockAttrs SRAM mirror
 * not reliably populated on Gen side. */
const unsigned char *roomrom_ow_palette_get_subpal3_patched(unsigned char room_id)
{
    return k_ow_subpal3_per_room[room_id & 0x7Fu];
}

/* Patch CRAM PAL2[1..3] with per-room sub-pal 3 colors. DISABLED
 * 2026-05-23: PAL2 now holds NES SPR sub-pal 1 (blue ramp) per
 * bg_palette.c, not sub-pal 3. Sub-pal 3 enemies (Blue Moblin etc.)
 * clamp to PAL2 via subpal_routing and render with blue ramp.
 *
 * Trade-off: sub-pal 3 enemies in Lost Hills rooms (where NES
 * $3F1C..$3F1F = $0F/$1C/$16 = black/dark-cyan/red, NOT blue) will
 * render with blue ramp instead of the captured Lost Hills colors.
 * Known regression for Blue Moblin / Blue Goriya / Wizzrobe in OW
 * rooms ~$00..$0F. Census shows ≤16 OW rooms affected; user-reported
 * Blue Lynel/Octorok bug (sub-pal 1, affects 30+ OW rooms) is the
 * dominant case so the swap is net positive.
 *
 * k_ow_subpal3_per_room in ow_subpal3_table.c is now dead data —
 * retained for the eventual sprite CHR 4x expansion (Phase N per
 * docs/superpowers/plans/2026-05-02-roomrom-sprite-chr-expansion-plan.md)
 * which would pack all 4 sub-pals into PAL1 via pixel-bias CHR and
 * route sub-pal 3 enemies to high PAL1 slots holding the per-room
 * patched colors. Until then this function is a no-op to preserve
 * the call-site API in ow_render.c. */
void roomrom_ow_palette_patch_subpal3(unsigned char room_id)
{
    (void)room_id;
}

/* Patch CRAM PAL0[0..15] with per-room NES BG palram bytes.
 * Captured live from NES across 128 OW rooms — values vary per-room
 * (Lost Hills brown for some, default green-OW for others).
 * Called by ow_render after roomrom_bg_palette_load_palram_full to
 * override the static defaults. */
void roomrom_ow_palette_patch_bg_per_room(unsigned char room_id)
{
    const unsigned char *bg = k_ow_bg_palram_per_room[room_id & 0x7Fu];
    unsigned short pal0[16] = {0};
    unsigned char i;
    for (i = 0u; i < 16u; ++i) {
        pal0[i] = roomrom_bg_palette_nes_to_cram(bg[i]);
    }
    render_load_palette(0u, pal0);
}
