/* Generated by RoomRom/tools/gen_bg_palette_blob.py. Do not edit. */
#include "ow_palette.h"

#include "render_abi.h"    /* render_load_palette */
#include "bg_palette.h"    /* nes_to_cram */
#include "platform_abi.h"  /* nes_ram */
#include "ow_subpal3_table.h"  /* k_ow_subpal3_per_room — NES truth */

/* Default OW PALRAM. Sub-pal 3 ($3F1C..$3F1F) = $0F $0C $1C $2C
 * (default cyan from LevelInfoOW.dat). NES per-room patch via Z_07.asm:1423
 * PatchAndCueLevelPalettesTransferAndAdvanceSubmode overrides this per
 * @ChooseTileObjPalette dispatch (Z_07.asm:1496-1527). Call
 * roomrom_ow_palette_patch_subpal3 after load_palram_full to apply. */
const unsigned char g_roomrom_ow_palram[2][32] = {
    /* orig */ { 0x0F, 0x30, 0x00, 0x12, 0x0F, 0x16, 0x27, 0x36, 0x0F, 0x1A, 0x37, 0x12, 0x0F, 0x17, 0x37, 0x12, 0x0F, 0x29, 0x27, 0x17, 0x0F, 0x02, 0x22, 0x30, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x0C, 0x1C, 0x2C },
    /* redux */ { 0x0F, 0x30, 0x00, 0x12, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x1A, 0x37, 0x12, 0x0F, 0x17, 0x37, 0x12, 0x0F, 0x29, 0x27, 0x17, 0x0F, 0x02, 0x22, 0x30, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x0C, 0x1C, 0x2C },
};

/* NES truth lookup. Per-room sub-pal 3 colors captured live from
 * NES Z1 via probe_nes_ow_subpal3_scan.lua. Bypasses NES Z_07.asm
 * @ChooseTileObjPalette dispatch since LevelBlockAttrs SRAM mirror
 * not reliably populated on Gen side. */
const unsigned char *roomrom_ow_palette_get_subpal3_patched(unsigned char room_id)
{
    return k_ow_subpal3_per_room[room_id & 0x7Fu];
}

/* Patch CRAM PAL2[1..3] with per-room sub-pal 3 colors. Called by
 * ow_render after roomrom_bg_palette_load_palram_full. PAL2 currently
 * holds NES SPR sub-pal 3 per bg_palette.c. */
void roomrom_ow_palette_patch_subpal3(unsigned char room_id)
{
    const unsigned char *colors = roomrom_ow_palette_get_subpal3_patched(room_id);
    unsigned short pal2[16] = {0};
    pal2[1] = roomrom_bg_palette_nes_to_cram(colors[1]);
    pal2[2] = roomrom_bg_palette_nes_to_cram(colors[2]);
    pal2[3] = roomrom_bg_palette_nes_to_cram(colors[3]);
    render_load_palette(2u, pal2);
}
