"""Tests for emit_gen_wrappers.py. Run:
    python -m unittest tools.gen_wrappers.test_emit_gen_wrappers
"""
from __future__ import annotations

import importlib.util
import json
import os
import tempfile
import textwrap
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOL_PATH = ROOT / "tools" / "emit_gen_wrappers.py"


def load_tool():
    spec = importlib.util.spec_from_file_location("emit_gen_wrappers", TOOL_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class SigTests(unittest.TestCase):
    def setUp(self):
        self.mod = load_tool()

    def test_void_no_args(self):
        self.assertEqual(self.mod.parse_sig("void ()"),
                         ("void", []))

    def test_void_one_arg(self):
        self.assertEqual(self.mod.parse_sig("void (unsigned int slot)"),
                         ("void", [("unsigned int", "slot")]))

    def test_return_type_two_args(self):
        self.assertEqual(
            self.mod.parse_sig("unsigned char (unsigned char a, unsigned int b)"),
            ("unsigned char", [("unsigned char", "a"), ("unsigned int", "b")]))

    def test_bad_sig_raises(self):
        with self.assertRaises(ValueError):
            self.mod.parse_sig("double ()")


class RenderTests(unittest.TestCase):
    def setUp(self):
        self.mod = load_tool()

    def test_void_body(self):
        out = self.mod.render_forwarder(
            {"old": "z05_foo", "new": "roomxf_foo", "sig": "void ()"})
        self.assertEqual(
            out.strip(),
            "void z05_foo(void) {\n    roomxf_foo();\n}")

    def test_return_body(self):
        out = self.mod.render_forwarder(
            {"old": "z05_bar", "new": "roomrt_bar",
             "sig": "unsigned char (unsigned int slot)"})
        self.assertEqual(
            out.strip(),
            "unsigned char z05_bar(unsigned int slot) {\n"
            "    return roomrt_bar(slot);\n}")

    def test_args_forwarded_by_name(self):
        out = self.mod.render_forwarder(
            {"old": "z05_baz", "new": "roomrt_baz",
             "sig": "void (unsigned int a, unsigned char b)"})
        self.assertIn("roomrt_baz(a, b)", out)


class HeaderMapTests(unittest.TestCase):
    def setUp(self):
        self.mod = load_tool()

    def test_known_prefix(self):
        self.assertEqual(self.mod.header_for("roomxf_foo"),
                         "room_transfer_runtime.h")

    def test_unknown_prefix(self):
        self.assertIsNone(self.mod.header_for("xyz_unknown"))


class RegionTests(unittest.TestCase):
    def setUp(self):
        self.mod = load_tool()

    def test_replace_between_markers(self):
        source = textwrap.dedent("""
            /* header comment */
            #include "foo.h"

            /* <<< auto-wrappers: z_05 (generated by tools/emit_gen_wrappers.py) >>> */
            OLD CONTENT
            /* <<< end auto-wrappers >>> */

            /* footer comment */
        """).lstrip()
        new = self.mod.replace_region(source, "z_05", "NEW CONTENT\n")
        self.assertIn("NEW CONTENT", new)
        self.assertNotIn("OLD CONTENT", new)
        self.assertIn("/* header comment */", new)
        self.assertIn("/* footer comment */", new)

    def test_missing_markers_appends(self):
        source = '#include "foo.h"\n'
        new = self.mod.replace_region(source, "z_05", "FORWARDERS\n")
        self.assertIn("/* <<< auto-wrappers: z_05", new)
        self.assertIn("FORWARDERS", new)
        self.assertIn("/* <<< end auto-wrappers >>> */", new)


class IdempotencyTests(unittest.TestCase):
    def setUp(self):
        self.mod = load_tool()

    def test_double_run_stable(self):
        manifest = {
            "bank": "z_05",
            "includes": ["room_transfer_runtime.h"],
            "symbols": [
                {"old": "z05_foo", "new": "roomxf_foo", "sig": "void ()"},
                {"old": "z05_bar", "new": "roomxf_bar",
                 "sig": "unsigned char (unsigned int slot)"},
            ],
        }
        with tempfile.TemporaryDirectory() as d:
            src = Path(d) / "z_05.c"
            src.write_text("/* z_05.c */\n#include \"../nes_abi.h\"\n")
            self.mod.apply_manifest(manifest, src)
            first = src.read_text()
            self.mod.apply_manifest(manifest, src)
            second = src.read_text()
            self.assertEqual(first, second)


class CheckModeTests(unittest.TestCase):
    def setUp(self):
        self.mod = load_tool()

    def test_check_passes_on_clean(self):
        manifest = {
            "bank": "z_05",
            "includes": [],
            "symbols": [
                {"old": "z05_foo", "new": "roomxf_foo", "sig": "void ()"},
            ],
        }
        with tempfile.TemporaryDirectory() as d:
            src = Path(d) / "z_05.c"
            src.write_text("/* z_05.c */\n")
            self.mod.apply_manifest(manifest, src)
            drift = self.mod.check_manifest(manifest, src)
            self.assertFalse(drift)

    def test_check_fails_on_drift(self):
        manifest = {
            "bank": "z_05",
            "includes": [],
            "symbols": [
                {"old": "z05_foo", "new": "roomxf_foo", "sig": "void ()"},
            ],
        }
        with tempfile.TemporaryDirectory() as d:
            src = Path(d) / "z_05.c"
            src.write_text("/* z_05.c */\n")
            self.mod.apply_manifest(manifest, src)
            polluted = src.read_text().replace(
                "roomxf_foo();",
                "roomxf_foo(); /* hand-edited */")
            src.write_text(polluted)
            drift = self.mod.check_manifest(manifest, src)
            self.assertTrue(drift)


class DuplicateSymbolTests(unittest.TestCase):
    def setUp(self):
        self.mod = load_tool()

    def test_duplicate_old_rejected(self):
        manifest = {
            "bank": "z_05",
            "includes": [],
            "symbols": [
                {"old": "z05_foo", "new": "roomxf_foo", "sig": "void ()"},
                {"old": "z05_foo", "new": "roomxf_bar", "sig": "void ()"},
            ],
        }
        with self.assertRaises(ValueError):
            self.mod.render_bank(manifest)


if __name__ == "__main__":
    unittest.main()
