-- bizhawk_t36_input_recorder.lua
-- Loop-based recorder. Advances frames explicitly, reads user input each
-- frame, logs it. User input passes through (we never call joypad.set).
-- Dumps on cap OR on BizHawk exit.

dofile((function()
    local env_root = os.getenv("CODEX_BIZHAWK_ROOT")
    if env_root and env_root ~= "" then
        env_root = env_root:gsub("/", "\\")
        return env_root .. "\\tools\\probe_root.lua"
    end
    local source = debug.getinfo(1, "S").source
    if source:sub(1, 1) == "@" then source = source:sub(2) end
    source = source:gsub("/", "\\")
    local tools_dir = source:match("^(.*)\\[^\\]+$")
    return tools_dir .. "\\probe_root.lua"
end)())

local OUT_TXT  = repo_path("builds\\reports\\t36_input_recording.txt")
local OUT_LUA  = repo_path("builds\\reports\\t36_input_recording.lua")
local OUT_JSON = repo_path("builds\\reports\\t36_input_recording.json")

local RECORD_FRAMES = 6000

local ADDR_MODE    = 0x0012
local ADDR_ROOM_ID = 0x00EB
local ADDR_OBJ_X   = 0x0070
local ADDR_OBJ_Y   = 0x0084

local txt = io.open(OUT_TXT, "w")
local function log(s)
    if txt then pcall(function() txt:write(s .. "\n"); txt:flush() end) end
    print(s)
end

log("T36 user-drive recorder (loop mode).")
log("Play from boot; close BizHawk window when done (auto-dumps).")

local BUTTONS = {
    "P1 Up", "P1 Down", "P1 Left", "P1 Right",
    "P1 A",  "P1 B",    "P1 Start", "P1 Select",
}

local frames = {}
local dumped = false

local function dump_outputs()
    if dumped then return end
    dumped = true
    local lua = io.open(OUT_LUA, "w")
    lua:write("-- Auto-generated by bizhawk_t36_input_recorder.lua\n")
    lua:write("return {\n")
    for _, ent in ipairs(frames) do
        local btns = {}
        for _, b in ipairs(ent.buttons) do
            btns[#btns + 1] = string.format("%q", b:gsub("^P1 ", ""))
        end
        lua:write(string.format(
            "  { f=%d, btns={%s}, mode=0x%02X, room=0x%02X, x=0x%02X, y=0x%02X },\n",
            ent.frame, table.concat(btns, ","), ent.mode, ent.room, ent.x, ent.y))
    end
    lua:write("}\n"); lua:close()

    local function jesc(s) return '"' .. s:gsub('"', '\\"') .. '"' end
    local json = io.open(OUT_JSON, "w")
    json:write("{\n  \"record_frames\": " .. #frames .. ",\n  \"frames\": [\n")
    for i, ent in ipairs(frames) do
        local btns = {}
        for _, b in ipairs(ent.buttons) do
            btns[#btns + 1] = jesc(b:gsub("^P1 ", ""))
        end
        local comma = (i < #frames) and "," or ""
        json:write(string.format(
            "    {\"f\":%d,\"btns\":[%s],\"mode\":%d,\"room\":%d,\"x\":%d,\"y\":%d}%s\n",
            ent.frame, table.concat(btns, ","), ent.mode, ent.room, ent.x, ent.y, comma))
    end
    json:write("  ]\n}\n"); json:close()
    log("Dumped " .. #frames .. " frames to " .. OUT_LUA)
end

event.onexit(function()
    pcall(function()
        print("onexit: dumping " .. #frames .. " frames")
        dump_outputs()
    end)
end)

for f = 1, RECORD_FRAMES do
    local input = joypad.get(1) or {}
    local pressed = {}
    for _, b in ipairs(BUTTONS) do
        local bare = b:gsub("^P1 ", "")
        if input[b] or input[bare] then
            pressed[#pressed + 1] = b
        end
    end
    table.sort(pressed)

    memory.usememorydomain("RAM")
    local mode = memory.read_u8(ADDR_MODE)
    local room = memory.read_u8(ADDR_ROOM_ID)
    local x    = memory.read_u8(ADDR_OBJ_X)
    local y    = memory.read_u8(ADDR_OBJ_Y)

    frames[#frames + 1] = {
        frame = f, buttons = pressed, mode = mode, room = room, x = x, y = y,
    }

    if (f % 60) == 0 then
        log(string.format("f%04d mode=$%02X room=$%02X x=$%02X y=$%02X btns=[%s]",
            f, mode, room, x, y, table.concat(pressed, ",")))
    end

    emu.frameadvance()
end

log("Hit RECORD_FRAMES cap")
dump_outputs()
txt:close()
client.pause()
