#!/usr/bin/env python3
"""Data pipeline orchestrator (S2 Phase A1).

Walks the current `data/` tree, computes SHA256 for every file, writes
`data/MANIFEST.sha256` in stable sort order. Run by `build.bat` to keep
the manifest in sync with whatever the active extractors produced.

This is the MVP at S2 start. As individual extractors are ported into
the role-based `data/{chr,audio,rooms,enemies,...}/` tree (S2 Phases B-D),
add their invocation to `RUN_EXTRACTORS` so a single command produces
every byte under `data/`.

Reproducibility check is `tools/probes/check_data_manifest.py` -- it
re-runs this script to a temp dir and diffs the produced manifest
against the committed one.
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data"
MANIFEST_PATH = DATA_DIR / "MANIFEST.sha256"

# Extractors that should run as part of the canonical pipeline. Each entry
# is the path to a Python script; ordering matters for deterministic
# emission (same script always emits the same paths). Already wired into
# build.bat phase 2a.0/2a.0b are extract_intro_assets.py + extract_fs_assets.py;
# they run there and emit into data/intro/ and data/fs/ respectively, so
# we do NOT list them here (they would double-run).
RUN_EXTRACTORS: list[Path] = [
    # S2 Phase B: extract_chr.py -> data/chr/
    REPO_ROOT / "tools" / "extract_chr.py",
    # S2 Phase C: extract_audio.py, extract_rooms.py, extract_enemies.py
    REPO_ROOT / "tools" / "extract_audio.py",
    REPO_ROOT / "tools" / "extract_rooms.py",
    REPO_ROOT / "tools" / "extract_enemies.py",
    # S2 Phase D: extract_misc.py, extract_demo_text.py, extract_frontend.py
    # extract_demo_text.py runs before extract_frontend.py so the text/ MANIFEST
    # is created first and extract_frontend.py can merge into it.
    REPO_ROOT / "tools" / "extract_misc.py",
    REPO_ROOT / "tools" / "extract_demo_text.py",
    REPO_ROOT / "tools" / "extract_frontend.py",
    # extract_dat_sidecars.py is intentionally NOT listed here: it writes
    # reference/aldonunez/dat/ for the transpiler, not the data/ tree.
]


def hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def walk_data() -> list[tuple[str, str]]:
    """Return [(rel_posix_path, sha256_hex), ...] for every file under data/.

    Excludes the manifest itself (would create a fixed-point dependency)
    and any .gitkeep placeholders.
    """
    out: list[tuple[str, str]] = []
    for path in sorted(DATA_DIR.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(DATA_DIR).as_posix()
        if rel == "MANIFEST.sha256":
            continue
        if path.name == ".gitkeep":
            continue
        out.append((rel, hash_file(path)))
    return out


def write_manifest(entries: list[tuple[str, str]]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with MANIFEST_PATH.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# data/MANIFEST.sha256 -- auto-generated by tools/build_data.py.\n")
        f.write("# Do not edit by hand. Re-run tools/build_data.py after\n")
        f.write("# any extractor changes its output. CI verifies against this\n")
        f.write("# file via tools/probes/check_data_manifest.py.\n")
        for rel, sha in entries:
            f.write(f"{sha}  {rel}\n")


def run_extractors(target_root: Path | None = None) -> int:
    """Run every entry in RUN_EXTRACTORS. target_root overrides the data/
    tree root for the reproducibility check; each script receives
    --out-dir pointing to the appropriate subdirectory. Real extractors
    write to repo data/ when target_root is None.
    """
    # Map each extractor script name to the data/ subdirectory it owns.
    # Extractors that do not appear here write to their default location.
    SUBDIR_MAP: dict[str, str] = {
        "extract_chr.py": "chr",
        "extract_audio.py": "audio",
        "extract_rooms.py": "rooms",
        "extract_enemies.py": "enemies",
        "extract_misc.py": "misc",
        "extract_demo_text.py": "text",
        "extract_frontend.py": "text",
    }

    for script in RUN_EXTRACTORS:
        cmd = [sys.executable, str(script)]
        if target_root is not None:
            subdir = SUBDIR_MAP.get(script.name, "")
            out_dir = target_root / subdir if subdir else target_root
            cmd += ["--out-dir", str(out_dir)]
        rc = subprocess.run(cmd, check=False).returncode
        if rc != 0:
            sys.stderr.write(f"[build_data] extractor failed: {script}\n")
            return rc
    return 0


def main(argv: list[str]) -> int:
    rc = run_extractors()
    if rc != 0:
        return rc
    entries = walk_data()
    write_manifest(entries)
    print(f"[build_data] manifested {len(entries)} files to {MANIFEST_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
