-- Generated by tools/parse_lst.py. Do not edit by hand.
-- Source: builds\whatif.lst
cycle_profile_buckets = {
  {
    name = "VBlankISR",
    tier = "T1",
    entry_addr = 0x00000222,
    static_insts = 12,
    exit_addr = 0x0000025C,
    exit_kind = "rte",
    call_sites = {
    },
  },
  {
    name = "IsrNmi",
    tier = "T1",
    entry_addr = 0x0004B14E,
    static_insts = 132,
    call_sites = {
      { call_addr = 0x00000248, return_addr = 0x0000024E, caller_src = "genesis_shell.asm", caller_line = 479, mnemonic = "jsr" },
    },
  },
  {
    name = "UpdateMode",
    tier = "T1",
    entry_addr = 0x0004BD5E,
    static_insts = 33,
    call_sites = {
      { call_addr = 0x0004B2F2, return_addr = 0x0004B2F6, caller_src = "zelda_translated\\z_07.asm", caller_line = 1644, mnemonic = "jsr" },
    },
  },
  {
    name = "TransferCurTileBuf",
    tier = "T2",
    entry_addr = 0x00047FEC,
    static_insts = 15,
    call_sites = {
      { call_addr = 0x0004B1C2, return_addr = 0x0004B1C6, caller_src = "zelda_translated\\z_07.asm", caller_line = 1517, mnemonic = "jsr" },
    },
  },
  {
    name = "music_tick",
    tier = "T2",
    entry_addr = 0x00000670,
    static_insts = 29,
    call_sites = {
      { call_addr = 0x0000024E, return_addr = 0x00000252, caller_src = "genesis_shell.asm", caller_line = 482, mnemonic = "bsr" },
    },
  },
  {
    name = "UpdatePlayer",
    tier = "T3",
    entry_addr = 0x0004C14E,
    static_insts = 40,
    call_sites = {
      { call_addr = 0x00045280, return_addr = 0x00045284, caller_src = "zelda_translated\\z_05.asm", caller_line = 8633, mnemonic = "jsr" },
      { call_addr = 0x0004BF92, return_addr = 0x0004BF96, caller_src = "zelda_translated\\z_07.asm", caller_line = 3294, mnemonic = "jsr" },
    },
  },
  {
    name = "UpdateObject",
    tier = "T3",
    entry_addr = 0x0004DC5E,
    static_insts = 148,
    call_sites = {
      { call_addr = 0x0004C032, return_addr = 0x0004C036, caller_src = "zelda_translated\\z_07.asm", caller_line = 3374, mnemonic = "jsr" },
    },
  },
  {
    name = "CheckMonsterCollisions",
    tier = "T3",
    entry_addr = 0x0003142E,
    static_insts = 41,
    call_sites = {
      { call_addr = 0x0002DDC2, return_addr = 0x0002DDC6, caller_src = "zelda_translated\\z_01.asm", caller_line = 1556, mnemonic = "jsr" },
      { call_addr = 0x00031410, return_addr = 0x00031412, caller_src = "zelda_translated\\z_01.asm", caller_line = 6908, mnemonic = "jsr" },
      { call_addr = 0x00039EE2, return_addr = 0x00039EE8, caller_src = "zelda_translated\\z_04.asm", caller_line = 1516, mnemonic = "jsr" },
      { call_addr = 0x0003ABC0, return_addr = 0x0003ABC6, caller_src = "zelda_translated\\z_04.asm", caller_line = 3385, mnemonic = "jsr" },
      { call_addr = 0x0003AEF0, return_addr = 0x0003AEF6, caller_src = "zelda_translated\\z_04.asm", caller_line = 3821, mnemonic = "jsr" },
      { call_addr = 0x0003B0F8, return_addr = 0x0003B0FE, caller_src = "zelda_translated\\z_04.asm", caller_line = 4156, mnemonic = "jsr" },
      { call_addr = 0x0003B95C, return_addr = 0x0003B962, caller_src = "zelda_translated\\z_04.asm", caller_line = 5337, mnemonic = "jsr" },
      { call_addr = 0x0003BCEC, return_addr = 0x0003BCF2, caller_src = "zelda_translated\\z_04.asm", caller_line = 5768, mnemonic = "jsr" },
      { call_addr = 0x0003BF48, return_addr = 0x0003BF4E, caller_src = "zelda_translated\\z_04.asm", caller_line = 6076, mnemonic = "jsr" },
      { call_addr = 0x0003C1EE, return_addr = 0x0003C1F4, caller_src = "zelda_translated\\z_04.asm", caller_line = 6526, mnemonic = "jsr" },
      { call_addr = 0x0003C258, return_addr = 0x0003C25E, caller_src = "zelda_translated\\z_04.asm", caller_line = 6574, mnemonic = "jsr" },
      { call_addr = 0x0003C594, return_addr = 0x0003C59A, caller_src = "zelda_translated\\z_04.asm", caller_line = 6951, mnemonic = "jsr" },
      { call_addr = 0x0003C9A2, return_addr = 0x0003C9A8, caller_src = "zelda_translated\\z_04.asm", caller_line = 7526, mnemonic = "jsr" },
      { call_addr = 0x0003CCCC, return_addr = 0x0003CCD2, caller_src = "zelda_translated\\z_04.asm", caller_line = 8028, mnemonic = "jsr" },
      { call_addr = 0x0003CCF0, return_addr = 0x0003CCF6, caller_src = "zelda_translated\\z_04.asm", caller_line = 8039, mnemonic = "jsr" },
      { call_addr = 0x0003CECE, return_addr = 0x0003CED4, caller_src = "zelda_translated\\z_04.asm", caller_line = 8284, mnemonic = "jsr" },
      { call_addr = 0x0003D0BC, return_addr = 0x0003D0C2, caller_src = "zelda_translated\\z_04.asm", caller_line = 8513, mnemonic = "jsr" },
      { call_addr = 0x0003D16E, return_addr = 0x0003D174, caller_src = "zelda_translated\\z_04.asm", caller_line = 8594, mnemonic = "jsr" },
      { call_addr = 0x0003D252, return_addr = 0x0003D258, caller_src = "zelda_translated\\z_04.asm", caller_line = 8707, mnemonic = "jsr" },
      { call_addr = 0x0003DBA4, return_addr = 0x0003DBAA, caller_src = "zelda_translated\\z_04.asm", caller_line = 9967, mnemonic = "jsr" },
      { call_addr = 0x0003E01C, return_addr = 0x0003E022, caller_src = "zelda_translated\\z_04.asm", caller_line = 10577, mnemonic = "jsr" },
      { call_addr = 0x0003E0E0, return_addr = 0x0003E0E6, caller_src = "zelda_translated\\z_04.asm", caller_line = 10669, mnemonic = "jsr" },
      { call_addr = 0x0003E6A0, return_addr = 0x0003E6A6, caller_src = "zelda_translated\\z_04.asm", caller_line = 11461, mnemonic = "jsr" },
      { call_addr = 0x0003EBDC, return_addr = 0x0003EBE2, caller_src = "zelda_translated\\z_04.asm", caller_line = 12140, mnemonic = "jsr" },
      { call_addr = 0x0003EC6A, return_addr = 0x0003EC70, caller_src = "zelda_translated\\z_04.asm", caller_line = 12214, mnemonic = "jsr" },
      { call_addr = 0x0003EF8A, return_addr = 0x0003EF90, caller_src = "zelda_translated\\z_04.asm", caller_line = 12660, mnemonic = "jsr" },
      { call_addr = 0x0003F16E, return_addr = 0x0003F174, caller_src = "zelda_translated\\z_04.asm", caller_line = 12924, mnemonic = "jsr" },
      { call_addr = 0x0004C06E, return_addr = 0x0004C074, caller_src = "zelda_translated\\z_07.asm", caller_line = 3401, mnemonic = "jsr" },
    },
  },
  {
    name = "MoveObject",
    tier = "T3",
    entry_addr = 0x0004C6FC,
    static_insts = 23,
    call_sites = {
      { call_addr = 0x0002FB50, return_addr = 0x0002FB56, caller_src = "zelda_translated\\z_01.asm", caller_line = 3405, mnemonic = "jsr" },
      { call_addr = 0x000303BC, return_addr = 0x000303C2, caller_src = "zelda_translated\\z_01.asm", caller_line = 4710, mnemonic = "jsr" },
      { call_addr = 0x00039A56, return_addr = 0x00039A5C, caller_src = "zelda_translated\\z_04.asm", caller_line = 920, mnemonic = "jsr" },
      { call_addr = 0x00039B78, return_addr = 0x00039B7E, caller_src = "zelda_translated\\z_04.asm", caller_line = 1081, mnemonic = "jsr" },
      { call_addr = 0x00039DC8, return_addr = 0x00039DCE, caller_src = "zelda_translated\\z_04.asm", caller_line = 1374, mnemonic = "jsr" },
      { call_addr = 0x0003A1D4, return_addr = 0x0003A1DA, caller_src = "zelda_translated\\z_04.asm", caller_line = 1937, mnemonic = "jsr" },
      { call_addr = 0x0003AD7E, return_addr = 0x0003AD84, caller_src = "zelda_translated\\z_04.asm", caller_line = 3627, mnemonic = "jsr" },
      { call_addr = 0x0003B344, return_addr = 0x0003B34A, caller_src = "zelda_translated\\z_04.asm", caller_line = 4503, mnemonic = "jsr" },
      { call_addr = 0x0003B8C2, return_addr = 0x0003B8C8, caller_src = "zelda_translated\\z_04.asm", caller_line = 5264, mnemonic = "jsr" },
      { call_addr = 0x00045204, return_addr = 0x00045208, caller_src = "zelda_translated\\z_05.asm", caller_line = 8569, mnemonic = "jsr" },
      { call_addr = 0x0004BE74, return_addr = 0x0004BE78, caller_src = "zelda_translated\\z_07.asm", caller_line = 3138, mnemonic = "jsr" },
      { call_addr = 0x0004D232, return_addr = 0x0004D236, caller_src = "zelda_translated\\z_07.asm", caller_line = 6106, mnemonic = "jsr" },
      { call_addr = 0x0004D314, return_addr = 0x0004D318, caller_src = "zelda_translated\\z_07.asm", caller_line = 6242, mnemonic = "jsr" },
      { call_addr = 0x0004D33E, return_addr = 0x0004D342, caller_src = "zelda_translated\\z_07.asm", caller_line = 6255, mnemonic = "jsr" },
      { call_addr = 0x0004D742, return_addr = 0x0004D746, caller_src = "zelda_translated\\z_07.asm", caller_line = 6799, mnemonic = "jsr" },
    },
  },
  {
    name = "Walker_Move",
    tier = "T4",
    entry_addr = 0x0004C5D2,
    static_insts = 115,
    call_sites = {
      { call_addr = 0x00039624, return_addr = 0x0003962A, caller_src = "zelda_translated\\z_04.asm", caller_line = 368, mnemonic = "jsr" },
      { call_addr = 0x0003975A, return_addr = 0x00039760, caller_src = "zelda_translated\\z_04.asm", caller_line = 531, mnemonic = "jsr" },
      { call_addr = 0x0003BB86, return_addr = 0x0003BB8C, caller_src = "zelda_translated\\z_04.asm", caller_line = 5620, mnemonic = "jsr" },
      { call_addr = 0x0004C180, return_addr = 0x0004C184, caller_src = "zelda_translated\\z_07.asm", caller_line = 3537, mnemonic = "jsr" },
    },
  },
  {
    name = "Walker_CheckTileCollision",
    tier = "T4",
    entry_addr = 0x0004C7DA,
    static_insts = 53,
    call_sites = {
      { call_addr = 0x0004C6E6, return_addr = 0x0004C6EA, caller_src = "zelda_translated\\z_07.asm", caller_line = 4348, mnemonic = "jsr" },
    },
  },
  {
    name = "UpdateMoblin",
    tier = "T4",
    entry_addr = 0x0003A512,
    static_insts = 65,
    call_sites = {
    },
  },
  {
    name = "UpdateArrowOrBoomerang",
    tier = "T4",
    entry_addr = 0x0004CFEE,
    static_insts = 125,
    call_sites = {
      { call_addr = 0x0003A644, return_addr = 0x0003A64A, caller_src = "zelda_translated\\z_04.asm", caller_line = 2646, mnemonic = "jsr" },
    },
  },
  {
    name = "AnimateAndDrawObjectWalking",
    tier = "T4",
    entry_addr = 0x0003109E,
    static_insts = 135,
    call_sites = {
      { call_addr = 0x0004C062, return_addr = 0x0004C068, caller_src = "zelda_translated\\z_07.asm", caller_line = 3395, mnemonic = "jsr" },
    },
  },
  {
    name = "AddQSpeedToPositionFraction",
    tier = "T4",
    entry_addr = 0x00030290,
    static_insts = 36,
    call_sites = {
    },
  },
  {
    name = "SubQSpeedFromPositionFraction",
    tier = "T4",
    entry_addr = 0x000302FA,
    static_insts = 41,
    call_sites = {
    },
  },
  {
    name = "TryNextDir",
    tier = "T4",
    entry_addr = 0x0004C86A,
    static_insts = 6,
    call_sites = {
    },
  },
  {
    name = "GetCollidableTile",
    tier = "T4",
    entry_addr = 0x0004C210,
    static_insts = 135,
    call_sites = {
      { call_addr = 0x0003D01E, return_addr = 0x0003D024, caller_src = "zelda_translated\\z_04.asm", caller_line = 8444, mnemonic = "jsr" },
    },
  },
  {
    name = "_oam_dma_flush",
    tier = "derived",
    entry_addr = 0x0002ACE6,
    static_insts = 29,
    call_sites = {
      { call_addr = 0x00000236, return_addr = 0x0000023C, caller_src = "genesis_shell.asm", caller_line = 466, mnemonic = "bsr" },
    },
  },
  {
    name = "_ags_flush",
    tier = "derived",
    entry_addr = 0x0000E188,
    static_insts = 12,
    call_sites = {
      { call_addr = 0x00000252, return_addr = 0x00000258, caller_src = "genesis_shell.asm", caller_line = 490, mnemonic = "bsr" },
    },
  },
  {
    name = "_ags_prearm",
    tier = "derived",
    entry_addr = 0x0000E1B8,
    static_insts = 5,
    call_sites = {
      { call_addr = 0x0000023C, return_addr = 0x00000242, caller_src = "genesis_shell.asm", caller_line = 472, mnemonic = "bsr" },
    },
  },
  {
    name = "DriveAudio",
    tier = "derived",
    entry_addr = 0x0002C11A,
    static_insts = 1,
    call_sites = {
      { call_addr = 0x0004B2DC, return_addr = 0x0004B2E2, caller_src = "zelda_translated\\z_07.asm", caller_line = 1635, mnemonic = "jsr" },
    },
  },
}
cycle_profile_missing = {}
