-- Generated by tools/parse_lst.py. Do not edit by hand.
-- Source: builds\whatif.lst
cycle_profile_buckets = {
  {
    name = "VBlankISR",
    tier = "T1",
    entry_addr = 0x00000422,
    static_insts = 12,
    exit_addr = 0x0000045C,
    exit_kind = "rte",
    call_sites = {
    },
  },
  {
    name = "IsrNmi",
    tier = "T1",
    entry_addr = 0x0004B34C,
    static_insts = 132,
    call_sites = {
      { call_addr = 0x00000448, return_addr = 0x0000044E, caller_src = "genesis_shell.asm", caller_line = 476, mnemonic = "jsr" },
    },
  },
  {
    name = "UpdateMode",
    tier = "T1",
    entry_addr = 0x0004BF5C,
    static_insts = 33,
    call_sites = {
      { call_addr = 0x0004B4F0, return_addr = 0x0004B4F4, caller_src = "zelda_translated\\z_07.asm", caller_line = 1644, mnemonic = "jsr" },
    },
  },
  {
    name = "TransferCurTileBuf",
    tier = "T2",
    entry_addr = 0x000481EA,
    static_insts = 15,
    call_sites = {
      { call_addr = 0x0004B3C0, return_addr = 0x0004B3C4, caller_src = "zelda_translated\\z_07.asm", caller_line = 1517, mnemonic = "jsr" },
    },
  },
  {
    name = "music_tick",
    tier = "T2",
    entry_addr = 0x00000870,
    static_insts = 29,
    call_sites = {
      { call_addr = 0x0000044E, return_addr = 0x00000452, caller_src = "genesis_shell.asm", caller_line = 479, mnemonic = "bsr" },
    },
  },
  {
    name = "UpdatePlayer",
    tier = "T3",
    entry_addr = 0x0004C34C,
    static_insts = 40,
    call_sites = {
      { call_addr = 0x0004547E, return_addr = 0x00045482, caller_src = "zelda_translated\\z_05.asm", caller_line = 8633, mnemonic = "jsr" },
      { call_addr = 0x0004C190, return_addr = 0x0004C194, caller_src = "zelda_translated\\z_07.asm", caller_line = 3294, mnemonic = "jsr" },
    },
  },
  {
    name = "UpdateObject",
    tier = "T3",
    entry_addr = 0x0004DE5C,
    static_insts = 148,
    call_sites = {
      { call_addr = 0x0004C230, return_addr = 0x0004C234, caller_src = "zelda_translated\\z_07.asm", caller_line = 3374, mnemonic = "jsr" },
    },
  },
  {
    name = "CheckMonsterCollisions",
    tier = "T3",
    entry_addr = 0x0003162C,
    static_insts = 41,
    call_sites = {
      { call_addr = 0x0002DFC0, return_addr = 0x0002DFC4, caller_src = "zelda_translated\\z_01.asm", caller_line = 1556, mnemonic = "jsr" },
      { call_addr = 0x0003160E, return_addr = 0x00031610, caller_src = "zelda_translated\\z_01.asm", caller_line = 6908, mnemonic = "jsr" },
      { call_addr = 0x0003A0E0, return_addr = 0x0003A0E6, caller_src = "zelda_translated\\z_04.asm", caller_line = 1516, mnemonic = "jsr" },
      { call_addr = 0x0003ADBE, return_addr = 0x0003ADC4, caller_src = "zelda_translated\\z_04.asm", caller_line = 3385, mnemonic = "jsr" },
      { call_addr = 0x0003B0EE, return_addr = 0x0003B0F4, caller_src = "zelda_translated\\z_04.asm", caller_line = 3821, mnemonic = "jsr" },
      { call_addr = 0x0003B2F6, return_addr = 0x0003B2FC, caller_src = "zelda_translated\\z_04.asm", caller_line = 4156, mnemonic = "jsr" },
      { call_addr = 0x0003BB5A, return_addr = 0x0003BB60, caller_src = "zelda_translated\\z_04.asm", caller_line = 5337, mnemonic = "jsr" },
      { call_addr = 0x0003BEEA, return_addr = 0x0003BEF0, caller_src = "zelda_translated\\z_04.asm", caller_line = 5768, mnemonic = "jsr" },
      { call_addr = 0x0003C146, return_addr = 0x0003C14C, caller_src = "zelda_translated\\z_04.asm", caller_line = 6076, mnemonic = "jsr" },
      { call_addr = 0x0003C3EC, return_addr = 0x0003C3F2, caller_src = "zelda_translated\\z_04.asm", caller_line = 6526, mnemonic = "jsr" },
      { call_addr = 0x0003C456, return_addr = 0x0003C45C, caller_src = "zelda_translated\\z_04.asm", caller_line = 6574, mnemonic = "jsr" },
      { call_addr = 0x0003C792, return_addr = 0x0003C798, caller_src = "zelda_translated\\z_04.asm", caller_line = 6951, mnemonic = "jsr" },
      { call_addr = 0x0003CBA0, return_addr = 0x0003CBA6, caller_src = "zelda_translated\\z_04.asm", caller_line = 7526, mnemonic = "jsr" },
      { call_addr = 0x0003CECA, return_addr = 0x0003CED0, caller_src = "zelda_translated\\z_04.asm", caller_line = 8028, mnemonic = "jsr" },
      { call_addr = 0x0003CEEE, return_addr = 0x0003CEF4, caller_src = "zelda_translated\\z_04.asm", caller_line = 8039, mnemonic = "jsr" },
      { call_addr = 0x0003D0CC, return_addr = 0x0003D0D2, caller_src = "zelda_translated\\z_04.asm", caller_line = 8284, mnemonic = "jsr" },
      { call_addr = 0x0003D2BA, return_addr = 0x0003D2C0, caller_src = "zelda_translated\\z_04.asm", caller_line = 8513, mnemonic = "jsr" },
      { call_addr = 0x0003D36C, return_addr = 0x0003D372, caller_src = "zelda_translated\\z_04.asm", caller_line = 8594, mnemonic = "jsr" },
      { call_addr = 0x0003D450, return_addr = 0x0003D456, caller_src = "zelda_translated\\z_04.asm", caller_line = 8707, mnemonic = "jsr" },
      { call_addr = 0x0003DDA2, return_addr = 0x0003DDA8, caller_src = "zelda_translated\\z_04.asm", caller_line = 9967, mnemonic = "jsr" },
      { call_addr = 0x0003E21A, return_addr = 0x0003E220, caller_src = "zelda_translated\\z_04.asm", caller_line = 10577, mnemonic = "jsr" },
      { call_addr = 0x0003E2DE, return_addr = 0x0003E2E4, caller_src = "zelda_translated\\z_04.asm", caller_line = 10669, mnemonic = "jsr" },
      { call_addr = 0x0003E89E, return_addr = 0x0003E8A4, caller_src = "zelda_translated\\z_04.asm", caller_line = 11461, mnemonic = "jsr" },
      { call_addr = 0x0003EDDA, return_addr = 0x0003EDE0, caller_src = "zelda_translated\\z_04.asm", caller_line = 12140, mnemonic = "jsr" },
      { call_addr = 0x0003EE68, return_addr = 0x0003EE6E, caller_src = "zelda_translated\\z_04.asm", caller_line = 12214, mnemonic = "jsr" },
      { call_addr = 0x0003F188, return_addr = 0x0003F18E, caller_src = "zelda_translated\\z_04.asm", caller_line = 12660, mnemonic = "jsr" },
      { call_addr = 0x0003F36C, return_addr = 0x0003F372, caller_src = "zelda_translated\\z_04.asm", caller_line = 12924, mnemonic = "jsr" },
      { call_addr = 0x0004C26C, return_addr = 0x0004C272, caller_src = "zelda_translated\\z_07.asm", caller_line = 3401, mnemonic = "jsr" },
    },
  },
  {
    name = "MoveObject",
    tier = "T3",
    entry_addr = 0x0004C8FA,
    static_insts = 23,
    call_sites = {
      { call_addr = 0x0002FD4E, return_addr = 0x0002FD54, caller_src = "zelda_translated\\z_01.asm", caller_line = 3405, mnemonic = "jsr" },
      { call_addr = 0x000305BA, return_addr = 0x000305C0, caller_src = "zelda_translated\\z_01.asm", caller_line = 4710, mnemonic = "jsr" },
      { call_addr = 0x00039C54, return_addr = 0x00039C5A, caller_src = "zelda_translated\\z_04.asm", caller_line = 920, mnemonic = "jsr" },
      { call_addr = 0x00039D76, return_addr = 0x00039D7C, caller_src = "zelda_translated\\z_04.asm", caller_line = 1081, mnemonic = "jsr" },
      { call_addr = 0x00039FC6, return_addr = 0x00039FCC, caller_src = "zelda_translated\\z_04.asm", caller_line = 1374, mnemonic = "jsr" },
      { call_addr = 0x0003A3D2, return_addr = 0x0003A3D8, caller_src = "zelda_translated\\z_04.asm", caller_line = 1937, mnemonic = "jsr" },
      { call_addr = 0x0003AF7C, return_addr = 0x0003AF82, caller_src = "zelda_translated\\z_04.asm", caller_line = 3627, mnemonic = "jsr" },
      { call_addr = 0x0003B542, return_addr = 0x0003B548, caller_src = "zelda_translated\\z_04.asm", caller_line = 4503, mnemonic = "jsr" },
      { call_addr = 0x0003BAC0, return_addr = 0x0003BAC6, caller_src = "zelda_translated\\z_04.asm", caller_line = 5264, mnemonic = "jsr" },
      { call_addr = 0x00045402, return_addr = 0x00045406, caller_src = "zelda_translated\\z_05.asm", caller_line = 8569, mnemonic = "jsr" },
      { call_addr = 0x0004C072, return_addr = 0x0004C076, caller_src = "zelda_translated\\z_07.asm", caller_line = 3138, mnemonic = "jsr" },
      { call_addr = 0x0004D430, return_addr = 0x0004D434, caller_src = "zelda_translated\\z_07.asm", caller_line = 6106, mnemonic = "jsr" },
      { call_addr = 0x0004D512, return_addr = 0x0004D516, caller_src = "zelda_translated\\z_07.asm", caller_line = 6242, mnemonic = "jsr" },
      { call_addr = 0x0004D53C, return_addr = 0x0004D540, caller_src = "zelda_translated\\z_07.asm", caller_line = 6255, mnemonic = "jsr" },
      { call_addr = 0x0004D940, return_addr = 0x0004D944, caller_src = "zelda_translated\\z_07.asm", caller_line = 6799, mnemonic = "jsr" },
    },
  },
  {
    name = "Walker_Move",
    tier = "T4",
    entry_addr = 0x0004C7D0,
    static_insts = 115,
    call_sites = {
      { call_addr = 0x00039822, return_addr = 0x00039828, caller_src = "zelda_translated\\z_04.asm", caller_line = 368, mnemonic = "jsr" },
      { call_addr = 0x00039958, return_addr = 0x0003995E, caller_src = "zelda_translated\\z_04.asm", caller_line = 531, mnemonic = "jsr" },
      { call_addr = 0x0003BD84, return_addr = 0x0003BD8A, caller_src = "zelda_translated\\z_04.asm", caller_line = 5620, mnemonic = "jsr" },
      { call_addr = 0x0004C37E, return_addr = 0x0004C382, caller_src = "zelda_translated\\z_07.asm", caller_line = 3537, mnemonic = "jsr" },
    },
  },
  {
    name = "Walker_CheckTileCollision",
    tier = "T4",
    entry_addr = 0x0004C9D8,
    static_insts = 53,
    call_sites = {
      { call_addr = 0x0004C8E4, return_addr = 0x0004C8E8, caller_src = "zelda_translated\\z_07.asm", caller_line = 4348, mnemonic = "jsr" },
    },
  },
  {
    name = "UpdateMoblin",
    tier = "T4",
    entry_addr = 0x0003A710,
    static_insts = 65,
    call_sites = {
    },
  },
  {
    name = "UpdateArrowOrBoomerang",
    tier = "T4",
    entry_addr = 0x0004D1EC,
    static_insts = 125,
    call_sites = {
      { call_addr = 0x0003A842, return_addr = 0x0003A848, caller_src = "zelda_translated\\z_04.asm", caller_line = 2646, mnemonic = "jsr" },
    },
  },
  {
    name = "AnimateAndDrawObjectWalking",
    tier = "T4",
    entry_addr = 0x0003129C,
    static_insts = 135,
    call_sites = {
      { call_addr = 0x0004C260, return_addr = 0x0004C266, caller_src = "zelda_translated\\z_07.asm", caller_line = 3395, mnemonic = "jsr" },
    },
  },
  {
    name = "AddQSpeedToPositionFraction",
    tier = "T4",
    entry_addr = 0x0003048E,
    static_insts = 36,
    call_sites = {
    },
  },
  {
    name = "SubQSpeedFromPositionFraction",
    tier = "T4",
    entry_addr = 0x000304F8,
    static_insts = 41,
    call_sites = {
    },
  },
  {
    name = "TryNextDir",
    tier = "T4",
    entry_addr = 0x0004CA68,
    static_insts = 6,
    call_sites = {
    },
  },
  {
    name = "GetCollidableTile",
    tier = "T4",
    entry_addr = 0x0004C40E,
    static_insts = 135,
    call_sites = {
      { call_addr = 0x0003D21C, return_addr = 0x0003D222, caller_src = "zelda_translated\\z_04.asm", caller_line = 8444, mnemonic = "jsr" },
    },
  },
  {
    name = "_oam_dma_flush",
    tier = "derived",
    entry_addr = 0x0002AEE6,
    static_insts = 29,
    call_sites = {
      { call_addr = 0x00000436, return_addr = 0x0000043C, caller_src = "genesis_shell.asm", caller_line = 463, mnemonic = "bsr" },
    },
  },
  {
    name = "_ags_flush",
    tier = "derived",
    entry_addr = 0x0000E388,
    static_insts = 12,
    call_sites = {
      { call_addr = 0x00000452, return_addr = 0x00000458, caller_src = "genesis_shell.asm", caller_line = 487, mnemonic = "bsr" },
    },
  },
  {
    name = "_ags_prearm",
    tier = "derived",
    entry_addr = 0x0000E3B8,
    static_insts = 5,
    call_sites = {
      { call_addr = 0x0000043C, return_addr = 0x00000442, caller_src = "genesis_shell.asm", caller_line = 469, mnemonic = "bsr" },
    },
  },
  {
    name = "DriveAudio",
    tier = "derived",
    entry_addr = 0x0002C318,
    static_insts = 1,
    call_sites = {
      { call_addr = 0x0004B4DA, return_addr = 0x0004B4E0, caller_src = "zelda_translated\\z_07.asm", caller_line = 1635, mnemonic = "jsr" },
    },
  },
}
cycle_profile_missing = {}
