"""emit_gen_wrappers.py — generate or verify the marker-bounded forwarder
region of each src/gen/z_0x.c from its JSON manifest.

See tools/gen_wrappers/README.md for manifest schema. Standard library only.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN_DIR = ROOT / "src" / "gen"
MANIFEST_DIR = ROOT / "tools" / "gen_wrappers"

ALLOWED_TYPES = {
    "void", "unsigned char", "unsigned int", "unsigned short",
    "int", "char", "signed char",
}

PREFIX_HEADERS = {
    "frontdemo_": "frontend_runtime.h",
    "frontname_": "frontend_runtime.h",
    "frontutil_": "frontend_runtime.h",
    "cavert_":  "cave_runtime.h",
    "cobrt_":   "combat_runtime.h",
    "colrt_":   "collision_runtime.h",
    "corert_":  "core_runtime.h",
    "enrt_":    "enemy_runtime.h",
    "hudrt_":   "hud_runtime.h",
    "itemrt_":  "item_runtime.h",
    "lcrt_":    "link_collision_runtime.h",
    "objrt_":   "object_runtime.h",
    "progrt_":  "progress_runtime.h",
    "roomld_":  "room_load_runtime.h",
    "roommd_":  "room_mode_runtime.h",
    "roomobj_": "room_object_runtime.h",
    "roompl_":  "room_player_runtime.h",
    "roomrt_":  "room_runtime.h",
    "roomxf_":  "room_transfer_runtime.h",
    "savert_":  "save_menu_runtime.h",
    "sprrt_":   "sprite_runtime.h",
    "targrt_":  "targeting_runtime.h",
    "trprt_":   "trap_runtime.h",
    "uwrt_":    "uw_person_runtime.h",
    "weprt_":   "weapon_runtime.h",
    "worldrt_": "world_runtime.h",
}

START_TMPL = "/* <<< auto-wrappers: {bank} (generated by tools/emit_gen_wrappers.py) >>> */"
END_MARKER = "/* <<< end auto-wrappers >>> */"

SIG_RE = re.compile(r"^\s*(?P<ret>[a-z ]+?)\s*\(\s*(?P<args>.*?)\s*\)\s*$")


def header_for(new: str) -> str | None:
    for prefix, header in PREFIX_HEADERS.items():
        if new.startswith(prefix):
            return header
    return None


def parse_sig(sig: str) -> tuple[str, list[tuple[str, str]]]:
    m = SIG_RE.match(sig)
    if not m:
        raise ValueError(f"bad signature: {sig!r}")
    ret = re.sub(r"\s+", " ", m.group("ret")).strip()
    if ret not in ALLOWED_TYPES:
        raise ValueError(f"bad return type: {ret!r}")
    args_src = m.group("args").strip()
    if not args_src or args_src == "void":
        return ret, []
    args: list[tuple[str, str]] = []
    for part in args_src.split(","):
        part = part.strip()
        tokens = part.split()
        if len(tokens) < 2:
            raise ValueError(f"bad arg: {part!r}")
        name = tokens[-1]
        atype = " ".join(tokens[:-1])
        if atype not in ALLOWED_TYPES:
            raise ValueError(f"bad arg type: {atype!r} in {sig!r}")
        args.append((atype, name))
    return ret, args


def render_forwarder(entry: dict) -> str:
    old = entry["old"]
    new = entry["new"]
    ret, args = parse_sig(entry["sig"])
    if args:
        param_decl = ", ".join(f"{t} {n}" for t, n in args)
        call_args = ", ".join(n for _, n in args)
    else:
        param_decl = "void"
        call_args = ""
    body_call = f"{new}({call_args});"
    if ret == "void":
        body = f"    {body_call}"
    else:
        body = f"    return {body_call}"
    return f"{ret} {old}({param_decl}) {{\n{body}\n}}\n"


def render_bank(manifest: dict) -> str:
    bank = manifest["bank"]
    includes = list(manifest.get("includes", []))
    symbols = manifest["symbols"]

    seen = set()
    for entry in symbols:
        if entry["old"] in seen:
            raise ValueError(f"duplicate old symbol: {entry['old']!r}")
        seen.add(entry["old"])
        header = header_for(entry["new"])
        if header and header not in includes:
            includes.append(header)

    lines = [START_TMPL.format(bank=bank), ""]
    if includes:
        for h in includes:
            lines.append(f'#include "{h}"')
        lines.append("")
    for entry in symbols:
        lines.append(render_forwarder(entry).rstrip() + "\n")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def replace_region(source: str, bank: str, body: str) -> str:
    start = START_TMPL.format(bank=bank)
    start_idx = source.find(start)
    end_idx = source.find(END_MARKER, start_idx + 1) if start_idx != -1 else -1

    if start_idx == -1 or end_idx == -1:
        trailing = "" if source.endswith("\n") else "\n"
        if body.lstrip().startswith(start):
            wrapped = body
        else:
            body_nl = body if body.endswith("\n") else body + "\n"
            wrapped = f"{start}\n{body_nl}{END_MARKER}\n"
        return source + trailing + "\n" + wrapped

    end_idx += len(END_MARKER)
    if end_idx < len(source) and source[end_idx] == "\n":
        end_idx += 1
    return source[:start_idx] + body + source[end_idx:]


def apply_manifest(manifest: dict, path: Path) -> None:
    body = render_bank(manifest)
    new_text = replace_region(path.read_text(), manifest["bank"], body)
    path.write_text(new_text)


def check_manifest(manifest: dict, path: Path) -> bool:
    body = render_bank(manifest)
    expected = replace_region(path.read_text(), manifest["bank"], body)
    return expected != path.read_text()


def bank_path(bank: str) -> Path:
    return GEN_DIR / f"{bank}.c"


def manifest_path(bank: str) -> Path:
    return MANIFEST_DIR / f"{bank}_manifest.json"


def load_manifest(bank: str) -> dict:
    return json.loads(manifest_path(bank).read_text())


def all_banks() -> list[str]:
    return sorted(p.stem.removesuffix("_manifest") for p in MANIFEST_DIR.glob("z_*_manifest.json"))


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bank", help="restrict to one bank, e.g. z_05")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if any bank would change")
    args = parser.parse_args(argv)

    banks = [args.bank] if args.bank else all_banks()
    drift = False
    for bank in banks:
        manifest = load_manifest(bank)
        if not manifest.get("symbols"):
            continue
        path = bank_path(bank)
        start = START_TMPL.format(bank=bank)
        if start not in path.read_text():
            print(f"SKIP: {bank} (no marker region yet)", file=sys.stderr)
            continue
        if args.check:
            if check_manifest(manifest, path):
                print(f"DRIFT: {bank}", file=sys.stderr)
                drift = True
        else:
            apply_manifest(manifest, path)

    return 1 if (args.check and drift) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
