"""Extract Zelda intro assets from the committed disassembly reference tree.

Reads reference/aldonunez/dat/ and emits src/gen/intro_*.c files containing
font CHR, art CHR, palette table, story tilemap, showcase tilemap, restore
blobs, and a handoff-state struct. Also emits src/gen/intro_asset_hashes.txt
listing SHA256 of every output for regression detection.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Canonical NES palette RGB values (Nesdev "2C02" LUT, first 64 entries).
# Each entry is (R, G, B) in 0..255.
NES_PALETTE_RGB = [
    (0x62, 0x62, 0x62), (0x00, 0x1F, 0xB2), (0x24, 0x04, 0xC8), (0x52, 0x00, 0xB2),
    (0x73, 0x00, 0x76), (0x80, 0x00, 0x24), (0x73, 0x0B, 0x00), (0x52, 0x28, 0x00),
    (0x24, 0x44, 0x00), (0x00, 0x57, 0x00), (0x00, 0x5C, 0x00), (0x00, 0x53, 0x24),
    (0x00, 0x3C, 0x76), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),

    (0xAB, 0xAB, 0xAB), (0x0D, 0x57, 0xFF), (0x4B, 0x30, 0xFF), (0x8A, 0x13, 0xFF),
    (0xBC, 0x08, 0xD6), (0xD2, 0x12, 0x69), (0xC7, 0x2E, 0x00), (0x9D, 0x54, 0x00),
    (0x60, 0x7B, 0x00), (0x20, 0x98, 0x00), (0x00, 0xA3, 0x00), (0x00, 0x99, 0x42),
    (0x00, 0x7D, 0xB4), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),

    (0xFF, 0xFF, 0xFF), (0x53, 0xAE, 0xFF), (0x90, 0x85, 0xFF), (0xD3, 0x65, 0xFF),
    (0xFF, 0x57, 0xFF), (0xFF, 0x5D, 0xCF), (0xFF, 0x77, 0x57), (0xFA, 0x9E, 0x00),
    (0xBD, 0xC7, 0x00), (0x7A, 0xE7, 0x00), (0x43, 0xF6, 0x11), (0x26, 0xEF, 0x7E),
    (0x2C, 0xD5, 0xF6), (0x4E, 0x4E, 0x4E), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),

    (0xFF, 0xFF, 0xFF), (0xB6, 0xE1, 0xFF), (0xCE, 0xD1, 0xFF), (0xE9, 0xC3, 0xFF),
    (0xFF, 0xBC, 0xFF), (0xFF, 0xBD, 0xF4), (0xFF, 0xC6, 0xC3), (0xFF, 0xD5, 0x9A),
    (0xE9, 0xE6, 0x81), (0xCE, 0xF4, 0x81), (0xB6, 0xFB, 0x9A), (0xA9, 0xFA, 0xC3),
    (0xA9, 0xF0, 0xF4), (0xB8, 0xB8, 0xB8), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),
]

def _quantize_channel(v: int) -> int:
    """Quantize an 8-bit channel to the Genesis 3-bit palette step (0/2/4/.../14)."""
    # Map [0..255] -> one of 0, 2, 4, 6, 8, 10, 12, 14 (8 discrete steps).
    step = min(7, v * 8 // 256)
    return step * 2

def nes_color_to_gen_cram(nes_idx: int) -> int:
    """Convert NES palette byte index (0..63) to a Genesis CRAM word.

    Genesis CRAM word format: 0000 BBB0 GGG0 RRR0 (little-endian bits).
    """
    if not 0 <= nes_idx < 64:
        raise ValueError(f"nes palette index out of range: {nes_idx}")
    r, g, b = NES_PALETTE_RGB[nes_idx]
    return (_quantize_channel(b) << 8) | (_quantize_channel(g) << 4) | _quantize_channel(r)

def nes_tile_to_gen_tile(nes: bytes) -> bytes:
    """Convert a single 8x8 NES 2bpp tile (16 bytes) to Genesis 4bpp (32 bytes).

    NES layout: 8 bytes of bitplane 0 (rows 0..7), then 8 bytes of bitplane 1.
    Genesis layout: 8 rows x 4 bytes/row; each row packs 8 pixels as 4-bit
    indices, high nibble first.
    """
    if len(nes) != 16:
        raise ValueError(f"nes tile must be 16 bytes, got {len(nes)}")
    out = bytearray(32)
    for row in range(8):
        bp0 = nes[row]
        bp1 = nes[row + 8]
        row_out = bytearray(4)
        for px in range(8):
            bit = 7 - px
            color = ((bp0 >> bit) & 1) | (((bp1 >> bit) & 1) << 1)
            byte_idx = px >> 1
            if (px & 1) == 0:
                row_out[byte_idx] |= (color & 0x0F) << 4
            else:
                row_out[byte_idx] |= (color & 0x0F)
        out[row * 4:(row + 1) * 4] = row_out
    return bytes(out)

# Story palette record lives in src/frontend_runtime.c. Duplicate the values
# here rather than parsing C - the record is stable and small.
STORY_PALETTE_RECORD = [
    0x3F, 0x00, 0x20, 0x0F, 0x30, 0x30, 0x30, 0x0F, 0x21, 0x30, 0x30, 0x0F,
    0x16, 0x30, 0x30, 0x0F, 0x29, 0x1A, 0x09, 0x0F, 0x29, 0x37, 0x17, 0x0F,
    0x02, 0x22, 0x30, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x0B, 0x1B, 0x2B, 0xFF,
]

def _emit_chr_array(out_path: Path, symbol: str, data: bytes) -> None:
    """Emit a C array of unsigned chars to a file."""
    lines = [f"/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
             f"const unsigned char {symbol}[{len(data)}] = {{\n"]
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    out_path.write_text("".join(lines))

def _build_story_cram() -> list[int]:
    """Convert the NES story palette record to a 64-entry Genesis CRAM buffer."""
    # Record layout (NES-style PPU transfer): skip 3-byte header, then 32 NES
    # palette bytes (4 sub-palettes x 8 entries, of which 0..3 are meaningful
    # per sub-palette in NES; Genesis uses 4 palettes x 16 colors).
    nes_bytes = STORY_PALETTE_RECORD[3:3 + 32]
    cram = [0] * 64
    for subpal in range(4):
        for color in range(4):
            nes_idx = nes_bytes[subpal * 4 + color] & 0x3F
            cram[subpal * 16 + color] = nes_color_to_gen_cram(nes_idx)
    return cram

def _emit_palette(out_path: Path, cram: list[int]) -> None:
    lines = [f"/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
             f"const unsigned short intro_palette[64] = {{\n"]
    for i in range(0, 64, 8):
        row = ", ".join(f"0x{v:04X}" for v in cram[i:i+8])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    out_path.write_text("".join(lines))

def _load_nes_chr(path: Path) -> bytes:
    """Read NES 2bpp CHR blob, convert to Genesis 4bpp, return concatenated bytes."""
    nes = path.read_bytes()
    assert len(nes) % 16 == 0, f"{path}: CHR length not multiple of 16"
    gen = bytearray()
    for i in range(0, len(nes), 16):
        gen += nes_tile_to_gen_tile(nes[i:i+16])
    return bytes(gen)

def main() -> int:
    ap = argparse.ArgumentParser(description="extract intro assets")
    ap.add_argument("--ref-dir", default=str(REPO / "reference" / "aldonunez" / "dat"),
                    help="path to committed disassembly reference data")
    ap.add_argument("--out-dir", default=str(REPO / "src" / "gen"),
                    help="output directory for generated C files")
    ap.add_argument("--handoff-json", default=str(REPO / "docs" / "superpowers" /
                    "captures" / "2026-04-24-intro-handoff-state.json"),
                    help="captured handoff state JSON")
    ap.add_argument("--restore-chr", default=str(REPO / "docs" / "superpowers" /
                    "captures" / "2026-04-24-intro-restore-chr.bin"))
    ap.add_argument("--restore-cram", default=str(REPO / "docs" / "superpowers" /
                    "captures" / "2026-04-24-intro-restore-cram.bin"))
    ap.add_argument("--verify", action="store_true",
                    help="re-check SHA of emitted files against committed hashes")
    args = ap.parse_args()

    ref_dir = Path(args.ref_dir)
    if not ref_dir.is_dir():
        print(f"error: reference dir not found: {ref_dir}", file=sys.stderr)
        return 2
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    font_src = ref_dir / "DemoBackgroundPatterns.dat"
    art_src = ref_dir / "DemoSpritePatterns.dat"
    if not font_src.exists() or not art_src.exists():
        print("error: required reference files missing", file=sys.stderr)
        return 2

    font_gen = _load_nes_chr(font_src)
    art_gen  = _load_nes_chr(art_src)
    _emit_chr_array(out_dir / "intro_font_chr.c", "intro_font_chr", font_gen)
    _emit_chr_array(out_dir / "intro_art_chr.c",  "intro_art_chr",  art_gen)

    cram = _build_story_cram()
    _emit_palette(out_dir / "intro_palette.c", cram)

    emitted = {
        "intro_font_chr.c": _sha(out_dir / "intro_font_chr.c"),
        "intro_art_chr.c":  _sha(out_dir / "intro_art_chr.c"),
        "intro_palette.c": _sha(out_dir / "intro_palette.c"),
    }

    hash_file = out_dir / "intro_asset_hashes.txt"
    if args.verify:
        return _verify(emitted, hash_file)
    _write_hashes(emitted, hash_file)
    return 0

def _sha(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()

def _write_hashes(emitted: dict[str, str], hash_file: Path) -> None:
    lines = [f"{sha}  {name}\n" for name, sha in sorted(emitted.items())]
    hash_file.write_text("".join(lines))

def _verify(emitted: dict[str, str], hash_file: Path) -> int:
    if not hash_file.exists():
        print(f"error: hash file missing: {hash_file}", file=sys.stderr)
        return 3
    expected = {}
    for line in hash_file.read_text().splitlines():
        sha, name = line.split("  ", 1)
        expected[name] = sha
    if expected != emitted:
        print("error: emitted SHA set differs from committed", file=sys.stderr)
        return 3
    return 0

if __name__ == "__main__":
    sys.exit(main())
