#!/usr/bin/env python3
"""Generate RoomRom/data/uw_l1q1_pushblocks.{c,h} from NES ground truth.

NES rule (Z_05.asm:FindAndCreatePushBlockObject lines 5461-5514): for
each room, the pushable block is the FIRST `$B0` tile found scanning
BG row 10 (= row $A) of the play area. Other `$B0` occurrences in the
same room are static decorative wall tiles, NOT BlockObj.

Slice-1 emits L1Q1 only. Schema:

    struct uw_pushblock_meta {
        unsigned char level;
        unsigned char quest;
        unsigned char room_id;
        unsigned char block_col_mt;   /* 0..15 */
        unsigned char block_row_mt;   /* 0..10 */
        unsigned char allowed_dirs;   /* mask: bit0=N bit1=S bit2=W bit3=E */
        unsigned char trigger_kind;   /* 0=collision, 1=stair, 2=door */
    };

`allowed_dirs = $0F` always, because NES `UpdateBlock0Idle` derives
push direction purely from Link's relative position; the player MUST
press the right key for that side per Z_04.asm:684 — but any side
Link approaches from is valid.

`trigger_kind = 1` if the room's cellar set in
RoomRom/data/uw_l1q1_cellar_pairs.h includes this room as a SOURCE
room (i.e., the block's secret reveals a stair). Else 0.

Run from repo root:
    python tools/uw_pushblock_meta_gen.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BLOB_C = REPO / "RoomRom" / "src" / "uw_room_blob.c"
CELLAR_PAIRS_C = REPO / "RoomRom" / "data" / "uw_l1q1_cellar_pairs.c"
OUT_C = REPO / "RoomRom" / "data" / "uw_l1q1_pushblocks.c"
OUT_H = REPO / "RoomRom" / "data" / "uw_l1q1_pushblocks.h"

BLOB_NT_ROW_BYTES = 32
BLOB_NT_ROWS = 22
BLOB_NT_BYTES = BLOB_NT_ROW_BYTES * BLOB_NT_ROWS  # 704
SCAN_ROW = 10  # NES BG row $A
TILE_BLOCK = 0xB0
ALLOWED_DIRS_ALL = 0x0F

# Slice-1 emits L1Q1 only.
SLICE_1_LEVEL = 1
SLICE_1_QUEST = 1


def parse_index(text: str) -> list[tuple[int, int, int, int]]:
    """Returns list of (map, quest, level, room_id) for every blob entry."""
    m = re.search(r"g_uw_room_index\[\d+\]\[4\] = \{(.+?)\};", text, re.S)
    if not m:
        sys.exit("blob index not found")
    body = m.group(1)
    rows = []
    for tup in re.finditer(
        r"\{\s*0x([0-9a-fA-F]+),\s*0x([0-9a-fA-F]+),\s*0x([0-9a-fA-F]+),\s*0x([0-9a-fA-F]+)\s*\}",
        body,
    ):
        rows.append(tuple(int(x, 16) for x in tup.groups()))
    return rows


def parse_nt_block(text: str, idx: int) -> bytes:
    """Returns 704-byte NT for blob entry idx."""
    m = re.search(r"g_uw_room_nt\[\d+\]\[\d+\] = \{(.+?)\n\};", text, re.S)
    if not m:
        sys.exit("blob nt array not found")
    body = m.group(1)
    # Parse all hex bytes; 704 per entry. With ~636 entries this is ~448 K
    # tokens — acceptable.
    bs = bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", body))
    start = idx * BLOB_NT_BYTES
    end = start + BLOB_NT_BYTES
    if end > len(bs):
        sys.exit(f"blob nt entry {idx} out of range (have {len(bs)} bytes)")
    return bs[start:end]


def find_block_col(nt: bytes, row: int) -> int | None:
    """Returns first BG col in `row` whose tile == $B0, else None.
    NES scans columns 4..26 (per Z_05.asm:5484-5499 `LDX #$08; CPX #$34`)."""
    base = row * BLOB_NT_ROW_BYTES
    for col in range(4, 27):
        if nt[base + col] == TILE_BLOCK:
            return col
    return None


def parse_cellar_sources() -> set[int]:
    """Returns set of L1Q1 room ids that are cellar sources."""
    if not CELLAR_PAIRS_C.exists():
        return set()
    text = CELLAR_PAIRS_C.read_text(encoding="utf-8")
    out = set()
    for m in re.finditer(
        r"\{\s*1u?,\s*1u?,\s*0x([0-9a-fA-F]+)u?,\s*0x[0-9a-fA-F]+u?\s*\}",
        text,
    ):
        out.add(int(m.group(1), 16))
    return out


def collect_l1q1(blob_text: str) -> list[dict]:
    index = parse_index(blob_text)
    cellar_sources = parse_cellar_sources()
    rows = []
    for blob_idx, (mp, q, lvl, rid) in enumerate(index):
        if mp != 0 or q != SLICE_1_QUEST or lvl != SLICE_1_LEVEL:
            continue
        nt = parse_nt_block(blob_text, blob_idx)
        col = find_block_col(nt, SCAN_ROW)
        if col is None:
            continue
        block_col_mt = col // 2
        block_row_mt = SCAN_ROW // 2  # = 5
        trigger = 1 if rid in cellar_sources else 0
        rows.append({
            "level": lvl,
            "quest": q,
            "room_id": rid,
            "block_col_mt": block_col_mt,
            "block_row_mt": block_row_mt,
            "allowed_dirs": ALLOWED_DIRS_ALL,
            "trigger_kind": trigger,
        })
    return rows


HEADER = """\
/* Auto-generated by tools/uw_pushblock_meta_gen.py - do not edit.
 *
 * UW push-block manifest for slice-1 (L1Q1). Each row maps a UW room
 * containing a pushable block to the metatile coord of that block.
 *
 * NES rule (Z_05.asm:FindAndCreatePushBlockObject lines 5461-5514):
 *   block = first $B0 tile found scanning BG row 10 left-to-right
 *           (cols 4..26).
 *   Other $B0 occurrences in the same room are static decorative
 *   wall tiles, NOT BlockObj.
 *
 * `allowed_dirs = $0F` because NES UpdateBlock0Idle derives push
 * direction from Link's relative position (Z_04.asm:632-685); any
 * side Link approaches from is valid.
 *
 * `trigger_kind`:
 *   0 = collision-only (push only opens path through block's metatile)
 *   1 = stair (CheckSecretTriggerBlockStairs, Z_05.asm:2471)
 *   2 = door  (CheckSecretTriggerBlockDoor,  Z_05.asm:2463)
 */

#ifndef ROOMROM_UW_L1Q1_PUSHBLOCKS_H
#define ROOMROM_UW_L1Q1_PUSHBLOCKS_H

struct uw_pushblock_meta {
    unsigned char level;
    unsigned char quest;
    unsigned char room_id;
    unsigned char block_col_mt;   /* 0..15 */
    unsigned char block_row_mt;   /* 0..10 */
    unsigned char allowed_dirs;   /* bit0=N bit1=S bit2=W bit3=E */
    unsigned char trigger_kind;   /* 0=collision 1=stair 2=door */
};

extern const struct uw_pushblock_meta uw_l1q1_pushblocks[];
extern const unsigned char uw_l1q1_pushblocks_count;
extern const unsigned char uw_pushblock_lookup[10][3][128];

#endif /* ROOMROM_UW_L1Q1_PUSHBLOCKS_H */
"""

C_PROLOGUE = """\
/* Auto-generated by tools/uw_pushblock_meta_gen.py - do not edit. */

#include "uw_l1q1_pushblocks.h"

const struct uw_pushblock_meta uw_l1q1_pushblocks[] = {
"""

C_EPILOGUE = """\
};

const unsigned char uw_l1q1_pushblocks_count =
    (unsigned char)(sizeof(uw_l1q1_pushblocks) /
                    sizeof(uw_l1q1_pushblocks[0]));
"""


def emit_pushblock_lookup(rows: list[dict]) -> str:
    table = [[[0 for _ in range(128)] for _ in range(3)] for _ in range(10)]
    for idx, r in enumerate(rows):
        table[r["level"]][r["quest"]][r["room_id"]] = idx + 1

    out = ["", "const unsigned char uw_pushblock_lookup[10][3][128] = {"]
    for level in range(10):
        out.append("    {")
        for quest in range(3):
            out.append("        {")
            vals = table[level][quest]
            for i in range(0, 128, 16):
                out.append("            " + ", ".join(f"{v}u" for v in vals[i:i + 16]) + ",")
            out.append("        },")
        out.append("    },")
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    if not BLOB_C.exists():
        sys.exit(f"missing {BLOB_C}")
    blob_text = BLOB_C.read_text(encoding="utf-8", errors="ignore")
    rows = collect_l1q1(blob_text)

    # Slice-1 sanity: expect at least one row including $22.
    rids = sorted(r["room_id"] for r in rows)
    print(f"L1Q1 push-block rooms: {[hex(r) for r in rids]} ({len(rids)} total)")
    if 0x22 not in rids:
        sys.exit("L1Q1 $22 push-block not found — generator regression")

    body_lines = []
    for r in rows:
        body_lines.append(
            f"    {{ {r['level']}u, {r['quest']}u, "
            f"0x{r['room_id']:02X}u, {r['block_col_mt']}u, "
            f"{r['block_row_mt']}u, 0x{r['allowed_dirs']:02X}u, "
            f"{r['trigger_kind']}u }},"
            f"  /* L{r['level']}Q{r['quest']} R${r['room_id']:02X} */"
        )
    OUT_H.write_text(HEADER, encoding="utf-8")
    OUT_C.write_text(C_PROLOGUE + "\n".join(body_lines) + "\n" + C_EPILOGUE
                     + emit_pushblock_lookup(rows),
                     encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(REPO)}")
    print(f"wrote {OUT_C.relative_to(REPO)}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
