"""Phase E differ — compare Genesis warp_routes_probe dump vs NES oracle.

Inputs:
  tools/parity/warp_routes_expected.json   (NES-extracted dispatch table)
  tools/parity/warp_routes_gen_dump.txt    (Genesis runtime probe dump)

Output:
  tools/parity/warp_routes_sweep_report.md  (per-room diff + summary)

Exit code:
  0 = all 128 rooms match (Phase E GREEN)
  1 = at least one room mismatched
  2 = required input missing
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
ORACLE = REPO / "tools" / "parity" / "warp_routes_expected.json"
GEN = REPO / "tools" / "parity" / "warp_routes_gen_dump.txt"
REPORT = REPO / "tools" / "parity" / "warp_routes_sweep_report.md"


def load_oracle() -> dict:
    raw = json.loads(ORACLE.read_text(encoding="utf-8"))
    by_room = {r["room_id"]: r for r in raw["rows"]}
    return {"summary": raw["summary"], "by_room": by_room}


def load_gen() -> dict:
    if not GEN.exists():
        print(f"missing {GEN}", file=sys.stderr)
        sys.exit(2)
    text = GEN.read_text(encoding="utf-8")
    header = {}
    rooms: dict[int, int] = {}
    for line in text.splitlines():
        m = re.match(r"# no_warp_count:\$([0-9A-Fa-f]+)\s*\((\d+)\)", line)
        if m:
            header["no_warp_count"] = int(m.group(2))
            continue
        m = re.match(r"# dungeon_count:\$([0-9A-Fa-f]+)\s*\((\d+)\)", line)
        if m:
            header["dungeon_count"] = int(m.group(2))
            continue
        m = re.match(r"# cave_count:\s*\$([0-9A-Fa-f]+)\s*\((\d+)\)", line)
        if m:
            header["cave_count"] = int(m.group(2))
            continue
        m = re.match(r"room \$([0-9A-Fa-f]+) = \$([0-9A-Fa-f]+)", line)
        if m:
            rooms[int(m.group(1), 16)] = int(m.group(2), 16)
            continue
        # New diag format: room $XX direct=$YY meta=$ZZ diff=$WW cid=$VV
        m = re.match(
            r"room \$([0-9A-Fa-f]+) direct=\$([0-9A-Fa-f]+) "
            r"meta=\$([0-9A-Fa-f]+) diff=\$([0-9A-Fa-f]+) "
            r"cid=\$([0-9A-Fa-f]+)",
            line,
        )
        if m:
            rooms[int(m.group(1), 16)] = int(m.group(5), 16)
    return {"header": header, "rooms": rooms}


def main() -> int:
    if not ORACLE.exists():
        print(f"missing {ORACLE}", file=sys.stderr)
        return 2

    oracle = load_oracle()
    gen = load_gen()

    if len(gen["rooms"]) != 128:
        print(
            f"gen dump has {len(gen['rooms'])} rows, expected 128",
            file=sys.stderr,
        )
        return 2

    mismatches: list[tuple[int, dict, int]] = []
    for room_id in range(128):
        expected_row = oracle["by_room"][room_id]
        gen_cid = gen["rooms"][room_id]
        expected_cid = expected_row.get("cave_id") or 0
        if gen_cid != expected_cid:
            mismatches.append((room_id, expected_row, gen_cid))

    lines = []
    lines.append("# Phase E Warp Routes Sweep Report\n\n")
    lines.append("_Generated by tools/parity/diff_warp_routes.py_\n\n")
    lines.append("## Header parity\n\n")
    lines.append("| Metric | Oracle | Gen |\n|---|---|---|\n")
    lines.append(
        f"| no_warp | {oracle['summary']['no_warp']} | "
        f"{gen['header'].get('no_warp_count')} |\n"
    )
    lines.append(
        f"| dungeon | {oracle['summary']['dungeon']} | "
        f"{gen['header'].get('dungeon_count')} |\n"
    )
    cave_total = (
        oracle["summary"]["cave_regular"] + oracle["summary"]["cave_shortcut"]
    )
    lines.append(
        f"| cave (regular+shortcut) | {cave_total} | "
        f"{gen['header'].get('cave_count')} |\n"
    )
    lines.append("\n## Per-room diff\n\n")
    if not mismatches:
        lines.append("All 128 rooms match. Phase E GREEN.\n")
    else:
        lines.append(f"{len(mismatches)} of 128 rooms mismatched.\n\n")
        lines.append(
            "| room | category | expected cid | gen cid | mode | level |\n"
            "|---|---|---|---|---|---|\n"
        )
        for room_id, exp, gen_cid in mismatches:
            cid_e = f"${exp['cave_id']:02X}" if exp["cave_id"] else "---"
            mode = f"${exp['mode']:02X}" if exp["mode"] is not None else "---"
            level = f"L{exp['level']}" if exp["level"] is not None else "-"
            lines.append(
                f"| ${room_id:02X} | {exp['category']} | {cid_e} | "
                f"${gen_cid:02X} | {mode} | {level} |\n"
            )

    REPORT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {REPORT.relative_to(REPO)}")
    print(f"{len(mismatches)}/128 mismatches")
    return 0 if not mismatches else 1


if __name__ == "__main__":
    raise SystemExit(main())
