"""Phase F differ — compare Genesis dungeon_roundtrip_probe dump
against tools/parity/dungeon_roundtrip_expected.json.

Inputs:
  tools/parity/dungeon_roundtrip_expected.json   (oracle)
  tools/parity/dungeon_roundtrip_gen_dump.txt    (Genesis runtime dump)

Output:
  tools/parity/dungeon_roundtrip_sweep_report.md

Exit code:
  0 = 18/18 rows have pass_flags == 0x0F + field-exact match
  1 = at least one row mismatched
  2 = required input missing
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
ORACLE = REPO / "tools" / "parity" / "dungeon_roundtrip_expected.json"
GEN = REPO / "tools" / "parity" / "dungeon_roundtrip_gen_dump.txt"
REPORT = REPO / "tools" / "parity" / "dungeon_roundtrip_sweep_report.md"


def load_oracle() -> list[dict]:
    if not ORACLE.exists():
        print(f"missing {ORACLE}", file=sys.stderr)
        sys.exit(2)
    return json.loads(ORACLE.read_text(encoding="utf-8"))["rows"]


def load_gen() -> dict:
    if not GEN.exists():
        print(f"missing {GEN}", file=sys.stderr)
        sys.exit(2)
    text = GEN.read_text(encoding="utf-8")
    rows: list[dict] = []
    header = {"rows_ok": None, "magic_ok": False}
    for line in text.splitlines():
        m = re.match(r"# magic:\s+\$57 \$46", line)
        if m:
            header["magic_ok"] = True
            continue
        m = re.match(r"# rows_ok:\s+\$[0-9A-Fa-f]+ \((\d+) of 18\)", line)
        if m:
            header["rows_ok"] = int(m.group(1))
            continue
        m = re.match(
            r"\s+(\d) (\d)\s+\$([0-9A-Fa-f]+)\s+\$([0-9A-Fa-f]+)\s+"
            r"\$([0-9A-Fa-f]+)\s+\$([0-9A-Fa-f]+)",
            line,
        )
        if m:
            rows.append(
                {
                    "level": int(m.group(1)),
                    "quest": int(m.group(2)),
                    "dest_scene": int(m.group(3), 16),
                    "dest_level": int(m.group(4), 16),
                    "dest_room_id": int(m.group(5), 16),
                    "pass_flags": int(m.group(6), 16),
                }
            )
    return {"header": header, "rows": rows}


def main() -> int:
    oracle_rows = load_oracle()
    gen = load_gen()

    if not gen["header"]["magic_ok"]:
        print("magic mismatch — probe did not publish", file=sys.stderr)
        return 1
    if len(gen["rows"]) != 18:
        print(
            f"gen dump has {len(gen['rows'])} rows, expected 18",
            file=sys.stderr,
        )
        return 1

    oracle_by_lq = {(r["level"], r["quest"]): r for r in oracle_rows}
    mismatches = []
    for grow in gen["rows"]:
        lq = (grow["level"], grow["quest"])
        orow = oracle_by_lq.get(lq)
        if orow is None:
            mismatches.append((lq, "no oracle row", grow))
            continue
        bad_fields = []
        if grow["pass_flags"] != orow["expected_pass_flags"]:
            bad_fields.append(
                f"flags ${grow['pass_flags']:02X}!=${orow['expected_pass_flags']:02X}"
            )
        if grow["dest_scene"] != orow["expected_dest_scene"]:
            bad_fields.append(
                f"scene ${grow['dest_scene']:02X}!=${orow['expected_dest_scene']:02X}"
            )
        if grow["dest_level"] != orow["expected_dest_level"]:
            bad_fields.append(
                f"level ${grow['dest_level']:02X}!=${orow['expected_dest_level']:02X}"
            )
        if grow["dest_room_id"] != orow["expected_dest_room_id"]:
            bad_fields.append(
                f"room ${grow['dest_room_id']:02X}!=${orow['expected_dest_room_id']:02X}"
            )
        if bad_fields:
            mismatches.append((lq, ", ".join(bad_fields), grow))

    lines = []
    lines.append("# Phase F Dungeon Round-Trip Sweep Report\n\n")
    lines.append("_Generated by tools/parity/diff_dungeon_roundtrip.py_\n\n")
    lines.append(
        f"Header rows_ok: **{gen['header']['rows_ok']}/18**, "
        f"magic OK: {gen['header']['magic_ok']}\n\n"
    )
    lines.append("## Per-row table\n\n")
    lines.append(
        "| L | Q | start (oracle) | scene | level | room | flags | verdict |\n"
        "|---|---|----------------|-------|-------|------|-------|---------|\n"
    )
    for grow in gen["rows"]:
        lq = (grow["level"], grow["quest"])
        orow = oracle_by_lq.get(lq, {})
        start = orow.get("start_room_id", 0)
        verdict = "PASS"
        if any(m[0] == lq for m in mismatches):
            verdict = "FAIL"
        lines.append(
            f"| {grow['level']} | {grow['quest']} | "
            f"${start:02X} | "
            f"${grow['dest_scene']:02X} | "
            f"${grow['dest_level']:02X} | "
            f"${grow['dest_room_id']:02X} | "
            f"${grow['pass_flags']:02X} | {verdict} |\n"
        )

    lines.append("\n")
    if not mismatches:
        lines.append("**All 18 rows match. Phase F GREEN.**\n")
    else:
        lines.append(f"## {len(mismatches)} mismatch(es)\n\n")
        for lq, reason, grow in mismatches:
            lines.append(f"- L{lq[0]}Q{lq[1]}: {reason}\n")

    REPORT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {REPORT.relative_to(REPO)}")
    print(f"{len(mismatches)}/18 mismatches")
    return 0 if not mismatches else 1


if __name__ == "__main__":
    raise SystemExit(main())
