#!/usr/bin/env python3
"""Restore the TRUE Quest-1 UW LevelBlockAttrs in data/rooms/dungeons.c from
the authoritative reference dats.

ROOT CAUSE (byte-proven 2026-05-31): the prior
tools/parity/cave_golden/regen_dungeon_blob_from_sram.py captured live NES
SRAM WITHOUT forcing Quest 1, so it read the Quest-2 LevelBlockAttrs and wrote
them into the Quest-1 slots under a false "UW interiors are quest-independent"
assumption. Cross-match proof:
    dungeons.c[0:768]   (UW1Q1 slot) == LevelBlockUW1Q2.dat  EXACTLY  (Q2!)
    dungeons.c[768:1536](UW2Q1 slot) == LevelBlockUW2Q2.dat  EXACTLY  (Q2!)
=> every Quest-1 UW room decoded the wrong monster-list-id; boss rooms
(template $32-$62, count forced 1) resolved to a regular-enemy template
instead of the boss -> Genesis spawned e.g. 6x $2A at L1 $35 instead of
Aquamentus $3D. (Live probe gen_boss_direct/*/state.txt.)

The .dat IS directly SRAM-installable for LevelBlocks (no transform): proven by
overworld.c[0:768] == LevelBlockOW.dat byte-identical, and the OW path works.
The reference dat list_ids decode to the KNOWN Q1 boss placements (Aquamentus
$3D@$35, Dodongo $31@$56, Manhandla $3C@$10, Gleeok2 $43@$13, Digdogger $39@$24,
Gohma $34@$1C, ...), cross-confirmed by LevelInfo_BossRoomId.

LevelInfo (incl. FoeCounts at SRAM offset 36) is NOT touched here — its dat
layout differs (FoeCounts at dat offset 32) and it does not affect boss spawn
(boss template forces count=1). Tracked separately for regular-room counts.

Re-runnable. Sources ONLY reference/aldonunez/dat/ — no NES ROM / emulator.
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
DUN_C = ROOT / "data" / "rooms" / "dungeons.c"
DAT = ROOT / "reference" / "aldonunez" / "dat"
BLOCK = 768


def parse_blob(text):
    body = text[text.find("{") + 1: text.rfind("}")]
    return [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+|\d+", body)]


def emit_c(blob):
    lines = [
        "/* Auto-generated by tools/extract_rooms.py - do not edit. */",
        "/* Q1 UW LevelBlockAttrs restored from reference/aldonunez/dat/"
        "LevelBlockUW{1,2}Q1.dat",
        " * by tools/parity/fix_dungeons_q1_lba.py. The prior SRAM-capture regen"
        " wrote",
        " * QUEST-2 tables into the Q1 slots (quest not forced during capture);"
        " the",
        " * dats are the authoritative, SRAM-installable Q1 data (OW path proves"
        " no",
        " * transform). LevelInfo/FoeCounts unchanged. */",
        f"const unsigned long rooms_dungeons_size = {len(blob)}UL;",
        f"const unsigned char rooms_dungeons[{len(blob)}] = {{",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    blob = parse_blob(DUN_C.read_text())
    orig = list(blob)
    uw1q1 = (DAT / "LevelBlockUW1Q1.dat").read_bytes()
    uw2q1 = (DAT / "LevelBlockUW2Q1.dat").read_bytes()
    assert len(uw1q1) == BLOCK and len(uw2q1) == BLOCK, "dat block size != 768"

    blob[0:BLOCK] = list(uw1q1)              # UW1Q1 (L1-6 Q1)
    blob[BLOCK:2 * BLOCK] = list(uw2q1)      # UW2Q1 (L7-9 Q1)

    changed = sum(1 for a, b in zip(orig, blob) if a != b)
    DUN_C.write_text(emit_c(blob), encoding="ascii", newline="\n")
    print(f"fix: {changed} bytes changed in {DUN_C.name} (len {len(blob)})")
    # verification spot-checks (C-table at block offset 256):
    def lid(c, d):
        return (c & 0x3F) | (0x40 if (d & 0x80) else 0)
    checks = [("L1 aqua",  0x35, 0,   0x3D), ("L2 dodongo", 0x56, 0,   0x31),
              ("L5 digd",  0x24, 0,   0x39), ("L6 gohma",   0x1C, 0,   0x34),
              ("L9 ganon", 0x42, 768, 0x3E)]
    for name, room, blk, want in checks:
        got = lid(blob[blk + 256 + room], blob[blk + 384 + room])
        flag = "OK" if got == want else f"!! want ${want:02X}"
        print(f"  {name:10} room ${room:02X}: list_id ${got:02X}  {flag}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
