#!/usr/bin/env python3
"""
tools/parity/nes_to_schema.py — NES Capture Bundle → Parity Oracle Schema
==========================================================================
Converts a Phase 1.5 NES capture bundle (output directory under
build/generated/nes_reference/<rom_hash>/<scenario_id>/) into a
parity-oracle-schema-conformant JSON instance.

Input bundle directory must contain:
    screenshot.png   — PNG frame screenshot
    ppu.bin          — raw PPU snapshot (optional; used for plane fallback)
    oam.bin          — NES OAM dump (64 × 4 bytes = 256 bytes)
    palram.bin       — NES PALRAM dump (32 bytes: $3F00-$3F1F)
    ciram.bin        — NES CIRAM / nametable RAM (2048 bytes: $2000-$27FF)
    ram.bin          — NES RAM dump (2048 bytes: $0000-$07FF)
    frame.txt        — frame number (single integer)
    input_log.txt    — controller 1 bitmask at frame (single hex byte, e.g. "00")
    rng_seed.txt     — RNG seed at scenario start (single hex u16, e.g. "AB12")

Output:
    schema-conformant JSON (stdout or --out <path>)

Usage:
    nes_to_schema.py <bundle_dir> [--scenario-id <id>] [--out <path>]

The NES-to-Genesis CRAM conversion uses the same NES color index → Genesis
CRAM word LUT as RoomRom/src/roomrom_bg_palette.c (misc_palettes array).
The LUT is loaded from build/generated/palettes/misc_palettes.bin if present;
otherwise a stub conversion is used (logs a warning).

NES OAM → Genesis SAT collapse is stubbed. Full collapse rules depend on
Anim_WriteSpecificItemSprites grouping logic (Phase 2).
"""

import argparse
import hashlib
import json
import os
import struct
import sys
from pathlib import Path

# ─── Paths ────────────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent.parent

# Path to the misc_palettes LUT binary generated from the NES ROM.
# Contains 64 × 2 bytes: NES color index → Genesis CRAM word (little-endian u16).
# Generated by tools/builder/ during asset extraction.
MISC_PALETTES_BIN = REPO_ROOT / "build" / "generated" / "palettes" / "misc_palettes.bin"


# ─── NES color → Genesis CRAM conversion ─────────────────────────────────────

def _load_misc_palettes() -> list:
    """
    Load the NES color index → Genesis CRAM word LUT from misc_palettes.bin.
    Returns a list of 64 integers (Genesis CRAM words, 12-bit, 0-0xFFF).

    If the file is not found, returns the stub LUT (all zeros) and logs a warning.
    The stub will cause CRAM comparison failures — run tools/builder/ first.

    LUT layout matches roomrom_bg_palette_nes_to_cram in
    RoomRom/src/roomrom_bg_palette.c:
        off = (nes_color & 0x3F) * 2
        cram_word = misc_palettes[off] | (misc_palettes[off+1] << 8)
    """
    if MISC_PALETTES_BIN.exists():
        data = MISC_PALETTES_BIN.read_bytes()
        lut = []
        for i in range(64):
            if i * 2 + 1 < len(data):
                word = data[i * 2] | (data[i * 2 + 1] << 8)
                lut.append(word & 0x0FFF)
            else:
                lut.append(0)
        return lut
    else:
        print(
            f"WARNING: misc_palettes.bin not found at {MISC_PALETTES_BIN}. "
            "Using stub LUT (all zeros). CRAM comparison will fail. "
            "Run tools/builder/ to generate palette assets from the NES ROM.",
            file=sys.stderr,
        )
        return [0] * 64


_MISC_PALETTES_LUT = None  # Lazy-loaded on first use


def nes_color_to_cram(nes_color: int) -> int:
    """
    Convert NES color index (0x00-0x3F) to Genesis CRAM word (0x000-0xFFF).
    Mirrors roomrom_bg_palette_nes_to_cram from RoomRom/src/roomrom_bg_palette.c.
    """
    global _MISC_PALETTES_LUT
    if _MISC_PALETTES_LUT is None:
        _MISC_PALETTES_LUT = _load_misc_palettes()
    idx = nes_color & 0x3F
    return _MISC_PALETTES_LUT[idx]


def palram_to_cram(palram32: bytes) -> list:
    """
    Convert NES PALRAM (32 bytes: $3F00-$3F1F) to Genesis CRAM array (64 entries).

    NES PALRAM layout:
        $3F00-$3F0F: BG palettes (4 × 4 colors) → Genesis PAL0 (indices 0-15)
        $3F10-$3F1F: sprite palettes (4 × 4 colors) → Genesis PAL1 (indices 16-31)

    PAL2 (indices 32-47) and PAL3 (indices 48-63) are filled with zeros; they
    are used for non-NES overlays on the Genesis side and have no NES equivalent.

    Genesis CRAM index layout (matches RoomRom VDP init):
        [0-15]:  PAL0 — BG
        [16-31]: PAL1 — sprites
        [32-47]: PAL2 — (non-NES / Redux expansions; zero here)
        [48-63]: PAL3 — (non-NES / Redux expansions; zero here)
    """
    if len(palram32) < 32:
        palram32 = palram32 + b'\x00' * (32 - len(palram32))

    cram = []
    # PAL0: BG ($3F00-$3F0F)
    for i in range(16):
        cram.append(nes_color_to_cram(palram32[i]))
    # PAL1: sprites ($3F10-$3F1F)
    for i in range(16, 32):
        cram.append(nes_color_to_cram(palram32[i]))
    # PAL2, PAL3: zeros (no NES equivalent)
    cram.extend([0] * 32)
    return cram


# ─── NES OAM → Genesis SAT collapse ──────────────────────────────────────────

def oam_to_sat(oam_entries: list) -> list:
    """
    Convert NES OAM (64 entries) to Genesis SAT (80 entries).

    Full collapse rules must match Anim_WriteSpecificItemSprites grouping
    logic from reference/aldonunez/sprites.asm. This stub produces a 1:1
    mapping (one NES 8x8 sprite → one Genesis 1x1 SAT entry) and pads to 80.

    STUB: 1:1 mapping. Multi-cell sprite grouping (e.g., Link body = 4 tiles
    collapsed to one 2x2 SAT entry) is NOT implemented. Replace this function
    at Phase 2 when the sprite system is defined.

    Coordinate conversion:
        NES OAM Y is top scanline - 1 (add 1 for screen Y).
        Genesis SAT Y adds 128 offset (VDP convention); X adds 128.
        Genesis SAT X/Y are stored pre-offset here (without the +128 bias)
        to match what the VDP reads; schema stores the raw VDP register value.
    """
    sat = []
    for sprite in oam_entries:
        nes_y = sprite["y"]
        nes_x = sprite["x"]
        tile  = sprite["tile"]
        attr  = sprite["attr"]

        # Skip off-screen sprites ($EF/$FF sentinel)
        if nes_y >= 0xEF:
            sat.append({"y": 0, "size_link": 0, "x": 0, "attr_tile": 0})
            continue

        # Convert NES Y to Genesis Y (NES Y + 1 for screen position + 128 VDP bias)
        gen_y = (nes_y + 1 + 128) & 0x1FF

        # Convert NES X to Genesis X (+ 128 VDP bias)
        gen_x = (nes_x + 128) & 0x1FF

        # Size = 0 (1×1 cell = 8×8 pixels) — stub; should be 2x2 for 16x16 sprites.
        # Link field = 0 for last sprite in chain.
        size_link = 0x0000

        # Extract NES palette bits (attr bits 1-0) → Genesis palette (bits 14-13)
        nes_pal = attr & 0x03
        gen_pal = nes_pal  # PAL0 = BG, PAL1 = sprites; NES sprite pal 0 → GEN PAL1
        # In NES mode, sprite subpalettes 0-3 map to GEN PAL1.
        # Subpalette select within PAL1 is handled by tile index in the
        # CHR expansion scheme; palette field is always 1 for NES sprites.
        gen_pal_bits = 1  # Always PAL1 for NES sprites (stub)

        # H/V flip
        hflip = 1 if (attr & 0x40) else 0
        vflip = 1 if (attr & 0x80) else 0

        # Priority: NES attr bit 5 = 1 means behind BG; Genesis bit 15 = 1 = high priority.
        nes_behind_bg = (attr >> 5) & 1
        gen_priority = 0 if nes_behind_bg else 1

        # Tile index: stub — use NES tile index directly.
        # TODO Phase 2: map NES tile index through CHR atlas tile remapping table.
        tile_index = tile & 0x7FF

        attr_tile = (
            (gen_priority << 15) |
            (gen_pal_bits << 13) |
            (vflip << 12) |
            (hflip << 11) |
            tile_index
        )

        sat.append({
            "y": gen_y,
            "size_link": size_link,
            "x": gen_x,
            "attr_tile": attr_tile,
        })

    # Pad to 80 entries
    while len(sat) < 80:
        sat.append({"y": 0, "size_link": 0, "x": 0, "attr_tile": 0})

    return sat[:80]


# ─── Nametable excerpt extractor ──────────────────────────────────────────────

def extract_nametable_excerpt(ciram: bytes, nametable_index: int = 0) -> list:
    """
    Extract 32×30 tile nametable from NES CIRAM.
    ciram: 2048 bytes ($2000-$27FF, or $2000-$2FFF with 4-screen VRAM).
    nametable_index: 0 or 1 (CIRAM has 2 nametables of 1024 bytes each).
    Returns list of 960 integers (32×30 tile bytes).
    """
    base = nametable_index * 0x400
    nt = []
    for row in range(30):
        for col in range(32):
            offset = base + row * 32 + col
            if offset < len(ciram):
                nt.append(ciram[offset])
            else:
                nt.append(0)
    return nt


# ─── SHA-256 helper ───────────────────────────────────────────────────────────

def sha256_file(path: Path) -> str:
    """Return lowercase SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


# ─── Bundle reader ────────────────────────────────────────────────────────────

def _read_int_file(path: Path, default: int = 0) -> int:
    """Read a file containing a single integer (decimal or hex with 0x prefix)."""
    if not path.exists():
        return default
    text = path.read_text(encoding="utf-8").strip()
    if text.startswith("0x") or text.startswith("0X"):
        return int(text, 16)
    try:
        return int(text)
    except ValueError:
        return int(text, 16)


def _read_hex_file(path: Path, default: str = "00") -> str:
    """Read a file containing a hex string (no prefix, no spaces)."""
    if not path.exists():
        return default
    return path.read_text(encoding="utf-8").strip().lower()


def _hex_bytes(data: bytes, expected_len: int) -> str:
    """Convert bytes to lowercase hex string, zero-padded to expected_len bytes."""
    if len(data) < expected_len:
        data = data + b'\x00' * (expected_len - len(data))
    return data[:expected_len].hex()


def convert_bundle(bundle_dir: Path, scenario_id: str = None) -> dict:
    """
    Convert a Phase 1.5 NES capture bundle directory into a schema instance dict.
    """
    bundle_dir = Path(bundle_dir)

    if not bundle_dir.is_dir():
        raise FileNotFoundError(f"Bundle directory not found: {bundle_dir}")

    # ── Required files ────────────────────────────────────────────────────────
    oam_path    = bundle_dir / "oam.bin"
    palram_path = bundle_dir / "palram.bin"
    ciram_path  = bundle_dir / "ciram.bin"
    ram_path    = bundle_dir / "ram.bin"
    png_path    = bundle_dir / "screenshot.png"
    frame_path  = bundle_dir / "frame.txt"
    input_path  = bundle_dir / "input_log.txt"
    rng_path    = bundle_dir / "rng_seed.txt"

    # ── Frame / input / RNG scalars ───────────────────────────────────────────
    frame = _read_int_file(frame_path, 0)

    input_text = _read_hex_file(input_path, "00")
    input_bitmask = int(input_text[:2], 16) if len(input_text) >= 2 else 0

    rng_text = _read_hex_file(rng_path, "0000")
    rng_seed = int(rng_text[:4], 16) if len(rng_text) >= 4 else 0

    # ── NES RAM ───────────────────────────────────────────────────────────────
    ram = ram_path.read_bytes() if ram_path.exists() else b'\x00' * 2048

    # Room ID: NES $EB
    room_id = ram[0x00EB] if len(ram) > 0x00EB else 0
    # Quest: NES $10C
    quest = (ram[0x010C] & 0x01) if len(ram) > 0x010C else 0
    # RNG current: NES $0619-$061A
    rng_current = 0
    if len(ram) > 0x061A:
        rng_current = (ram[0x0619] << 8) | ram[0x061A]

    # ── Link state ────────────────────────────────────────────────────────────
    def _ram(offset, default=0):
        return ram[offset] if len(ram) > offset else default

    link = {
        "x":            _ram(0x0070),
        "y":            _ram(0x0084),
        "dir":          _ram(0x0098) % 4,
        "action":       _ram(0x0641),
        "anim_frame":   _ram(0x0010) % 16,  # simplified from frame counter
        "hp":           _ram(0x066F),
        "invuln_timer": _ram(0x0627),
        "b_item":       _ram(0x0657),
    }

    # ── Enemy state ───────────────────────────────────────────────────────────
    enemies = []
    for slot in range(16):
        enemies.append({
            "type":         _ram(0x0340 + slot),
            "x":            _ram(0x0470 + slot),
            "y":            _ram(0x0460 + slot),
            "dir":          _ram(0x04B0 + slot) % 4,
            "action":       _ram(0x0420 + slot),
            "hp":           _ram(0x06B0 + slot),
            "anim_frame":   _ram(0x0560 + slot),
            "projectile_id": _ram(0x04C0 + slot),
        })

    # ── Item state ────────────────────────────────────────────────────────────
    items = []
    for slot in range(8):
        items.append({
            "type":  _ram(0x0410 + slot),
            "x":     _ram(0x0490 + slot),
            "y":     _ram(0x0480 + slot),
            "state": _ram(0x05B0 + slot),
        })

    # ── RAM buckets ───────────────────────────────────────────────────────────
    ram_bytes_obj = {
        "globals":           _hex_bytes(ram[0x0000:0x0100], 256),
        "link_state_block":  _hex_bytes(ram[0x0620:0x0680], 96),
        "enemy_state_block": _hex_bytes(ram[0x0340:0x0600], 480),
        "save_buffer":       _hex_bytes(b'\x00' * 2304, 2304),  # NES SRAM not in ram.bin
    }
    # Note: save_buffer is NES SRAM $6000-$68FF; not present in ram.bin (which
    # covers $0000-$07FF). If the bundle includes sram.bin, read from there.
    sram_path = bundle_dir / "sram.bin"
    if sram_path.exists():
        sram = sram_path.read_bytes()
        # NES SRAM starts at $6000; extract $6000-$68FF (2304 bytes)
        ram_bytes_obj["save_buffer"] = _hex_bytes(sram[0:2304], 2304)

    # ── PALRAM → CRAM ─────────────────────────────────────────────────────────
    palram = palram_path.read_bytes() if palram_path.exists() else b'\x00' * 32
    cram = palram_to_cram(palram)

    # ── OAM ───────────────────────────────────────────────────────────────────
    oam_raw = oam_path.read_bytes() if oam_path.exists() else b'\x00' * 256
    oam_entries = []
    for i in range(64):
        base = i * 4
        if base + 3 < len(oam_raw):
            oam_entries.append({
                "y":    oam_raw[base + 0],
                "tile": oam_raw[base + 1],
                "attr": oam_raw[base + 2],
                "x":    oam_raw[base + 3],
            })
        else:
            oam_entries.append({"y": 0xFF, "tile": 0, "attr": 0, "x": 0})

    # ── OAM → SAT (stub) ──────────────────────────────────────────────────────
    sat = oam_to_sat(oam_entries)

    # ── Nametable excerpt ─────────────────────────────────────────────────────
    ciram = ciram_path.read_bytes() if ciram_path.exists() else b'\x00' * 2048
    nametable_excerpt = extract_nametable_excerpt(ciram, nametable_index=0)

    # ── Plane excerpts (NES → Genesis nametable conversion stub) ──────────────
    # NES nametable tiles → Genesis plane entries.
    # Full conversion requires the BG tile atlas remapping table (Phase 2).
    # Stub: each NES tile index becomes a Genesis nametable word with
    # tile=tile_index, palette=0, no flip, no priority.
    def _nt_to_plane(nt: list) -> list:
        plane = []
        for tile in nt:
            # TODO Phase 2: add tile atlas offset and palette from attribute table.
            plane.append(tile & 0x7FF)  # raw tile index, no flags
        # Pad or truncate to 896 entries (32×28 tiles)
        if len(plane) > 896:
            plane = plane[:896]
        while len(plane) < 896:
            plane.append(0)
        return plane

    plane_a_excerpt = _nt_to_plane(nametable_excerpt[:896])
    plane_b_excerpt = [0] * 896  # NES has no Plane B equivalent

    # ── Screenshot SHA-256 ────────────────────────────────────────────────────
    if png_path.exists():
        screenshot_sha256 = sha256_file(png_path)
    else:
        print(
            f"WARNING: screenshot.png not found in {bundle_dir}. "
            "Using placeholder SHA-256.",
            file=sys.stderr,
        )
        screenshot_sha256 = "0" * 64

    # ── Assemble instance ─────────────────────────────────────────────────────
    instance = {
        "frame":            frame,
        "input_bitmask":    input_bitmask,
        "rng_seed":         rng_seed,
        "rng_current":      rng_current,
        "room_id":          room_id,
        "quest":            quest,
        "link":             link,
        "enemies":          enemies,
        "items":            items,
        "ram_bytes":        ram_bytes_obj,
        "cram":             cram,
        "sat":              sat,
        "oam":              oam_entries,
        "plane_a_excerpt":  plane_a_excerpt,
        "plane_b_excerpt":  plane_b_excerpt,
        "nametable_excerpt": nametable_excerpt,
        "screenshot_sha256": screenshot_sha256,
    }

    return instance


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description=(
            "Convert a Phase 1.5 NES capture bundle into a parity oracle schema instance."
        )
    )
    parser.add_argument(
        "bundle_dir",
        help=(
            "Path to capture bundle directory (e.g., "
            "build/generated/nes_reference/<rom_hash>/<scenario_id>/)."
        ),
    )
    parser.add_argument(
        "--scenario-id",
        help="Override scenario ID (default: infer from bundle_dir name).",
    )
    parser.add_argument(
        "--out",
        help="Write schema JSON to this file instead of stdout.",
    )
    args = parser.parse_args()

    bundle_dir = Path(args.bundle_dir)
    scenario_id = args.scenario_id or bundle_dir.name

    try:
        instance = convert_bundle(bundle_dir, scenario_id)
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(3)

    json_str = json.dumps(instance, indent=2)

    if args.out:
        try:
            with open(args.out, "w", encoding="utf-8") as f:
                f.write(json_str)
            print(f"Written to {args.out}", file=sys.stderr)
        except OSError as e:
            print(f"ERROR writing output: {e}", file=sys.stderr)
            sys.exit(3)
    else:
        print(json_str)


if __name__ == "__main__":
    main()
