"""uw_bg_gate.py — dungeon BG byte-exact gate over the cached room goldens.

SCOPE, stated precisely:

  For every cached NES/Gen dungeon room pair, runs
  tools/parity/cave_golden/cave_byte_diff.py, whose gate is:
    * BG palette (Genesis CRAM) byte-exact against NES PALRAM mapped
      through the misc_palettes LUT, and
    * every NES BG play cell has a Genesis tile at the structural offset.

  It does NOT gate rendered-RGB, sprite palettes, or OAM->SAT. Those are
  reported by the differ as info and are explicitly outside this verdict.
  Saying "dungeon BG byte-exact" and meaning "the dungeon is correct"
  would be the RULE V1 failure, so the verdict line names the gate.

Goldens are captured by tools/parity/cave_golden/run_dungeon_sweep.py into
C:/tmp/cave_golden as nes_L<L>Q<Q>_R<RR>/ and gen_L<L>Q<Q>_R<RR>/. This
gate only diffs what is already captured; it never captures.

Usage:
    python tools/parity/uw_bg_gate.py
    python tools/parity/uw_bg_gate.py --emit-evidence dungeons

Exit codes:
    0  every cached pair passes the gate
    1  one or more fail
    2  no cached pairs found
"""
from __future__ import annotations

import argparse
import collections
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
GOLDEN = pathlib.Path(r"C:\tmp\cave_golden")
DIFFER = ROOT / "tools" / "parity" / "cave_golden" / "cave_byte_diff.py"
REPORT = ROOT / "docs" / "audit" / "uw_bg_status.md"


def find_pairs() -> list[tuple[str, pathlib.Path, pathlib.Path]]:
    pairs = []
    for gd in sorted(GOLDEN.glob("gen_L*")):
        nd = GOLDEN / gd.name.replace("gen_", "nes_", 1)
        if nd.is_dir():
            pairs.append((gd.name.replace("gen_", "", 1), nd, gd))
    return pairs


def run_gate() -> tuple[int, str, list[tuple[str, str]]]:
    pairs = find_pairs()
    if not pairs:
        return 2, f"uw_bg_gate: NO cached room pairs under {GOLDEN}", []

    counts: collections.Counter[str] = collections.Counter()
    fails: list[tuple[str, str]] = []
    for room, nd, gd in pairs:
        r = subprocess.run(
            [sys.executable, str(DIFFER), "--nes", str(nd), "--gen", str(gd)],
            capture_output=True, text=True,
        )
        ok = r.returncode == 0 and "GATE PASS" in r.stdout
        counts["PASS" if ok else "FAIL"] += 1
        if not ok:
            m = re.search(r"GATE DIVERGENCES.*?: (\d+)", r.stdout)
            fails.append((room, m.group(1) if m else "?"))

    total = counts["PASS"] + counts["FAIL"]
    if counts["FAIL"]:
        return 1, (
            f"uw_bg_gate: {counts['PASS']}/{total} rooms pass the BG gate, "
            f"{counts['FAIL']} FAIL"
        ), fails
    return 0, (
        f"uw_bg_gate: {counts['PASS']}/{total} dungeon rooms BG byte-exact "
        "(CRAM via LUT + play-cell presence; rendered-RGB and sprites NOT gated)"
    ), fails


def write_report(verdict_line: str, fails: list[tuple[str, str]]) -> None:
    lines = [
        "# uw_bg_gate — dungeons DATA axis verdict",
        "",
        "> Generated by `tools/parity/uw_bg_gate.py`.",
        "> Gate = BG CRAM byte-exact via the misc_palettes LUT + every NES BG",
        "> play cell has a Genesis tile. Rendered-RGB, sprite palettes and",
        "> OAM->SAT are reported by the differ as info and are NOT gated here.",
        "",
        verdict_line,
        "",
    ]
    if fails:
        lines += ["## Failing rooms", ""]
        lines += [f"- `{r}` — {n} gate divergence(s)" for r, n in fails]
        lines += [""]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(prog="uw_bg_gate.py")
    ap.add_argument("--emit-evidence", metavar="SYSTEM",
                    help="on PASS, print a signed evidence block for SYSTEM's "
                         "DATA axis")
    args = ap.parse_args()

    rc, verdict_line, fails = run_gate()
    print(verdict_line)
    if rc == 2:
        return rc
    write_report(verdict_line, fails)
    if rc != 0:
        for room, n in fails[:20]:
            print(f"  FAIL {room}  divergences={n}")
        return rc

    if args.emit_evidence:
        sys.path.insert(0, str(ROOT / "tools" / "audit" / "completion"))
        from emit import EvidenceRecorder  # noqa: PLC0415

        rec = EvidenceRecorder(root=ROOT)
        for rel in ("tools/parity/uw_bg_gate.py",
                    "tools/parity/cave_golden/cave_byte_diff.py",
                    "data/rooms/dungeons.c",
                    "data/misc/palettes.c",
                    "src/game/dungeon/uw_render.c"):
            target = ROOT / rel
            if target.exists():
                rec.read(target)
        print(
            rec.emit(
                system=args.emit_evidence,
                axis="DATA",
                artifact=REPORT,
                verdict_line=verdict_line,
                command=(
                    "python tools/parity/uw_bg_gate.py --emit-evidence "
                    f"{args.emit_evidence}"
                ),
                emitted_by="tools/parity/uw_bg_gate.py",
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
